canonical/k8s-snap

k8s/args/k8sd, k8s/lib.sh, k8s/wrappers/services/k8sd, snap/snapcraft.yaml, src/k8s/cmd/k8s/k8s_add_node.go, src/k8s/cmd/k8s/k8s_bootstrap_cluster.go, src/k8s/cmd/k8s/k8s_cluster.go, src/k8s/cmd/k8s/k8s_join_node.go, src/k8s/cmd/k8s/k8s_list_cluster.go, src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/k8s/cluster/cluster.go
Introduces the following CLI commands:
* `add-node <name>`: generates a connection token for <name>
* `join-node <token>`: join a cluster with the token (to be executed on the <name> node)
The workflow now looks like this:
1. On the cluster node: 
```
$ k8s add-node <hostname of joining node or arbitrary name>
<token>
```
2. On the joining node:
```
k8s join-node <token>
```
The `--name` flag for `k8s join-node <token>` defaults to the hostname of the joining node.
This was tested locally with the binaries (k8s CLI is not integrated in the snap yet)
=> Add node joining to k8s clustering CLI

.github/workflows/e2e.yaml, k8s/network-requirements.sh, snap/snapcraft.yaml, src/k8s/go.mod, src/k8s/pkg/component/component.go, src/k8s/pkg/component/hook.go, src/k8s/pkg/utils/file.go, tests/e2e/lxd-profile.yaml, tests/e2e/templates/nginx-pod.yaml, tests/e2e/tests/e2e_util/config.py, tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_smoke.py
To get the CNI working:
```bash
sudo snap install ./k8s.snap --dangerous
sudo /snap/k8s/current/k8s/connect-interfaces.sh
sudo /snap/k8s/current/k8s/network-requirements.sh
sudo k8s init
sudo k8s enable network 
```
Having `kubernetes-support` interface on `k8sd` is not ideal, however we can not check existing paths without it. Although `mount-observe` feels like it should be enough.
Passing in dynamic values to deployment mechanism is also up for discussion.
=> Adding the network enablement support

src/k8s/pkg/component/component.go
Currently, we are unable to disable a component using the `k8s disable` command. This PR introduces a fix for this process.
=> Fix `enable` and `disable` commands for k8s `components`

build-scripts/components/kubernetes/patches/default/0001-use-a-resolv.conf-file-with-non-loopback-nameservers.patch, build-scripts/components/kubernetes/patches/default/0001-use-resolv.conf-file-with-non-loopback-nameservers.patch
Patch Kubelet so that it picks a `resolv.conf` file from the host that contains valid non-loopback upstream nameserver addresses.
This is useful so that we can remove friction from pods being unable to resolve external hostnames (e.g. `canonical.com`).
Build the snap with the applied patch, and try to resolve an external hostname:
```
kubectl run --rm -it --image alpine -- nslookup canonical.com
```
It should the nameservers configured by systemd-resolve and work without issues. The same does not happen if `/etc/resolv.conf` is used instead, since the loopback address does not work inside the pod.
The implementation is loosely based on https://github.com/canonical/microk8s/blob/master/scripts/find-resolv-conf.py
=> Use a resolv.conf file with non-loopback addresses by default

k8s/connect-interfaces.sh, snap/snapcraft.yaml
- remove unused account-control interface (we do not edit group memberships)
- tidy up connect-interfaces.sh script
- do not attempt to connect removed `k8s-*` interfaces
=> Cleanup snap interface connections

src/k8s/api/v1/cluster.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/endpoints.go
Provides an endpoint to retrieve an admin kubeconfig, e.g. for the charm. 
Note that this PR provides an initial implementation of the endpoint. As discussed, we might need argument overwrites (e.g. server address) in the future. For that, the `GetKubeConfigRequest` object can easily be extended later as needed.
The CLI is hidden and only a convenience for internal dev and test work (the same output can be obtained with `kubectl config view --raw`).
=> Add k8s config REST endpoint and CLI command

tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_storage.py
After #56, use the `k8s kubectl` command in e2e tests
=> Use `k8s kubectl` in e2e tests

tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_storage.py
`check=True` is set by default on `util.run` at https://github.com/canonical/k8s-snap/blob/main/tests/e2e/tests/e2e_util/util.py#L18
Cleanup the code a bit, in hope that future tests do not clutter by imitating the existing ones.
=> drop extraneous check=True from e2e tests

src/k8s/pkg/k8s/client/cluster_node.go
The check for this in `k8s init` was already added in (#45). This PR also adds it to the `join-node` workflow.
=> Wait for k8sd to become up in CLI

src/k8s/cmd/k8s-dqlite/main.go, src/k8s/cmd/k8s/main.go, src/k8s/cmd/k8sd/main.go
Do not print duplicate error messages in case of CLI errors:
```
$ k8sd init 
Error: unknown command "init" for "k8sd"
Run 'k8sd --help' for usage.
INFO[0000] k8sd command failed                           error="unknown command \"init\" for \"k8sd\""
```
```
$ k8sd init
Error: unknown command "init" for "k8sd"
Run 'k8sd --help' for usage.
```
=> chore: improve error handling on CLI

src/k8s/api/v1/cluster.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/utils/k8s/client.go, src/k8s/pkg/utils/k8s/status.go, src/k8s/pkg/utils/k8s/status_test.go
This commit introduces a client to query the k8s cluster. 
It wraps the official go-k8s client library and introduces `ClusterReady` in the k8s Status.
=> Add k8s client and ClusterReady check

src/k8s/api/v1/cluster.go, src/k8s/cmd/k8s/formatter/formatter.go, src/k8s/cmd/k8s/k8s_status.go
Adds flags to specify in which format the CLI output should be displayed.
Current output (the `:` seem to be a bug in the components endpoint that I address in a follow-up PR)
```
ubuntu@init:~/k8s$ sudo k8s status
k8s is running
high-availability: no
components:
: 
: 
: 
dns: disable
storage: disable
network: enable
```
=> Format cluster status CLI output

src/k8s/cmd/k8s/k8s_helm.go, tests/e2e/tests/test_cilium_e2e.py, tests/e2e/tests/test_clustering.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_smoke.py, tests/e2e/tests/test_storage.py
Adds the Cilium end-to-end connectivity tests. These require the cilium CLI to be downloaded and run.
There is one test that fails on LXD, see the inline note in the test.
=> Run cilium end-to-end connectivity tests

src/k8s/api/v1/cluster.go, src/k8s/api/v1/component.go, src/k8s/cmd/k8s/formatter/formatter.go, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_add_node.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_cluster.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_generate_auth_token.go, src/k8s/cmd/k8s/k8s_init.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_kubectl.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_status.go, src/k8s/cmd/k8s/main.go, src/k8s/pkg/k8s/client/client.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8sd/api/impl/component.go, src/k8s/pkg/k8sd/api/impl/k8s-dqlite.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/utils/control.go, src/k8s/pkg/utils/control_test.go, src/k8s/pkg/utils/k8s/status.go, tests/e2e/tests/test_cilium_e2e.py, tests/e2e/tests/test_clustering.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_smoke.py, tests/e2e/tests/test_storage.py
* Adds `--wait-ready` flag that blocks until a node is ready
* Adds `--timeout`
* `k8s status` always waits for API server to become ready (with timeout)
* Fixes a bug in `GetComponents` that added empty component entries to the result.
```
ubuntu@my-node:~/k8s$ sudo k8s status --wait-ready
k8s is ready.
high-availability: no
control-plane nodes:
my-node: 10.84.220.162
components:
dns        disabled
network    enabled
storage    disabled
```
=> Polish k8s status CLI command

src/k8s/pkg/k8sd/database/kubernetes_auth_tokens.go, src/k8s/pkg/k8sd/database/kubernetes_auth_tokens_test.go, src/k8s/pkg/k8sd/database/sql/queries/kubernetes-auth-tokens/delete-by-token.sql, src/k8s/pkg/k8sd/database/sql/queries/kubernetes-auth-tokens/delete-by-username.sql
Extend the database schema to allow deleting a Kubernetes token by token or username/groups. This is needed to handle the deletion of cluster nodes.
- Add `delete-by-username.sql` and `delete-by-token.sql` queries
- Add `database.DeleteToken()` and database.DeleteTokenOf()` to the schema
- Add unit tests
=> Add support for deleting Kubernetes auth tokens

tests/e2e/tests/e2e_util/harness/lxd.py
Minor PR that prevents our e2e logs from being filled with noisy `pushing file ....` messages in case of failure.
=> de-noise lxd file push output

tests/e2e/requirements-test.txt, tests/e2e/tests/conftest.py, tests/e2e/tests/e2e_util/config.py, tests/e2e/tests/e2e_util/harness/__init__.py, tests/e2e/tests/e2e_util/harness/base.py, tests/e2e/tests/e2e_util/harness/juju.py, tests/e2e/tests/e2e_util/harness/local.py, tests/e2e/tests/e2e_util/harness/lxd.py, tests/e2e/tests/e2e_util/harness/multipass.py, tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_cilium_e2e.py, tests/e2e/tests/test_clustering.py, tests/e2e/tests/test_dns.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_retry.py, tests/e2e/tests/test_smoke.py, tests/e2e/tests/test_storage.py
With some spare cycles, i noticed there was a `TODO` on the e2e testing to improve the retry logic.
This PR wraps tenacity's retry logic to run commands on harnesses or on local commands
=> Update E2E test's retry logic to use tenacity

.github/workflows/go.yaml, src/k8s/go.mod, src/k8s/go.sum
Run `go mod tidy`, and update the CI to properly check for uncommitted diffs
=> chore: run go mod tidy

k8s/components/components.yaml, k8s/connect-interfaces.sh, snap/snapcraft.yaml, src/k8s/api/v1/component.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_enable_ingress.go, src/k8s/pkg/component/component.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/network.go, src/k8s/pkg/component/storage.go, src/k8s/pkg/k8s/client/component.go, src/k8s/pkg/k8sd/api/component.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/utils/k8s/restart_daemonset.go, src/k8s/pkg/utils/k8s/restart_deployment.go, tests/e2e/lxd-profile.yaml, tests/e2e/templates/ingress-test.yaml, tests/e2e/tests/test_ingress.py
Added ingress support through Cilium. I've also modified the `Component` manager and let components declare parents to update their configuration.
Currently everything seems to operate normally without the kube-proxy replacement which is listed as a [requirement](https://docs.cilium.io/en/stable/network/servicemesh/ingress/#prerequisites).
=> Added ingress support

snap/snapcraft.yaml
Starting the k8s snap sometimes timeouted because containerd failed to come up in time. Increasing the timeout fixes this.
=> Increase snap start-timeout

snap/snapcraft.yaml
Ensure symlinked binaries are symlinks on the resulting snap. Reduces the size of the unpacked snap (by default, the `cp` command would create multiple identical binaries).
=> ensure all k8s binaries are symlinks

.github/workflows/e2e.yaml
This will spin up a TMate session whenever the e2e run fails. You then can connect to the session by using the credentials printed out in the build step.
Make sure to have your SSH keys setup in your GH profile as only the actor (mostly the PR author) will be able to access the session. The session will close within 10 min if no one connects to it.
=> Add tmate to Github CI

tests/e2e/tox.ini
Stop the CI if one test fails. Right now, we continue to run all tests which accumulates several hours of "wasted" GH runner time.
Let's save some company money...
=> Abort e2e tests after first test failure

tests/e2e/lxd-profile.yaml
Update the LXD profile to allow containers to mount loopback devices.
Note that adding these devices on the profile does not clutter the host or the container with extra loop devices. It only ensures that they can be used as needed.
```bash
lxc launch ubuntu:22.04 -p default -p k8s-e2e test-container
lxc shell test-container
truncate -s 1G a.img
losetup -fP a.img
```
=> Support loopback devices on LXD profile

src/k8s/api/v1/cluster.go, src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/setup/k8s_dqlite.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/hooks.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/database/cluster_configs_test.go, src/k8s/pkg/k8sd/database/clusterconfigs/cluster_configs.go, src/k8s/pkg/k8sd/database/clusterconfigs/cluster_configs_merge.go, src/k8s/pkg/k8sd/database/kubernetes_auth_tokens.go, src/k8s/pkg/k8sd/database/schema.go, src/k8s/pkg/k8sd/database/worker.go, src/k8s/pkg/utils/cert/storage.go, src/k8s/pkg/utils/clusterconfigs.go, tests/e2e/tests/test_clustering.py
Introduces a more flexible approach for modifying cluster configuration during bootstrap with the addition of a --interactive flag to the k8s bootstrap command.
To improve code organization and readability, relocates the cluster configuration logic into a dedicated package, as exemplified by clusterconfigs.NewDefault().
Addresses an issue in clusterconfig.Merge where Authorization config was missing and ensures proper calculation of the microcluster timeout. The timeout now accurately reflects values provided via the --timeout flag by considering the context.
Note: I only added two configs to demonstrate the concept and get this signed-off. More parameters will be added in follow-up PRs.
=> Add machinery to configure cluster on bootstrap

src/k8s/pkg/k8sd/api/cluster.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/component.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/k8sd/api/kubernetes_auth_tokens.go, src/k8s/pkg/k8sd/api/worker.go
Move the endpoint definitions in `endpoints.go`, such that we can easily look up the available APIs. Add missing endpoint names, comments and use a consistent naming scheme for the handlers.
In a similar vein, cleanup some parts of the components to return consistent error codes, depending on the error that occurs.
=> Cleanup API endpoint definitions and error codes

src/k8s/Makefile
Past versions of go-dqlite required this flag, but no longer https://github.com/canonical/go-dqlite/releases/tag/v1.20.0
=> Remove unnecessary CGO_LDFLAGS_ALLOW flag

src/k8s/pkg/component/component.go, src/k8s/pkg/component/gateway.go
This PR removes the workaround in `src/k8s/pkg/component/gateway.go` where a second manager around the helm client is created. The helm client only needs to know about the updated helm client config, which is done in a new function called `initializeHelmClientConfig()`.
The e2e tests for the k8s-snap confirmed the fix works and shows that the gateway controller does indeed get created.
```
ubuntu@bug-fix:~/k8s-snap/tests/e2e$ lxc shell k8s-e2e-af3fbd-1
root@k8s-e2e-af3fbd-1:~# k8s enable gateway
Component 'Gateway' enabled
root@k8s-e2e-af3fbd-1:~# k8s kubectl get gatewayclass
NAME     CONTROLLER                     ACCEPTED   AGE
cilium   io.cilium/gateway-controller   True       20s
``` 
[KU-286]: https://warthogs.atlassian.net/browse/KU-286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …
=> Initialize Helm Client Config

tests/e2e/README.md, tests/e2e/tests/conftest.py, tests/e2e/tests/e2e_util/harness/__init__.py, tests/e2e/tests/e2e_util/harness/base.py, tests/e2e/tests/e2e_util/harness/juju.py, tests/e2e/tests/e2e_util/harness/local.py, tests/e2e/tests/e2e_util/harness/lxd.py, tests/e2e/tests/e2e_util/harness/multipass.py, tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_cilium_e2e.py, tests/e2e/tests/test_clustering.py, tests/e2e/tests/test_dns.py, tests/e2e/tests/test_gateway.py, tests/e2e/tests/test_ingress.py, tests/e2e/tests/test_network.py, tests/e2e/tests/test_smoke.py, tests/e2e/tests/test_storage.py
I noticed that many of the e2e tests were doing the complete same tasks again and again.  I've pushed this reuse through to conftest.py into a pytest fixture called "instances" which starts the requested number of instances for a test, bootstraps the first node, then yields the instances as a list to the test procedure. 
While testing, i was using the juju test harness and have applied a number of improvements to that harness
The exec method now behaves more like the lxd and multipass harness in that it uses juju's stderr, stdout, returncode and even provides a way to pass in stdin through the `input` argument. 
Lastly, this creates a new `Instance` object that's returned from harness.new_instance which maps through the common harness methods like send_file, pull_file, exec, and …
=> Shrinkify many tests using a setup fixture

src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_status.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/cluster_node.go, src/k8s/pkg/k8s/setup/containerd.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/snap/services.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/utils/control/wait.go, src/k8s/pkg/utils/control/wait_test.go, src/k8s/pkg/utils/k8s/status.go, src/k8s/pkg/utils/sys.go, tests/e2e/tests/test_clustering.py
By default, microcluster commands are not retriable if something fails in the hooks (other microcluster apps ignore this, a fix is expected to be delivered this cycle). For now, we manually roll back node assignments and configs in the CLI.
Additionally, several checks and flags were added to improve CLI handling and resilience.
Note that this PR only cleans up control-plane nodes. Workers need a bit more work (see TODO in code) that will be tackled in follow-up PRs.
* Cleanup node if `k8s bootstrap` or `k8s join-cluster` fails
* Add proper error message if k8s is not run with root
* `k8s join-cluster` checks if the node is already bootstrapped and provides an actionable error message.
* `k8s status` shows nodes and components even if k8s is not ready.
* `k8s bootstrap` check if the node …
=> Improve clustering resilience and CLI

src/k8s/api/v1/worker.go, src/k8s/pkg/k8s/client/token.go, src/k8s/pkg/k8sd/api/endpoints.go
* Rename worker token response to match the control-plane response
* Rename worker API endpoint to match control-plane tokens endpoint
=> Cleanup API naming

src/k8s/go.mod, src/k8s/pkg/component/component.go, src/k8s/pkg/component/component_test.go, src/k8s/pkg/component/dns.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/interface.go, src/k8s/pkg/component/mock/mock.go, src/k8s/pkg/component/network.go, src/k8s/pkg/component/storage.go, src/k8s/pkg/k8sd/api/impl/component.go
This PR adds unit test harness(fixtures and mocks) to our `ComponentManager` utility which interacts with the helm client/cli to operate on components. 
In order to be able to override the mocked Helm action configuration, @bschimke95  advised me to use an `HelmConfigInitializer` interface that calls the real or fake `InitializeHelmClientConfig` function. This function either returns a fake action Configuration or the real one. 
The interface is added to the Helm Client and set when the new Component manager instance is created. This required adding the initializer as an argument to the Component manager and update references to the function.
The mock for the snap builds on the snap mock in this repo. I used the snap mock's pathprefix to be able to give the snap a fake …
=> Unit testing harness for ComponentManager

k8s/args/kube-controller-manager, k8s/args/kube-scheduler
This pull request introduces delegated authentication configuration for both `kube-scheduler` and`kube-controller-manager` components.
Our upcoming work on observability integration requires the functionality to scrape metrics from the cluster components. Currently, certain services fail to validate authentication requests because they lack the necessary configuration to perform token based validation. Specifically, they cannot handle TokenAccessReview and SubjectAccessReview for requests arriving via the secure port.  Delegated authentication will address this issue, ensuring that all components can securely validate the requests from external scrapers
https://github.com/kubernetes/kubernetes/pull/72491
=> Add delegated auth config for `kube-scheduler` and `kube-controller-manager`

tests/e2e/tests/e2e_util/harness/lxd.py
Improve visibility for lxc file push errors (unfortunately, some are sent to stdout instead of stderr and were dropped, making it hard to debug the reason for the test failures.)
=> Improve error message on failed lxc file push

src/k8s/go.mod, src/k8s/pkg/component/component.go, src/k8s/pkg/component/dns.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/component/network.go, src/k8s/pkg/component/storage.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/utils/k8s/client.go, src/k8s/pkg/utils/k8s/endpoints.go, src/k8s/pkg/utils/k8s/endpoints_test.go, src/k8s/pkg/utils/k8s/restart_daemonset.go, src/k8s/pkg/utils/k8s/restart_daemonset_test.go, src/k8s/pkg/utils/k8s/restart_deployment.go, src/k8s/pkg/utils/k8s/restart_deployment_test.go, src/k8s/pkg/utils/k8s/services.go, src/k8s/pkg/utils/k8s/services_test.go, src/k8s/pkg/utils/k8s/status.go, src/k8s/pkg/utils/k8s/status_test.go
Extend `type Snap interface` with a `KubernetesRESTClientGetter()`, and use it for initializing Kubernetes clients.
- Also cleanup some `if err := ...; err != nil {}` checks in files.
=> Retrieve Kubernetes REST Client from the snap interface

.github/workflows/strict.yaml
Ensure CI runs when pushing to autoupdate/strict branch from GitHub Actions
=> Ensure CI runs when pushing to autoupdate/strict branch

k8s/args/kube-apiserver, src/k8s/pkg/k8sd/setup/kube_apiserver.go
enabling the `NodeRestriction` plugin to put restrictions on the kubelet
https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#noderestriction
Among such restrictions are:
> kubelets will only be allowed to modify their own Node API object, and only modify Pod API objects that are bound to their node. kubelets are not allowed to update or remove taints from their Node API object
> Prevents kubelets from adding/removing/updating labels with a node-restriction.kubernetes.io/ prefix. This label prefix is reserved for administrators to label their Node objects for workload isolation purposes, and kubelets will not be allowed to modify labels with that prefix.
=> Enable NodeRescript admission plugin

src/k8s/api/v1/types.go, src/k8s/api/v1/types_test.go
Currently, any bootstrap config specified during k8s bootstrap is ignored, because the marshal/unmarshal implementation is broken.
This PR ensures that the conversion of the bootstrap from a map to yaml and back works.
There is a bug because we need tags to ensure proper marshaling and unmarshaling of the bootstrap config.
Adding the yaml tags solves our problem:
```
type BootstrapConfig struct {
Components []string `yaml:"components"`
ClusterCIDR string `yaml:"cluster-cidr"`
}
```
=> Fix bootstrap config conversion

docs/src/tutorial/getting-started.md
Follow-up PR to https://github.com/canonical/k8s-snap/pull/120.
Corrects manifest link and improves naming.
=> [Follow up] Docs: getting-started manifest link

src/k8s/pkg/k8sd/setup/containerd.go
If any of the cni plugins already exist, do not fail. Fixes the following error:
```
root@t1:~# k8s bootstrap
Failed with error: failed to configure containerd: failed to symlink cni plugin bandwidth: symlink cni /opt/cni/bin/bandwidth: file exists
```
=> do not fail if cni plugins already exist

src/k8s/hack/compile-dynamic-dqlite.sh, src/k8s/hack/compile-static-dqlite.sh
Do not fetch `sys/queue.h` from a remote URL that we don't control, rather use the file that exists on the host. Tested that the file is there for all archs we target.
=> use queue.h from host libc6-dev

build-scripts/components/runc/build.sh, build-scripts/components/runc/patches/v1.1.12/0001-Disable-static-PIE-on-arm64.patch
Fixes
```
go build -trimpath -buildmode=pie  -tags "seccomp apparmor netgo osusergo" -ldflags "-X main.gitCommit=v1.1.12-0-g51d5e94 -X main.version=1.1.12 -linkmode external -extldflags --static-pie -s -w" -o runc .
/snap/go/10482/pkg/tool/linux_arm64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find rcrt1.o: No such file or directory
collect2: error: ld returned 1 exit status
```
=> Disable runc static PIE builds on arm64

docs/src/explanation/about.md
Adds an about page for Canonical Kubernetes 
N.B. Community link relies on #149
=> KU-213 Docs: Add about page

docs/src/reference/community.md, docs/src/reference/index.md
Adds the community page. There are two links which we don't have anything for yet:
- contributing to docs
- contributing to code
which have been marked as TODOs
=> Docs: add community page

docs/src/explanation/about.md, docs/src/howto/install/snap.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_add_node.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_remove_node.go
Report more information about what potentially long-running commands are doing. Ensure CLI feedback messages are consistent.
- Tweak the bootstrap/join cli output so users know a bit more about what's going on.
- Addresses [ST1005](https://staticcheck.io/docs/checks#ST1005) and makes error strings consistent throughout `./cmd/k8s`.
=> CLI feedback messages

src/k8s/api/v1/errors.go, src/k8s/cmd/k8s/errors/errors.go, src/k8s/cmd/k8s/k8s_status.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/interface.go
Make the `k8s status` command fail fast in situations where status is unlikely to be forthcoming -- e.g. when the api-server is unavailable and we have not explicitly asked for `--wait-ready`.
- New `k8sdClient.IsKubernetesAPIServerReady` function that attempts to get cluster endpoints
- Call this new func in `k8s_status.go` before any waiting/timeout context
- Present helpful message when we're unable to get apiserver endpoints
The `k8s status` command has a `--timeout` option that can return quickly (3s) if configured, though the default is 90s. Prior to this PR, status will happily wait the entire `timeout` until `k8sdClient.ClusterStatus` fails if `client-go` can't talk to kubernetes. With this PR, status will fail fast if:
- we're not bootstrapped
- `client-go` can't reach a …
=> k8s status should return immediately if the api server is down

src/k8s/api/v1/types.go, src/k8s/api/v1/types_test.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/pkg/k8sd/types/cluster_config.go, src/k8s/pkg/k8sd/types/cluster_config_test.go, src/k8s/pkg/utils/file.go
Ensure rbac is enabled during bootstrap by default.  Only disable it if user explicitly sets enable = `false`.
=> enable rbac by default, configurable on bootstrap

k8s/lib.sh
`test_node_cleanup` e2e test fails often. Looks like sometimes we do not clear containerd mounts
The change attempts to address the following error:
```
Status  Spawn               Ready               Summary
Done    today at 09:25 UTC  today at 09:26 UTC  Stop snap "k8s" services
Done    today at 09:25 UTC  today at 09:26 UTC  Run remove hook of "k8s" snap if present
Done    today at 09:25 UTC  today at 09:26 UTC  Disconnect interfaces of snap "k8s"
Done    today at 09:25 UTC  today at 09:26 UTC  Remove aliases for snap "k8s"
Done    today at 09:25 UTC  today at 09:26 UTC  Make snap "k8s" unavailable to the system
Done    today at 09:25 UTC  today at 09:26 UTC  Remove security profile for snap "k8s" (x1)
Done    today at 09:25 UTC  today at 09:26 UTC  Remove data for snap "k8s" (x1)
Done …
```
=> Improve remove hook

src/k8s/cmd/k8s/k8s_add_node.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_disable_dns.go, src/k8s/cmd/k8s/k8s_disable_gateway.go, src/k8s/cmd/k8s/k8s_disable_ingress.go, src/k8s/cmd/k8s/k8s_disable_loadbalancer.go, src/k8s/cmd/k8s/k8s_disable_metrics_server.go, src/k8s/cmd/k8s/k8s_disable_network.go, src/k8s/cmd/k8s/k8s_disable_storage.go, src/k8s/cmd/k8s/k8s_enable_dns.go, src/k8s/cmd/k8s/k8s_enable_gateway.go, src/k8s/cmd/k8s/k8s_enable_ingress.go, src/k8s/cmd/k8s/k8s_enable_loadbalancer.go, src/k8s/cmd/k8s/k8s_enable_metrics_server.go, src/k8s/cmd/k8s/k8s_enable_network.go, src/k8s/cmd/k8s/k8s_enable_storage.go, src/k8s/cmd/k8s/k8s_generate_auth_token.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_status.go
By default, PersistentPreRun hooks are not chained. If a child command overwrites this, the parent hook is not executed.
This caused the global permissions check to be overwritten in the sub-commands and caused misleading error messages when running commands without root permission.
There is a flag to introduce the chaining behavior but this unnecessarily complicates the commands. Since we have shallow command, using `PreRun` hooks is just fine. 
Btw, we are not the only ones that got confused by this feature: https://github.com/spf13/cobra/issues/252
=> Use PreRunE for sub-commands

src/k8s/pkg/component/network.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/utils/file.go, src/k8s/pkg/utils/file_test.go
Cilium fails to deploy if `/sys` is not mount with shared propagation.
This PR adds a check to verify that `/sys` is mounted with the propagation type.
=> Warn if /sys mount propagation is not shared

src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, tests/e2e/tests/conftest.py, tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_cilium_e2e.py, tests/e2e/tests/test_cleanup.py, tests/e2e/tests/test_dns.py, tests/e2e/tests/test_gateway.py, tests/e2e/tests/test_ingress.py, tests/e2e/tests/test_loadbalancer.py, tests/e2e/tests/test_metrics_server.py, tests/e2e/tests/test_network.py
Enable components after a successful `k8s bootstrap`. These will include `dns` and `network` by default, or any valid set of component names that the user provided during bootstrap.
- Giant switch
We maintain various lists of components in `cmd/k8s/k8s_enable`, `pkg/snap/snap`, a couple interfaces, and as part of our v1 api endpoint list.  We should consolidate those to a single source-of-truth where names, attrs, and methods can be managed together.
But that's not what this PR is about.  This PR ensures that default components are enabled after a successful bootstrap, e.g.:
```bash
$ sudo k8s bootstrap -v -d --interactive
Which components would you like to enable? () [dns, network]: dns, ham, network, storanges
Please set the Cluster CIDR? [10.1.0.0/16]: 
Bootstrapping the cluster. This …
```
=> Enable components specified during bootstrap by default

src/k8s/api/v1/node.go, src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_local_node_status.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/cluster_node.go, src/k8s/pkg/k8s/client/interface.go, src/k8s/pkg/k8s/client/mock/mock.go, src/k8s/pkg/k8s/client/node.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/k8sd/api/node.go, src/k8s/pkg/utils/node.go, tests/e2e/tests/e2e_util/util.py, tests/e2e/tests/test_clustering.py
Provides an endpoint to query the current status of the local k8s node. This is especially useful for the charm that wants to know the current role of specific node. It is not possible to query other nodes for security purposes.
Additionally,
* changed `ClusterMember` to `NodeStatus` to better reflect the new shared use
* added a hidden CLI command `k8s local-node-status` for testing.
* added basic test coverage by integrating assertions into the `test_clustering.py` test.
* use enum for datastore and cluster roles to not rely on random strings.
=> Add GET k8sd/node endpoint

docs/src/assets/arch.dsl, docs/src/assets/k8s-container.puml, docs/src/assets/k8s-services.puml, docs/src/assets/k8sd-component.puml, docs/src/assets/overview.puml, docs/src/explanation/about.md, docs/src/explanation/channels.md, docs/src/howto/index.md, docs/src/howto/install/snap.md, docs/src/howto/networking/default-dns.md, docs/src/howto/networking/default-ingress.md, docs/src/howto/storage.md, docs/src/index.md, docs/src/reference/architecture.md, docs/src/reference/community.md, docs/src/tutorial/add-remove-nodes.md, docs/src/tutorial/getting-started.md, docs/src/tutorial/kubectl.md
Some updates in our docs:
- use `bash` in all cli commands
- the snap now auto enables dns network and metrics server
- remove "components" from various places including our architecture doc
- include the arch.dsl used to produce all arch graphs
- same formatting in configuration options in howtos
- metrics-server is part of the distribution
- RBAC is on by default so we do not mention it
- local-storage vs storage fix
- --help fix
=> Tweaks in docs

src/k8s/pkg/component/network.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/setup/kube-proxy, src/k8s/pkg/k8sd/setup/kube_proxy.go, src/k8s/pkg/k8sd/setup/kube_proxy_test.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, tests/e2e/lxd-profile.yaml
Juju only supports specific devices. This commit removes the unsupported ones.
Also, the container cannot modify the sysctl config on LXD, thus we disable this setting in kube-proxy.
=> Update e2e lxd-profile and kube-proxy config

src/k8s/cmd/k8s/k8s_get_join_token.go, tests/e2e/tests/test_clustering.py
* Add guidance on what to do with the join token
* Add `--output-format` flag
Example output:
```
ubuntu@alice:~/k8s$ sudo k8s get-join-token node1
On the node you want to join call:
sudo k8s join-cluster eyJuYW1lIjoibm9kZTEiLCJzZWNyZXQiOiJlMzFkYjZlOTM0OTZmYjkxOTVkMjlmNTY0NTY0ODNiZTY1MmVjNWQ0Y2M4YzI0YjlhODAwNWQ4OTczYWNiMzBhIiwiZmluZ2VycHJpbnQiOiJjMTEwNGMxZGRiNDU4NjdhODJhOWU4ZWNiZWYwZTFjODA1NWNlOThiZDE3NDZkMDQ4OWI1ZWJlNzg1OWJkMWU5Iiwiam9pbl9hZGRyZXNzZXMiOlsiMTAuODQuMjIwLjIzNzo2NDAwIl19
ubuntu@alice:~/k8s$ sudo k8s get-join-token node2 -o json
{"join-token":"eyJuYW1lIjoibm9kZTIiLCJzZWNyZXQiOiI1NmJjZWI4MDY0NGM2NWIyYjc4ZTNhNWUzNGQ0NTMzOTBlMDFjMWZiODFiOWM0MDE3NTFiNTMxMGY2MjhhOTBlIiwiZmluZ2VycHJpbnQiOiJjMTEwNGMxZGRiNDU4NjdhODJhOWU4ZWNiZWYwZTFjODA1NWNlOThiZDE3NDZkMDQ4OWI1ZWJlNzg1OWJkMWU5Iiwiam9pb …
```
=> Improve k8s get-join-token output

src/k8s/pkg/utils/file.go, src/k8s/pkg/utils/file_test.go
With this PR, the following key-value in Kubelet argument file is now supported by the ParseArgumentLine function:
`--node-labels=node-role.kubernetes.io/control-plane=,node-role.kubernetes.io/worker=`
This is needed for KU-447 specifically for unit testing setup.kubelet.
=> Refactor ParseArgumentLine to support Kubernetes label values

src/k8s/pkg/component/dns.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/component/metrics_server.go, src/k8s/pkg/component/network.go, src/k8s/pkg/component/storage.go
Request enabled should be treated as true if not set in request, otherwise the functionality won't be refreshed with new settings.
=> Request enabled should be treated as true if not set in request

src/k8s/api/v1/cluster_config.go, src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/utils/database.go
Example output:
```
ubuntu@alice:~/k8s$ sudo k8s status
status: ready
high-availability: no
datastore:
master-nodes:
- 10.84.220.237:6400
standy-nodes: none
spare-nodes:
- 10.84.220.25:6400
network:
enabled: true
dns:
enabled: true
cluster-domain: cluster.local
service-ip: 10.152.183.108
upstream-nameservers:
- /etc/resolv.conf
metrics-server:
enabled: true
```
=> Update k8s status command

docs/src/explanation/index.md, docs/src/explanation/security.md, docs/src/reference/roadmap.md
Adds the security explainer and adjusts a few other pages accordingly.
=> Docs: add security page

src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_kubectl.go, src/k8s/cmd/k8s/k8s_set.go
* if `k8s get` is called without functionality it returns the full configuration
```
ubuntu@bob:~/k8s$ sudo k8s get
network:
enabled: true
dns:
enabled: true
cluster-domain: cluster.local
service-ip: 10.152.183.149
upstream-nameservers:
- /etc/resolv.conf
...
```
* `k8s kubectl` gives a meaningful error msg if cluster is not bootstrapped
```
ubuntu@bob:~/k8s$ sudo k8s kubectl get nodes -A
The cluster has not been initialized yet. Please call:
sudo k8s bootstrap
```
`k8s set --help` gives a hint how to find configurations.
```
ubuntu@bob:~/k8s$ sudo k8s set --help
Configure one of network, dns, gateway, ingress, local-storage, load-balancer, metrics-server.
Use `k8s get` to explore configuration options.
```
`k8s enable/disable` print feedback (`Enabling ingress...`)
```
ubuntu@bob:~/k8s$ …
```
=> CLI UX fixes

src/k8s/cmd/k8s/errors/errors.go, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_kubectl.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_set.go, src/k8s/cmd/k8s/k8s_status.go
Changes:
- remove global flags -d and -v
- flag descriptions should start with lowercase and should not end with a '.'
- command descriptions should start with a capital letter and should not end with a '.'
- error messages that suggest you to run a command should prefix the command with an empty line and double space and suffix the command with an empty line
- minor tweaks in the command descriptions
- few spelling errors
=> Small touches towards a homogeneous CLI

src/k8s/go.mod, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/api/cluster_tokens.go, src/k8s/pkg/utils/hostname.go, src/k8s/pkg/utils/hostname_test.go
Sanitise the node names that are used in microcluster.
- See `TestCleanHostname` about how sanitisation is performed (upper-case are lowered as well)
- Clean the hostname when bootstrapping (we cannot currently hijack the bootstrap endpoint of microcluster. If we had a custom bootstrap endpoint we could do it there instead
- Clean the hostname when generating node tokens.
=> Ensure valid node names

src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/types/cluster_config.go, src/k8s/pkg/k8sd/types/cluster_config_test.go, src/k8s/pkg/utils/cidr.go, src/k8s/pkg/utils/cidr_test.go
Allow users to specify a service CIDR during bootstrap.
- new ServiceCIDR default bootstrap config (10.152.183.0/24)
- interactive bootstrap prompt for ServiceCIDR
- add first address of the ServiceCIDR range(s) to the cert SANs
=> Configurable service CIDR

src/k8s/cmd/k8s/formatter/formatter.go, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_set.go, src/k8s/cmd/k8s/k8s_status.go
* Set global `--output-format/-o` flag for public k8s commands where applicable.
Feedback/Log messages are printed to `stderr` now, so that the content of `stdout` can be parsed, e.g. if `--output-format=json`
Example output:
```
ubuntu@peter:~/k8s$ sudo k8s bootstrap -o json
Bootstrapping the cluster. This may take some time, please wait.
{
"node": {
"name": "peter",
"address": "10.84.220.158"
}
}
ubuntu@peter:~/k8s$ sudo k8s bootstrap -o json 2> /dev/null
{
"node": {
"name": "peter",
"address": "10.84.220.158"
}
}
```
* Make `--timeout/-t` a global flag.
=> Update global  flags

src/k8s/cmd/util/args.go
=> Fix condition in cmdutil.ExactArgs()

src/k8s/api/v1/cluster_config.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/types/cluster_config.go
Use `load-balancer.l2-mode` and `load-balancer.bgp-mode` consistently in the code base
=> Use `load-balancer.l2-mode` and `load-balancer.bgp-mode` consistently

src/k8s/pkg/component/dns.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/cluster_config.go, src/k8s/pkg/k8s/client/component.go, src/k8s/pkg/k8s/client/kubernetes_auth_tokens.go
The timeout should only be set via CLI. Introducing hard-coded timeouts in the code may randomly break.
=> Remove timeout contexts

src/k8s/cmd/k8s/k8s_bootstrap.go
The options checker was too exact and also took the newline into account. The options validation therefore never passed.
=> Fix `k8s bootstrap` interactive mode

snap/snapcraft.yaml
`k8s-dqlite` is missing from the `bom.json` on the snap, fix that.
=> add missing k8s-dqlite entry in the bom.json

docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_join-cluster.md, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/interface.go, src/k8s/pkg/k8s/client/mock/mock.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/setup/kubelet.go
Small improvements to make the single-node cluster for development UX better.
- Configurable `hostname` and `address` in the `k8s bootstrap` command.
- Always include machine IP addresses as SANs to the generated self-signed certificates.
- Do not set the kubelet `--node-ip` if a loopback address is used.
You can bootstrap a cluster using the loopback address and get a functional cluster
```bash
k8s bootstrap --address 127.0.0.1:6400
```
=> Support single-node deployments

src/k8s/pkg/k8sd/setup/certificates.go
The certificates are being written to different locations, causing the API server to fail to start. This pull request modifies the destination paths of these certificates to the correct ones.
=> Write the External Datastore Certs in the Correct Location

src/k8s/cmd/k8s/k8s_set.go
Ensure `k8s set` fails if an invalid key is passed
=> fail k8s set on invalid key

src/k8s/pkg/k8sd/app/hooks_join.go
We are missing some checks for external datastores. Therefore, while attempting to join other control plane units, these fail to join the cluster. This pull request aims to fix that issue
=> Configure External Datastore

src/k8s/api/v1/cluster.go, src/k8s/api/v1/cluster_node.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/pkg/k8s/client/cluster.go, src/k8s/pkg/k8s/client/cluster_node.go, src/k8s/pkg/k8s/client/interface.go, src/k8s/pkg/k8s/client/mock/mock.go, src/k8s/pkg/k8sd/api/cluster_bootstrap.go, src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/utils/timeout.go
This PR adds the  `POST k8sd/cluster` endpoint to the k8s-snap.
The endpoints calls `postClusterBootstrap` which then calls the `cluster/control` endpoint in microcluster in order to create a new cluster.
=> POST k8sd/cluster endpoint to bootstrap a cluster

build-scripts/components/kubernetes/patches/default/0001-allow-all-nodes-to-get-k8sd-config.patch, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/component/dns.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/api/impl/k8sd.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/database/util_test.go, src/k8s/pkg/k8sd/types/node_config.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/utils/k8s/client.go, src/k8s/pkg/utils/k8s/configmap.go
Added `NodeConfigurationController` that handles watching and reconciling arguments on services. 
Restructured components(functionalities) to reduce code duplication and help with updating node config(`k8sd-config` configmap)
=> Propagate node configuration through kubernetes api

src/k8s/pkg/k8sd/api/cluster_join.go
The server-side context does not get the deadline from the client. Instead it will just be cancelled when the client context is cancelled. So, instead of querying the context from the context we do not set a deadline at all on the server-side and let't the client handle this.
=> Fix wrong context for joining cluster

src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/utils/k8s/endpoints.go, tests/integration/tests/test_clustering.py
Makes the k8s-snap joining process more robust and fixes #271 
See integration test runs here: https://github.com/canonical/k8s-operator/pull/54
This PR:
* Ensures that the `kubernetes API` server is ready
* Let the worker config request wait for the right context and not a fixed timeout
* Adds a retry to the k8s endpoint request.
=> Fix joining under high load

src/k8s/pkg/k8sd/setup/certificates.go
Remove certificate files if they are empty (such that stale or removed certificates are no longer used).
- Reduce some code duplication with helper `ensureFiles()` utility
- remove files if the cert contents are empty
=> Update setup.Ensure*PKI() functions to delete empty certificates

docs/src/_parts/commands/k8s.md, docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_completion.md, docs/src/_parts/commands/k8s_completion_bash.md, docs/src/_parts/commands/k8s_completion_fish.md, docs/src/_parts/commands/k8s_completion_powershell.md, docs/src/_parts/commands/k8s_completion_zsh.md, docs/src/_parts/commands/k8s_config.md, docs/src/_parts/commands/k8s_disable.md, docs/src/_parts/commands/k8s_enable.md, docs/src/_parts/commands/k8s_get-join-token.md, docs/src/_parts/commands/k8s_get.md, docs/src/_parts/commands/k8s_join-cluster.md, docs/src/_parts/commands/k8s_kubectl.md, docs/src/_parts/commands/k8s_remove-node.md, docs/src/_parts/commands/k8s_set.md, docs/src/_parts/commands/k8s_status.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go
* Remove `-t` for `--timeout`
* Remove `-o` for `--output-format`
* Rename `--config` to `--file`
=> remove short-form flags

src/k8s/api/v1/types_test.go, src/k8s/pkg/k8sd/pki/k8sdqlite_test.go, src/k8s/pkg/snap/util/node_test.go, src/k8s/pkg/snap/util/services_test.go, src/k8s/pkg/utils/errors/errors_test.go, src/k8s/pkg/utils/k8s/node_test.go
Minor PR
```
NewGomegaWithT is deprecated in favor of gomega.NewWithT, which does not stutter.
```
=> Use gomega NewWithT instead of deprecated NewGomegaWithT

src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/setup/kube_apiserver.go, src/k8s/pkg/k8sd/setup/kube_apiserver_test.go, src/k8s/pkg/k8sd/types/cluster_config_datastore.go, src/k8s/pkg/k8sd/types/cluster_config_datastore_test.go
Move the generation of kube-apiserver arguments from the datastore configuration into `pkg/k8sd/types`, and add focused unit tests
- Add `(Datastore).ToKubeAPIServerArguments()`
- Use it in `setup.KubeAPIServer()`
- Update callers and tests
- Add unit tests for ToKubeAPIServerArguments()
=> Add (Datastore).ToKubeAPIServerArguments() helper

docs/src/_parts/commands/k8s.md, docs/src/_parts/commands/k8s_disable.md, docs/src/_parts/commands/k8s_enable.md, docs/src/_parts/commands/k8s_get.md, docs/src/_parts/commands/k8s_set.md, docs/src/assets/arch.dsl, docs/src/assets/k8s-container.puml, docs/src/assets/k8s-services.puml, docs/src/explanation/about.md, docs/src/howto/storage.md, docs/tools/custom_conf.py, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_set.go, src/k8s/pkg/k8sd/api/endpoints.go
Tried to separate code/docs changes but our git diff CI did not like that... "changes not in repository".
Note: not every instance of the word "functionality" is renamed in docs because "feature" would not be appropriate in those instances. Eg: "If [...] your cluster will return to normal functionality."
=> Functionality -> Feature

src/k8s/pkg/client/dqlite/remove.go, src/k8s/pkg/client/dqlite/remove_test.go, src/k8s/pkg/client/dqlite/types.go, src/k8s/pkg/component/gateway.go, src/k8s/pkg/component/ingress.go, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/utils/control/retry.go, src/k8s/pkg/utils/control/retry_test.go
In a two node dqlite cluster, one is leader/voter and one is a spare node.
If the leader node should be removed, the leadership needs to be transferred to the remaining node first. 
The `go-dqlite` client provides a Transfer function that transfers the leadership to another node. However, this requires the other node to either be a voter or standby, not spare.
To work around this limitation, this PR:
1. assign the spare node the standby role
1. transfer leadership to the new standby node
1. create a new client to the new leader
1. remove the old leader node from the cluster
This approach is a bit problematic for several reasons. If a spare node is promoted to standby it needs to copy the whole database. For large dbs this might take significant amount of time. 
So, this implementation …
=> transfer leadership before removing the leader node

src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/api/cluster_tokens.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/types/worker.go, src/k8s/pkg/k8sd/types/worker_test.go, src/k8s/pkg/utils/certificate.go, src/k8s/pkg/utils/certificate_test.go
This PR addresses Mitm vulnerabilities for joining worker nodes by validating the server. 
A joining node validates the server (cluster member) by checking the servers certificate against the fingerprint of the join token. The joining node adds the certificate to its trusted certificates and the TLS connection is established, the joining node may now join the cluster.
=> Add fingerprint check when worker joins cluster

docs/src/howto/networking/default-loadbalancer.md, src/k8s/api/v1/bootstrap_config_test.go, src/k8s/cmd/k8s/k8s_bootstrap_test.go, src/k8s/cmd/k8s/testdata/bootstrap-config-full.yaml, src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/k8sd/types/cluster_config_convert_test.go, src/k8s/pkg/k8sd/types/cluster_config_merge_test.go, src/k8s/pkg/k8sd/types/cluster_config_validate.go, src/k8s/pkg/k8sd/types/cluster_config_validate_test.go
Currently only CIDRs can be specified for load-balancer.cidrs.
Accept IP range as well to the load-balaner.cidrs.
Example to set IP range:
```
sudo k8s set load-balancer.cidrs="10.1.0.0/16,10.2.0.100-10.2.0.200"
```
Fixes: #311
=> add support for ip range in load-balancer.cidrs

src/k8s/api/v1/join_config.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go
Allow specifying extra SANs when joining control plane nodes.
=> Allow specifying extra SANs when joining control plane nodes

src/k8s/pkg/k8sd/setup/embed/apiserver/auth-token-webhook.conf, src/k8s/pkg/k8sd/setup/kube_apiserver.go
For security reasons we want to connect to the apiserver using tls. We can use microcluster CA.
=> Use TLS when connecting to apiserver

docs/src/_parts/commands/k8s_get-join-token.md, src/k8s/cmd/k8s/k8s_get_join_token.go, tests/integration/tests/test_util/util.py
`k8s get-join-token` simply prints the token in stdout
=> remove --output-format from k8s get-join-token

src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/k8sd/app/app.go
To enable, `--pprof-address` needs to be specified in k8sd arguments.
=> add pprof debug endpoints (disabled by default)

k8s/components/charts/ck-loadbalancer/values.schema.json
Commit 6eb114f1dceac20af3863b30dca8de96e210d274 add support for ip ranges in k8sd config settings. However the helm chart ck-loadbalancer schema validation is not updated. Update ck-loadbalancer schema validation to validate ippool against cidr or start/stop or both.
=> Update loadbalancer ip pool schema to support ip range

src/k8s/pkg/component/loadbalancer.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/types/cluster_config_convert.go, src/k8s/pkg/k8sd/types/cluster_config_convert_loadbalancer.go, src/k8s/pkg/k8sd/types/cluster_config_convert_loadbalancer_internal_test.go, src/k8s/pkg/k8sd/types/cluster_config_convert_test.go, src/k8s/pkg/k8sd/types/cluster_config_features.go, src/k8s/pkg/k8sd/types/cluster_config_merge.go, src/k8s/pkg/k8sd/types/cluster_config_merge_test.go, src/k8s/pkg/k8sd/types/cluster_config_validate.go, src/k8s/pkg/k8sd/types/cluster_config_validate_test.go
Follow up PR on #324. Make sure the internal state separates CIDRs and IP ranges.
=> Properly handle LoadBalancer IPRanges in the internal state

build-scripts/patches/strict/0001-Strict-patch.patch, snap/snapcraft.yaml
Adjust systemd service definitions in `snapcraft.yaml`:
- Add `before` and `after` to note the order in which to start the services
- Adjust the strict patch for the updates to `snap/snapcraft.yaml`
- Add a 5s timeout to apiserver restarts
=> Adjust systemd service definitions

src/k8s/pkg/k8sd/controllers/node_configuration.go
Ensure that any changes in the kubeconfig files are picked up between client failures
=> re-create k8s client in case of failure

src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/provider.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/app/provider.go, src/k8s/pkg/k8sd/controllers/update_node_configuration.go, src/k8s/pkg/k8sd/controllers/update_node_configuration_test.go
This PR adds a controller that updates the `k8sd-config` config map of the cluster asynchronously.
It is triggered by the sending `struct{}` to the controllers `UpdateCh` (e.g. by the bootstrap hook or `k8s set`). 
This is a first effort of making commands return fast instead of e.g. waiting for service restarts and apply changes async. Follow-up work will move the component updates to a controller  as well.
Relates and works towards fixing:
#321 and #277
=> Decouple update k8sd-config configmap from k8s set API

docs/src/charm/howto/etcd.md, docs/src/charm/howto/index.md
This pull request introduces a How-To guide on integrating the Canonical Kubernetes operator with an external etcd datastore.
=> Add How-To Integrate `k8s-operator` with `etcd`

src/k8s/pkg/k8sd/app/app.go
Follow up fix for #339, use the admin client, as the node config cannot update the configmap:
```
Apr 18 17:49:12 u1 k8s.k8sd[1482]: 2024/04/18 17:49:12 failed to reconcile cluster configuration: failed to update node config: failed to update configmap, namespace: kube-system name: k8sd-config: configmaps "k8sd-config" is forbidden: User "system:node:u1" cannot patch resource "configmaps" in API group "" in the namespace "kube-system": can only read resources of this type
```
=> Use the admin client for updating the configmap

src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/controllers/update_node_configuration.go, src/k8s/pkg/k8sd/controllers/update_node_configuration_test.go, src/k8s/pkg/k8sd/types/cluster_config_kubelet.go, src/k8s/pkg/k8sd/types/cluster_config_kubelet_test.go
Add machinery to sign and verify the kubelet configmap contents. We currently specify `nil` keys everywhere for now.
Extend `types.KubeletFromConfigMap()` and `types.Kubelet.ToConfigMap()` to accept an optional ECDSA public and private key respectively.
If a non-nil key is passed:
- We hash the configuration contents (using `Kubelet.hash()`)
- In `Kubelet.ToConfigMap()` we use the private key and include it in the configmap as `k8sd-mac`
- In `types.KubeletFromConfigMap()` we use the public key to verify the hash and return an error otherwise.
- `ecdsa.SignASN1` will only sign `hash[:curveBitsize/8]`. We ensure that we don't verify mismatching signatures by ensuring that the key is large enough. The hash is a sha256 sum (32 bytes long), therefore we need at least `elliptic.P256()`
- Added …
=> Support signed kubelet configmap

build-scripts/patches/strict/0001-Strict-patch.patch, k8s/wrappers/services/containerd
Fixes appamor permission issue:
```
Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "2c33e5af7e6c928662576f3d4452ec94da99670bb2ffe88ca505938b51d93f31": OCI runtime exec failed: exec failed: unable to start container process: apparmor failed to apply profile: write /proc/self/attr/apparmor/exec: operation not permitted: unknown
```
Similar fix to https://github.com/canonical/microk8s/pull/1579/files
=> Run containerd unconfined in classic mode.

src/k8s/pkg/k8sd/api/cluster_bootstrap.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/api/cluster_tokens.go, src/k8s/pkg/k8sd/api/kubeconfig.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/utils/json.go, src/k8s/pkg/utils/json_test.go
The current `json.NewDecoder()` parses unknown fields and invalid json which might cause silent failures. With `DisallowUnknownFields` we now only allow valid json with known fields.
=> Use strict json decoder for API requests

src/k8s/pkg/client/dqlite/remove_test.go
Looks like something slipped in #289. As written, the test does not assert anything
=> Fixup unit test assertion

src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/provider.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/provider.go, src/k8s/pkg/k8sd/controllers/update_node_configuration.go, src/k8s/pkg/k8sd/controllers/update_node_configuration_test.go
- triggerCh is passed during creation, as a receive-only channel
- reconciledCh is internal and there is a receive-only accessor for downstream
Also make minor naming adjustments
=> Adjust trigger channels on the UpdateNodeConfigController

tests/integration/tests/test_etcd.py
Addresses flake https://github.com/canonical/k8s-snap/actions/runs/8848200925/job/24298083455#step:7:1473
=> Increase timeout for etcd and apiserver to come up during tests

src/k8s/cmd/k8s/k8s_set.go, src/k8s/cmd/k8s/k8s_set_test.go, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/utils/mapstructure.go
Use `mapstructure` to parse `k8s set` command arguments
- Allows parsing string slice inputs as `val1,val2` or YAML (or JSON) formatted strings
- Add unit tests for `k8s set` arguments
- If `mapstructure.NewDecoder` fails we panic, as all errors are programming bugs (see implementation of `NewDecoder`)
- We check for the list of known keys such that we present a meaningful user error, rather than a mapstructure error that the field is unknown.
=> Parse k8s set with mapstructure

src/k8s/pkg/client/kubernetes/status.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/cluster_util.go
The former implementation just waited for the nodes to become available. This led to some race-conditions where the api-server was not yet ready but the client already queried it.
See e.g. https://github.com/canonical/k8s-snap/actions/runs/8924131359/job/24511724390#step:7:374
=> Wait until kubernetes endpoint becomes available

.github/workflows/strict-integration.yaml, .github/workflows/strict.yaml
- Remove branch checkout during integration tests (we just apply the patch, we don't need to update any branches.
- Strict release branches are `release-1.xx-strict`, see failure in https://github.com/canonical/k8s-snap/actions/runs/8951306335/job/24587484219
=> Fix github actions to update strict branches

tests/integration/templates/bootstrap-all.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_dns.py, tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_metrics_server.py, tests/integration/tests/test_network.py, tests/integration/tests/test_smoke.py, tests/integration/tests/test_storage.py
Sets up an instance that enables all features and persists over the test session. All features (dns, gateway, ...) run against this instance to reduce setup/teardown time.
This reduces the integration test time by around ~18 min (58min -> 30min)
=> Reuse k8s instance across feature tests

snap/snapcraft.yaml
According to [snapcraft io docs](https://snapcraft.io/docs/architectures#core20-4) the `architectures` tag for `core20` snaps, this replacement is identical.  Launchpad builds however seem to be having difficulty seeing that this snap should be built for multiple architectures without this change
=> Adjustments so launchpad builders pick up arm64 requirement

src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/api/response.go
`InternalError` doesn't quite describe situations where a client needs to know if a node is already OUT of the cluster, or already IN the cluster. 
This creates unique 521 and 522 HTTP status codes for those events
=> Create new response API codes for specific Leave/Join failures

docs/tools/.readthedocs.yaml
Updating the RTD build script to auto-cancel creating docs for PRs with no doc changes
N.B., the webhook will still run, it will just finish quickly without building any docs and saving some server power.
=> Update RTD build conditions

.github/ISSUE_TEMPLATE/create_release_branch.md, .github/workflows/go.yaml, .github/workflows/integration.yaml, .github/workflows/python.yaml, .github/workflows/sbom.yaml, .github/workflows/strict-integration.yaml, .github/workflows/strict.yaml
Use `autoupdate/release-1.xx-strict` for strict release branches, to avoid having the auto promotion jobs failing due to branch protection rules
This also makes the strict branches fall in line with `autoupdate/strict`, to make it clear that these branches are not to be interacted with.
=> use `autoupdate/release-1.xx-strict` branches for strict

src/k8s/cmd/k8s/k8s_bootstrap.go
Backport #414 to the `release-1.30` branch
=> [Backport 1.30] enable local-storage by default (#414)

docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_join-cluster.md, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_bootstrap_test.go, src/k8s/cmd/k8s/k8s_join_cluster.go, tests/integration/templates/bootstrap-all.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_dns.py, tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_metrics_server.py, tests/integration/tests/test_network.py, tests/integration/tests/test_smoke.py, tests/integration/tests/test_storage.py
Backport #407 and #396 to release-1.30 branch
* read configs from stdin on '-'
* Reuse k8s instance across feature tests (#392)
=> [1.30] read configs from stdin on '-' (#407)

.github/workflows/go.yaml, .github/workflows/integration.yaml, .github/workflows/python.yaml, .github/workflows/sbom.yaml, .github/workflows/strict-integration.yaml, .github/workflows/update-components.yaml
Resolves the following issue https://github.com/canonical/k8s-snap/actions/runs/9125937201/job/25093148460#step:6:105
With this change, CI runs properly on PRs: https://github.com/canonical/k8s-snap/pull/432
=> Fix GitHub actions update components CI for release branches

src/k8s/pkg/k8sd/types/cluster_config_convert.go, src/k8s/pkg/k8sd/types/cluster_config_convert_test.go, tests/integration/tests/test_control_plane_taints.py, tests/integration/tests/test_util/util.py
Complete the register control-planes with taints task and test that taints are adequately applied on bootstrap
=> Copy control-plane taint from bootstrap config

docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_disable.md, docs/src/_parts/commands/k8s_enable.md, docs/src/_parts/commands/k8s_get-join-token.md, docs/src/_parts/commands/k8s_get.md, docs/src/_parts/commands/k8s_join-cluster.md, docs/src/_parts/commands/k8s_remove-node.md, docs/src/_parts/commands/k8s_set.md, docs/src/_parts/commands/k8s_status.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_generate_auth_token.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_set.go, src/k8s/cmd/k8s/k8s_status.go
Right now, the context deadline is initially set at root level when the command is created.This causes problems for interactive commands as the deadline may b
e exceeded while the user inputs the data.
To prevent this, we remove the global timeout and specifically set 
it in each command right before the RPC calls.
=> Explicitly set timeout in each CLI command

src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/database/schema.go, src/k8s/pkg/k8sd/database/sql/migrations/worker-tokens/000-create.sql, src/k8s/pkg/k8sd/database/sql/queries/cluster-configs/delete-worker-token.sql, src/k8s/pkg/k8sd/database/sql/queries/cluster-configs/insert-worker-token.sql, src/k8s/pkg/k8sd/database/sql/queries/cluster-configs/select-worker-token.sql, src/k8s/pkg/k8sd/database/sql/queries/worker-tokens/delete-by-token.sql, src/k8s/pkg/k8sd/database/sql/queries/worker-tokens/insert.sql, src/k8s/pkg/k8sd/database/sql/queries/worker-tokens/select.sql, src/k8s/pkg/k8sd/database/worker.go, src/k8s/pkg/k8sd/database/worker_test.go
Allow `k8s get-join-token` to return tokens without specifying a hostname (and match any name specified during `k8s join-cluster`)
- Add a separate `worker_tokens` database table
- `database.CheckWorkerNodeToken()` checks against the token itself, not the node name
- When a token has an empty node name, any joining name is accepted
=> Make `k8s get-join-token $hostname` optional

src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/setup/kube_apiserver_test.go, tests/integration/templates/nginx-dualstack.yaml
This PR contains the relevant changes to make dualstack (IPv4/IPv6) work on the k8s-snap. 
The current implementation for Kubernetes works out of the box as the only requirements from there is to set the proper `PodCIDR` and `ServiceCIDR` as `IPv4CIDR,IPv6CIDR`. A tiny unittest verifies that the kube-apiserver CIDR is properly set with both CIDRs.
For Cilium, IPv6 is disabled by default. Hence, we need to explicitly enable it if the IPv6 CIDR is set. 
Lastly, the `nginx-dualstack.yaml` was added to manually verify dualstack and will later be used in the integration tests.
=> Enable dualstack and add test files

docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_disable.md, docs/src/_parts/commands/k8s_enable.md, docs/src/_parts/commands/k8s_get-join-token.md, docs/src/_parts/commands/k8s_get.md, docs/src/_parts/commands/k8s_join-cluster.md, docs/src/_parts/commands/k8s_remove-node.md, docs/src/_parts/commands/k8s_set.md, docs/src/_parts/commands/k8s_status.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go, src/k8s/cmd/k8s/k8s_generate_auth_token.go, src/k8s/cmd/k8s/k8s_get.go, src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/cmd/k8s/k8s_set.go, src/k8s/cmd/k8s/k8s_status.go
=> [release-1.30] Explicitly set timeout in each CLI command (#443)

.github/workflows/go.yaml, .github/workflows/integration.yaml, .github/workflows/moonray.yaml, .github/workflows/python.yaml, .github/workflows/sbom.yaml, build-scripts/patches/moonray/0001-Moonray.patch, build-scripts/patches/moonray/apply
Add a Github workflow to automatically apply the moonray patches whenever the main branch changes. 
The current dummy patch is expected to be changed by follow-up PRs that contain e.g. Calico and Contour
=> Add autoupdate/moonray to GitHub workflows

docs/src/_parts/commands/k8s_bootstrap.md, docs/src/_parts/commands/k8s_join-cluster.md, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/pkg/utils/cidr.go, src/k8s/pkg/utils/cidr_test.go
Infer the address for the microcluster by specifying a CIDR in the address flag.
This allows us to have configuration in the ClusterAPI resources (where individual node IPs are not known yet) to choose the network interface that will be used by microcluster.
**Bootstrapping**
```
root@kcp-1:/k8s# k8s bootstrap --address 10.20.30.0/24
Bootstrapping the cluster. This may take a few seconds, please wait.
Bootstrapped a new Kubernetes cluster with node address "10.20.30.241:6400".
The node will be 'Ready' to host workloads after the CNI is deployed successfully.
root@kcp-1:/k8s# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
inet 127.0.0.1/8 scope host lo
valid_lft forever preferred_lft …
```
=> Add CIDR for microcluster Network Interface Configuration

build-scripts/patches/moonray/0001-Moonray.patch, src/k8s/pkg/k8sd/features/implementation_moonray.go
Add moonray implementation that (will) contain the features for moonray. This is ignored by default and only enabled by the moonray patch (which in turn also disables the `default_implementation`)
=> Add moonray implementation and go ignore tags

.github/workflows/update-branches.yaml
Follow up fix from #476, use the output from the `determine` step
=> Fixup update-branches workflow

src/k8s/cmd/k8s/k8s_x_wait_for.go, src/k8s/pkg/client/kubernetes/pods.go, src/k8s/pkg/client/kubernetes/pods_test.go, src/k8s/pkg/k8sd/features/calico/status.go, src/k8s/pkg/k8sd/features/cilium/status.go, src/k8s/pkg/k8sd/features/coredns/status.go, src/k8s/pkg/k8sd/features/status.go
* Refactor IsPodReady to `CheckForReadyPods` and add go-docs
* Add unittest for `CheckForReadyPods`
* Remove `ListPods`
* Refactor `CheckNetwork` and `CheckDNS` to only return error (nil->success)
=> Cleanup Status check code

src/k8s/pkg/k8sd/setup/kube_apiserver.go, src/k8s/pkg/k8sd/setup/kube_apiserver_test.go, src/k8s/pkg/k8sd/setup/kube_controller_manager.go, src/k8s/pkg/k8sd/setup/kube_controller_manager_test.go, src/k8s/pkg/k8sd/setup/kubelet.go, src/k8s/pkg/k8sd/setup/kubelet_test.go
This adds default arguments to kubelet, api server, controller manager services that improve our compliance with CIS guidelines. Also modifies our tests to reflect these changes.
=> add arguments to improve cis compliance and adjust tests accordingly

build-scripts/patches/moonray/apply, src/k8s/pkg/k8sd/features/status.go, tests/integration/tests/test_network.py
Make the network tests more generic. This will allow us to test on any implementation of the network feature.
- Removed Cilium bits from the Network integration tests
- Drive-by fixes for the `x-wait-for` error messages and improvements to the StatusInterface docs.
=> Improve Network Integration Tests

snap/hooks/install, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go
Workaround for services sometimes hanging during `k8s bootstrap`. From investigation, the hang happens before exec'ing the `kube-apiserver` binary (similar for other binaries).
```bash
Jun 14 07:56:40 $HOSTNAME systemd[1]: Started Service for snap application k8s.kube-apiserver.
Jun 14 07:56:40 $HOSTNAME k8s.kube-apiserver[497086]: + exec /snap/k8s/491/bin/kube-apiserver --allow-privileged=true --authentication-token-webhook-config-file=/var/snap/k8s/common/args/conf.d/auth-token-webhook.conf --authorization-mode=Node,RBAC --client-ca-file=/etc/kubernetes/pki/client-ca.crt --enable-admission-plugins=NodeRestriction --etcd-servers=unix:///var/snap/k8s/common/var/lib/k8s-dqlite/k8s-dqlite.sock --kubelet-certificate-authority=/etc/kubernetes/pki/ca.crt …
```
=> Ensure binaries do not hang during bootstrap

src/k8s/pkg/k8sd/setup/kube_proxy.go, src/k8s/pkg/k8sd/setup/kube_proxy_test.go, src/k8s/pkg/k8sd/setup/kubelet.go, src/k8s/pkg/k8sd/setup/kubelet_test.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go
When configuring kubelet and kube-proxy, only specify the `--hostname-override` flag if the node name does not match.
- Add a `snap.Snap.Hostname() string` method, which returns `os.Hostname()` or falls back to `"dev"`
- When configuring kubelet and kube-proxy, if the node name (coming from microcluster config) does not match the hostname (from snap.Hostname()`, only then configure `--hostname-override`
=> Do not set --hostname-override on kubelet and kube-proxy if hostname matches

snap/snapcraft.yaml, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_x_list_images.go, src/k8s/pkg/k8sd/features/calico/register.go, src/k8s/pkg/k8sd/features/cilium/register.go, src/k8s/pkg/k8sd/features/coredns/register.go, src/k8s/pkg/k8sd/features/localpv/register.go, src/k8s/pkg/k8sd/features/metrics-server/register.go, src/k8s/pkg/k8sd/images/images.go, src/k8s/pkg/k8sd/setup/containerd.go
Add a hidden command that can be used to retrieve the list of images a particular build of `k8s-snap` will use.
- Add `pkg/k8sd/images` package. This exports two functions: `Registrer` and `Images`
- Individual packages "register" their images by using a `func init() { images.Register(...) }`
- The list-images command simply retrieves the list using `images.Images()`.
- This way, individual implementations (e.g. calico or cilium) simply have an `init()` that registers the images. `init()` does not run for packages that are not imported by the code.
- We currently implicitly depend on more images than just the ones in our configs. Added TODOs to resolve them separately.
=> Add command to retrieve images used by k8s-snap

build-scripts/components/containerd/patches/default/0001-side-load-images-plugin.patch, src/k8s/tools/go.mod, src/k8s/tools/go.sum, src/k8s/tools/regctl.sh, src/k8s/tools/tools.go
Add a containerd plugin that sideloads images when containerd starts (and, optionally, at a refresh interval)
The plugin can be configured by a section like this in the `config.toml` file of containerd (or in a separate file):
```toml
[plugins."io.containerd.service.v1.sideload-images"]
disabled = true 
sources = ["path1", "path2"]
namespace = "k8s.io"
```
The default behaviour is to attempt to sideload any `tar` files found in `/var/snap/k8s/common/images` when containerd starts.
- Add patch for containerd plugin. This plugin is based on https://github.com/canonical/microk8s/blob/7a788d6d308672b0bde609e777727ded4255c134/build-scripts/components/containerd/patches/default/0001-microk8s-sideload-images-plugin.patch
- Also `regctl` under `tools`, such that we can easily run commands like …
=> Use a containerd plugin for side-loading images

src/k8s/pkg/k8sd/features/cilium/chart.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/register.go
Bump to Cilium 1.15.2-ck2 images, (adds support for arm64)
- Also does a drive-by fix to the cilium-operator image we report, as Cilium adds the `-generic` suffix for the pods.
=> use cilium 1.15.2-ck2 images

build-scripts/hack/upstream-images.yaml, src/k8s/pkg/k8sd/features/calico/chart.go, src/k8s/pkg/k8sd/features/calico/network.go, src/k8s/pkg/k8sd/features/calico/register.go
Sync Calico CNI images from upstream to the ghcr.io registry.
We have encountered that we hit the rate limits of DockerHub. This pull request mirrors the images we are using in Calico to ghcr.io, allowing the k8s snap to pull them from there instead of DockerHub.
```
Events:
Type     Reason     Age   From               Message
----     ------     ----  ----               -------
Normal   Scheduled  21s   default-scheduler  Successfully assigned calico-system/calico-node-ps4zh to kcp-1
Normal   Pulled     22s   kubelet            Container image "ghcr.io/canonical/k8s-snap/calico/pod2daemon-flexvol:v3.28.0" already present on machine
Normal   Created    22s   kubelet            Created container flexvol-driver
Normal   Started    22s   kubelet            Started container flexvol-driver …
```
=> Sync Calico CNI images from upstream

src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/utils/sys.go
Added to flags to `k8sd` in order to disable node and control-plane config controllers:
`--disable-node-config-controller`
`--disable-control-plane-config-controller`
`--disable-update-node-config-controller`
`--disable-feature-controller`
```shell
/snap/k8s/current/bin/k8sd --disable-node-config-controller --disable-control-plane-config-controller --disable-update-node-config-controller --disable-feature-controller
```
And you should see the logs stating that the config controllers were not initialized.
```text
2024/06/25 16:36:14 node-config-controller disabled via config
2024/06/25 16:36:14 control-plane-config-controller disabled via config
2024/06/25 16:36:14 update-node-config-controller disabled via config
2024/06/25 16:36:14 feature-controller disabled via config
```
=> Add disable-config-controller options to k8sd

src/k8s/pkg/utils/shims/shims.go, tests/integration/README.md, tests/integration/lxd/almalinux/lxd-profile.yaml, tests/integration/lxd/setup-image.sh, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/harness/lxd.py
Use a pre-built image and fetched OCI images for integration tests, with the aim to reduce e2e test running times and reduce the amount of fetched images.
=> Prepare LXD images for e2e tests to improve runtimes

src/k8s/api/v1/cluster.go, src/k8s/api/v1/cluster_node.go, src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_join_cluster.go, src/k8s/pkg/client/k8sd/cluster.go, src/k8s/pkg/k8sd/api/cluster_bootstrap.go, src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/utils/microcluster.go, src/k8s/pkg/utils/microcluster_test.go
This is a pre-requisite for fixing how k8sd cleans up when a bootstrap or join cluster operation fails.
Merge after #518 
Handle context cancellations during the bootstrap and join hooks. Without this change:
1. microcluster always applies a 30-second timeout if the context has no deadline set, effectively ignoring the timeout passed by the client
2. context deadline exceeded now cancels the bootstrap or join hook. Previously, this was using `s.Context` (from microcluster daemon), and therefore the hooks would keep running.
=> Microcluster timeouts during `k8s bootstrap` and `k8s join-cluster`

src/k8s/api/v1/cluster_node.go, src/k8s/cmd/k8s/k8s_remove_node.go, src/k8s/pkg/client/k8sd/cluster.go, src/k8s/pkg/client/kubernetes/node.go, src/k8s/pkg/client/kubernetes/node_test.go, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/provider.go, src/k8s/pkg/k8sd/setup/k8s_dqlite.go, src/k8s/pkg/snap/util/services.go
Merge after #520 
- Bootstrap control plane, bootstrap worker and join control plane hooks are refactored. We always defer a function that checks the result of the hook.
- In the case of preRemove, we simply log the error and proceed, otherwise the node is removed by microcluster peers but not the underlying dqlite database, breaking the cluster
- In the case of `k8s bootstrap`, remove all configs, stop control plane services, then use `ResetClusterMember`. This resets the microcluster state. Note that this runs automatically by k8sd, no manual action from the client is required.
- In the case of `k8s join-cluster` for worker nodes, similarly revert configs, then use `ResetClusterMember`
- In the case of `k8s join-cluster` for control plane nodes: When the `postJoin` hook runs, the node …
=> Cleanup on failed `k8s bootstrap` an `k8s join-cluster` attempts

docs/src/_parts/commands/k8s_disable.md, docs/src/_parts/commands/k8s_enable.md, src/k8s/cmd/k8s/k8s_disable.go, src/k8s/cmd/k8s/k8s_enable.go
Closes #523 
```bash
$ ./src/k8s/bin/static/k8s enable
Error: requires at least 1 arg(s), only received 0
Usage:
k8s enable [network|dns|gateway|ingress|local-storage|load-balancer] ... [flags]
Flags:
-h, --help                   help for enable
--output-format string   set the output format to one of plain, json or yaml (default "plain")
--timeout duration       the max time to wait for the command to execute (default 1m30s)
```
=> show features on `k8s enable/disable`

src/k8s/pkg/k8sd/features/calico/chart.go, src/k8s/pkg/k8sd/features/calico/cleanup.go, src/k8s/pkg/k8sd/features/calico/internal.go, src/k8s/pkg/k8sd/features/calico/internal_test.go, src/k8s/pkg/k8sd/features/calico/network.go
* Changed default encapsulation to VXLAN for both IPv4 and IPv6 pools
* Disabled Calico api server deployment by default
* Added annotations for node address auto detection
=> Switch default encapsulation to VXLAN, add annotations for autodetection

.github/workflows/integration-informing.yaml, .github/workflows/integration.yaml, .github/workflows/nightly-test.yaml
This PR updates our workflows to include the new 24.04 LTS OS and use 5.21 lxd LTS.
- explicitly use lxd 5.21 in nightly, informing-integration and integration
- add test on 24.04 to integration test
=> E2E test use lxd 5.21 & ubuntu 24.04 LTS

docs/src/.markdownlint.json
It was a typo in the config file :) @bschimke95 @louiseschmidtgen
=> Fix markdownlinter: _ not -

.github/workflows/fast-forward.yaml
Followup from #531 #534: GitHub actions do not fetch all of `origin` branches automatically: https://github.com/canonical/k8s-snap/actions/runs/9839344218/job/27161226404
=> Fixup how to checkout from origin

src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/update_node_configuration.go, src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/pki/control_plane_test.go, src/k8s/pkg/k8sd/pki/k8sdqlite.go, src/k8s/pkg/k8sd/pki/worker.go, src/k8s/pkg/k8sd/pki/worker_test.go, src/k8s/pkg/utils/pki/generate.go, src/k8s/pkg/utils/pki/generate_test.go, src/k8s/pkg/utils/pki/load.go
Move utility functions that deal with x509 certificates and public/private keys into a reusable `pkiutil` package
This is to reduce diff with incoming changes around implementing support for certificate refreshes.
=> Move pki utils to separate pkiutil package

.github/workflows/integration.yaml
We are at a point where integration tests fail more often because of flakes rather than an actual bug, therefore do not `fail-fast` when a flake occurs
=> do not fail-fast on integration tests

.github/workflows/cron-jobs.yaml
TICSQServer uploads the scan artifacts. We do not need to do anything more than that.
=> Do not upload Tiobe tarball

build-scripts/components/cni/build.sh, build-scripts/components/cni/patches/default/0001-single-entrypoint-for-cni-plugins.patch
When building cni plugins, we pull in `pkg/reexec` and vendor before running the build. This could result in an unpredictable source of external dependencies.
We avoid this by dropping the dependency and doing a simple switch-case, similar to https://github.com/canonical/k8s-snap/blob/a3d112ad4a74797e8b1bd6849442bb3069a039a9/src/k8s/cmd/main.go#L33-L41
=> drop unpinned `docker/pkg/reexec` dependency from cni plugins

tests/integration/requirements-test.txt
Tiobe uses pylint https://portal.tiobe.com/2020.3/docs/admin/admin_A18_analyzerpylint.html  . We would like to make it available in the tests path so some of our tests appear as expected (not gray in https://canonical.tiobe.com/tiobeweb/TICS/TqiDashboard.html#axes=ErrorSuppression(no),CodeType(Set(production,test)),Configuration(default),ProjectGroup(PublicRepos),Project(k8s-snap),Sub()&metric=tqiCodingStd&sort=T(1,worst))
=> Add pylint in the tests dependencies to have tiobe tests passing

docs/src/snap/howto/backup-restore.md, docs/src/snap/howto/index.md, docs/src/snap/tutorial/backing-up.md
Adds documentation to use velero and minio (though it could be some other s3 bucket endpoint) to facilitate cluster backups
* Based on the [Microk8s docs](https://microk8s.io/docs/velero) under the same banner, these docs offer a tutorial of how to install velero on minio in order to create backups.  
* adjusted those docs to upgrade the versions of velero and minio used in the examples.
=> Adding docs copied from microk8s and adjusted for k8s

src/k8s/cmd/k8s/k8s_set.go
other commands clamp timeout to minimum but this one did not
=> clamp timeout to minimum in k8s_set.go

tests/integration/tests/test_cilium_e2e.py
The cilium e2e test is known to be flaky on the Github Actions runners.
We know that Cilium works in the snap and this test causes more trouble then it is useful for now.
=> Disable cilium e2e on Github Actions

tests/integration/templates/bootstrap-control-plain-taints.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_control_plane_taints.py, tests/integration/tests/test_dualstack.py, tests/integration/tests/test_smoke.py, tests/integration/tests/test_util/util.py
Simplify integration tests by adding new pytest markers for `dualstack` and custom `bootstrap_config`s
We have a bunch of tests that require custom bootstrap configuration (e.g. dualstack). The current approach is to disable the automatic bootstrapping of the first `instance` and instead do this setup manually in each test. Those setup steps only differ in the path of the bootstrap config, so we can simply pass this to the marker.
Note that we still need the `disable_k8s_bootstrapping` marker for the `test_etcd` as this test requires the etcd cluster certs and needs to generate the bootstrap config dynamically.
=> Provide pytest marker to set custom bootstrap config

build-scripts/components/kubernetes/patches/v1.31.0/0001-allow-all-nodes-to-get-k8sd-config.patch, build-scripts/components/kubernetes/patches/v1.31.0/0001-single-kubernetes-binary.patch, build-scripts/components/kubernetes/patches/v1.31.0/0001-use-resolv.conf-file-with-non-loopback-nameservers.patch, build-scripts/components/kubernetes/patches/v1.31.0/0002-Allow-node-role-labels-on-kubelet-registration.patch
Adjust patches so that we can build k8s-snap for Kubernetes v1.31.0
=> Add support for Kubernetes v1.31.0

build-scripts/hack/update-component-versions.py
Document the `latest-1.xx.txt` version marker, which can be used to build Kubernetes release candidate versions.
=> Document how to update kubernetes version for release candidates

src/k8s/api/v1/types.go, src/k8s/cmd/k8s/k8s_status.go
Fix issues in `k8s status` formatting.
- properly format `load-balancer` and `local-storage` in `k8s status --output-format yaml`:
```
$ k8s status
localstorage:
enabled: true
message: enabled at /var/snap/k8s/common/rawfile-storage
version: 0.8.0-ck5
updatedat: 2024-08-07T11:30:54Z
```
- properly format node statuses in `k8s status --output-format yaml`:
```
$ k8s status
members:
- name: ip-172-31-34-101
address: 172.31.34.101:6400
clusterrole: control-plane
datastorerole: voter
```
- properly format feature status in `k8s status --output-format json`:
```
$ k8s status --output-format json
"dns": {
"Enabled": true,
"Message": "enabled at 10.152.183.153",
"Version": "1.11.1-ck4",
"UpdatedAt": "2024-08-07T11:30:54Z"
},
```
=> Consistent field names in k8s status outputs

docs/src/charm/howto/charm.md, docs/src/charm/howto/install-lxd.md
I've added some instructions for managing the LXD profile when deploying the charm 
I have covered the case for deploying to localhost
Currently as a draft because:
- I'm not sure of the best way of tackling the case e.g. of bundles. How can we edit the profiles on a machine which hasn't been created yet?
=> Add lxd charm howto

docs/src/capi/tutorial/getting-started.md
This PR adds a tab for the MAAS infrastructure in the CAPI tutorial.
=> Add MAAS infrastructure tab for CAPI tutorial

src/k8s/pkg/utils/certificate_test.go
Because it relies on a specific error message, the test can fail under arcane conditions. Instead, test that an error occured. Also, drive-by gomega idioms
=> refactor GetRemoteCertificate test

src/k8s/pkg/k8sd/controllers/csrsigning/validate_test.go
Test the encryption and common paths of the `validateCSR` function.
=> Add unittest for CSR validation

src/k8s/go.mod, src/k8s/go.sum
Switch to microcluster v2 fork without join name verification to unblock CAPI work while we work towards a proper solution.
=> Switch to microcluster fork without join name verification

src/k8s/pkg/k8sd/features/cilium/gateway.go
Previously, Gateway API CRDs were installed and removed at the start of enabling or disabling the Gateway feature.
This approach caused issues when the Gateway feature was disabled, as the CRDs were removed too early, leading to failures in Cilium's cleanup process due to the absence of these CRDs.
This commit ensures that Gateway API CRDs are only removed after Cilium has been updated, preventing cleanup failures.
=> Delay Gateway API CRD Removal Until After Cilium Update

src/k8s/go.mod, src/k8s/pkg/client/k8s/mock/mock.go, src/k8s/pkg/k8sd/controllers/csrsigning/controller.go, src/k8s/pkg/k8sd/controllers/csrsigning/reconcile.go, src/k8s/pkg/k8sd/controllers/csrsigning/reconcile_approve.go, src/k8s/pkg/k8sd/controllers/csrsigning/reconcile_approve_test.go, src/k8s/pkg/k8sd/controllers/csrsigning/reconcile_test.go, src/k8s/pkg/k8sd/controllers/csrsigning/setup.go, src/k8s/pkg/k8sd/controllers/csrsigning/test/k8s_mock.go
I was inspired by the [upstream kubernetes](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/volumemanager/reconciler/reconciler_test.go).
=> Add unit tests for csrsigning controller

src/k8s/go.mod, src/k8s/pkg/k8sd/api/cluster_tokens.go, src/k8s/pkg/k8sd/database/schema.go, src/k8s/pkg/k8sd/database/sql/migrations/worker-tokens/001-add-expiry.sql, src/k8s/pkg/k8sd/database/sql/queries/worker-tokens/insert.sql, src/k8s/pkg/k8sd/database/sql/queries/worker-tokens/select.sql, src/k8s/pkg/k8sd/database/worker.go, src/k8s/pkg/k8sd/database/worker_test.go
Add an optional TTL for worker tokens similar to https://github.com/canonical/k8s-snap/pull/620
This PR requires the (backward-compatible) update in the k8s-snap-api.
https://github.com/canonical/k8s-snap-api/pull/5
Once this PR is reviewed and approved, I will merge the API change, create a new tag (1.0.3) and update this k8s-snap PR to use the new API version.
=> Add worker token TTL

src/k8s/pkg/client/kubernetes/status.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_start.go
`onStart` hook happens before `onBootstrap`. because of this, on non-fresh machines (non-fresh == `/etc/kubernetes/admin.conf` is available) we use invalid/old `admin.conf` kubeconfig for csrsigining controller client. this PR makes sure that we prevent running controllers until we have the correct `.conf` files and we can reach the k8s cluster.
build and install k8s on a fresh machine, run `bootstrap` and check logs and confirm the csrsigning controller is running, e.g.:
```text
Aug 21 08:28:20 test k8s.k8sd[1642]: I0821 08:28:20.897429    1642 controller/controller.go:181] "Starting Controller" logger="k8sd.csrsigning" controller="certificatesignin
grequest" controllerGroup="certificates.k8s.io" controllerKind="CertificateSigningRequest"
Aug 21 08:28:21 test k8s.k8sd[1642]: I0821 …
```
=> Add k8s endpoint check to markNodeReady

docs/src/_parts/commands/k8s.md, docs/src/_parts/commands/k8s_refresh-certs.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_refresh_certs.go, src/k8s/pkg/client/k8sd/interface.go, src/k8s/pkg/client/k8sd/manage.go, src/k8s/pkg/client/k8sd/mock/mock.go, src/k8s/pkg/k8sd/api/certificates_refresh.go
Add a `refresh-certs` command to refresh certificates for both control plane and worker nodes.
In Proposal 002, we outlined the process for refreshing certificates via the `k8s` command line interface. This allows the snap to refresh certificates for both control plane and worker nodes in the cluster.
```
root@t-1:~# k8s refresh-certs --ttl 10mo --extra-sans=10.0.10.10 foo.local
Certificates have been successfully refreshed, and will expire at 26265600.
root@t-1:~# openssl x509 -in /etc/kubernetes/pki/kubelet.crt -noout -text
Certificate:
Data:
Version: 3 (0x2)
Serial Number:
12:c4:76:9f:58:42:e7:a2:e1:2f:b3:fb:6e:85:48:01
Signature Algorithm: sha256WithRSAEncryption
Issuer: CN = kubernetes-ca
Validity
Not Before: Aug 23 20:40:39 2024 GMT
Not After : Jun 23 20:40:39 2025 GMT
Subject: O = …
```
=> Add `refresh-certs` Command

src/k8s/cmd/k8s/k8s_get_join_token.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_preinit.go, src/k8s/pkg/k8sd/app/hooks_remove.go, tests/integration/tests/test_clustering.py, tests/integration/tests/test_util/util.py
Microcluster validates that the certificate SANs do match with the name that was created when creating the join token. 
This breaks the CAPI workflow as in that, the noden/hostname is unknown at the time the token is created. 
We can work around this issue by providing extraSANs to the microcluster certificate on init which is done in this PR.
See https://docs.google.com/document/d/1ZcEDgLwy_BroyJr_oqTOyqBsK0mvBt7EB6UCrCxC1mg/edit#heading=h.kavgppauvkj5 for more context.
=> Add extra SANs to microcluster certificate

.github/workflows/go.yaml, src/k8s/pkg/k8sd/setup/directories.go
When the Cilium feature is enabled, add simple user/group/permissions checks on the configured CNIBinDir (/opt/cni/bin) before installing the Cilium Helm chart.
Fixes: https://github.com/canonical/k8s-snap/issues/567
=> Add checks for CNIBinDir ownership/permissions.

build-scripts/hack/sync-images.yaml, docs/src/snap/howto/install/offline.md, src/k8s/pkg/k8sd/features/localpv/chart.go, src/k8s/pkg/k8sd/features/metrics-server/chart.go
* bumps metrics-server from 0.7.0-ck0  -> 0.7.0-ck1
* bumps rawfile-localpv from 0.8.0-ck5  -> 0.8.0-ck4
Though it looks odd, i did confirm the rawfile-localpv had its "ck*" revision drop to a smaller number, it is in fact the correct image.  We need to look at the workflow to understand how it managed to generate a lower number than the previous ck5 release.
=> Multiarch image support for local storage and metrics-server

snap/hooks/install, src/k8s/cmd/k8s/k8s_x_snapd_config.go
We have machinery in place to sync the k8sd configuration with snapd config. This is reconciled via `k8s x-snapd-config config`. The reconciliation is triggered on every config change and in the snap `configure` hook. 
This causes issues on refresh because `k8sd` may not be up yet after restart and cause:
```
buntu@juju-32b103-6:~$ sudo snap refresh k8s
2024-08-28T14:51:52Z INFO Waiting for "snap.k8s.kube-apiserver.service" to stop.
error: cannot perform the following tasks:
- Run configure hook of "k8s" snap if present (run hook "configure": Error: failed to update k8sd state: failed to update k8s configuration: failed to PUT /k8sd/cluster/config: Database is not yet initialized)
```
This PR fixes this issue by making sure that `k8sd` is up before performing the reconciliation. 
``` …
```
=> k8sd snapd config sync: Wait for k8sd to come up

k8s/lib.sh
Some Kubernetes volumes may not be easily removed (e.g.: NFS volumes from a local NFS provider), leading to a significantly increased snap removal time and leaked volume mounts.
Due to the volume leak, the ``/var/lib/kubelet`` folder is never cleaned up properly either, which means that on reinstalling the k8s snap afterwards and bootstrapping the cluster, the current node will not be registered to the cluster.
This adds the ``-f`` option to ``umount``, forcing the unmount.
Fixes: https://github.com/canonical/k8s-snap/issues/612
=> Forces volume umount when snap is removed

src/k8s/pkg/k8sd/api/cluster_remove.go
Node removal process in CAPI might fail, we figured that the context passed to`DeleteClusterMember` is somehow getting canceled but couldn't figure out why or by which component. The cancellation happens after the `RunPreRemoveHook` call and before the `DeleteCoreClusterMember` call in `clusterMemberDelete` endpoint of microcluster. This is a workaround to avoid the cancellation. keep in mind that this failure is flaky and might not happen in every run.
=> Pass independent context to DeleteClusterMember

docs/src/snap/reference/certificates.md, docs/src/snap/reference/index.md, src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/pki/k8sdqlite.go
Adds an overview of all certificates used by Canonical K8s
https://canonical-ubuntu-documentation-library--632.com.readthedocs.build/canonical-kubernetes/632/snap/reference/certificates/
=> Certificate reference page

docs/src/snap/howto/index.md, docs/src/snap/howto/restore-quorum.md, src/k8s/cmd/k8sd/k8sd.go, src/k8s/cmd/k8sd/k8sd_cluster_recover.go, src/k8s/hack/static-go-build.sh, src/k8s/pkg/utils/file.go, src/k8s/pkg/utils/yaml.go
We're adding a command that can be used to recover Canonical K8s clusters after dqlite quorum loss.
The command will:
* assist the user in making the necessary k8s-dqlite and k8sd configuration changes
* create pre-recovery and post-recovery backups that can be applied to other nodes
* issue a dqlite reconfigure request, updating the raft members
* attempt to contact the other dqlite members in order to ensure that all cluster members are offline before attempting to perform the recovery steps
Based on the microcloud command, which leverages the microcluster implementation:
* https://github.com/canonical/microcloud/blob/main/cmd/microcloud/cluster_members.go
* https://github.com/canonical/microcluster/blob/42551841a56dd2d4697d577428bdb4d7d5f877d0/internal/recover/recover.go#L72
For …
=> Add command for k8sd recovery after quorum loss

src/k8s/pkg/k8sd/features/calico/chart.go, src/k8s/pkg/k8sd/features/calico/network.go, src/k8s/pkg/k8sd/features/calico/network_test.go, src/k8s/pkg/k8sd/features/calico/register.go, src/k8s/pkg/k8sd/features/cilium/network_test.go
- Add unit test for calico k8sd network feature
- Remove `t.Helper()` from cilium network tests as well since I noticed this way finding the root cause of the failed tests becomes easier.
=> Add unit tests for Calico network k8sd feature

src/k8s/pkg/k8sd/features/cilium/chart.go, src/k8s/pkg/k8sd/features/cilium/loadbalancer.go, src/k8s/pkg/k8sd/features/cilium/loadbalancer_test.go, src/k8s/pkg/k8sd/features/cilium/network_test.go
- Add unit tests for `Cilium load-balancer` k8sd feature
- Rename some `Cilium network` tests and functions to prevent conflict
=> Add unit tests for cilium load balancer

docs/moonray/howto/index.md, docs/moonray/howto/networking/default-ingress-mr.md, docs/moonray/howto/networking/index.md, docs/src/snap/howto/index.md, docs/src/snap/howto/networking/default-ingress.md, docs/src/snap/howto/networking/index.md
This PR adds some additional context around contour's default tls secret configuration, as it is slightly different from cilium's.
Moonray: https://canonical-moonray--656.com.readthedocs.build/656/
=> Ingress default tls secret extra moonray comment

.github/workflows/integration.yaml, tests/branch_management/.copyright.tmpl, tests/branch_management/requirements-dev.txt, tests/branch_management/requirements-test.txt, tests/branch_management/tests/conftest.py, tests/branch_management/tests/test_branches.py, tests/branch_management/tox.ini
Each pull request should ensure that the changes address that prior gh release branches exist and that lp recipes for this release exists
* each PR will run `Test Branch Management`
* test that the previous release branches exist for all flavours
* test that all tip branches exist and are mapped to an lp recipe for that branch
* this will protect us from accidentally upgrading `main` to a new 1.xx version before creating release branches for 1.(xx-1)
* this will protect us from accidentally upgrading `main` without creating launchpad recipes
* This doesn't yet protect us from not having created snap tracks... this will be included in a follow up
=> Introduce tests to ensure branches and lp-recipes exist

.github/workflows/update-components.yaml
Include the release-1.31 branch in auto-update components job as a part of https://github.com/canonical/k8s-snap/issues/666
Merge after:
* https://github.com/canonical/k8s-snap/pull/667
=> Auto-update components in release-1.31 branch

.github/workflows/nightly-test.yaml
Nightly edge CI workflow is failing due to lxd 5.19/stable not being available.  Update to lxd 5.21/stable.
KU-1576: fixes #669.
=> use lxd 5.21/stable snap

docs/src/snap/howto/restore-quorum.md, src/k8s/cmd/k8sd/k8sd_cluster_recover.go
At the moment, the "k8sd cluster-recover" displays interactive prompts and text editors that assist the user in updating the dqlite configuration.
We need to be able to run the command non-interactively in order to automate the cluster recovery procedure.
This change adds a "--non-interactive" flag. If set, we'll no longer show confirmation prompts and we'll assume that the configuration files have already been updated, proceeding with the dqlite recovery.
=> k8sd cluster-recover: add non-interactive mode

.github/ISSUE_TEMPLATE/create_release_branch.md
Based on #666 , improved the process to create release branches
=> Update the issue template for creating release branches

.github/workflows/integration-informing.yaml, src/k8s/pkg/client/kubernetes/endpoints.go, src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/pki/k8sdqlite.go, src/k8s/pkg/k8sd/pki/worker.go, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/k8sd/setup/k8s_apiserver_proxy.go, src/k8s/pkg/k8sd/setup/k8s_apiserver_proxy_test.go, src/k8s/pkg/k8sd/setup/kube_apiserver.go, src/k8s/pkg/k8sd/setup/kube_proxy.go, src/k8s/pkg/k8sd/setup/kube_proxy_test.go, src/k8s/pkg/k8sd/setup/kubelet.go, src/k8s/pkg/k8sd/setup/util_kubeconfig.go, src/k8s/pkg/proxy/userspace.go, src/k8s/pkg/utils/cidr.go, src/k8s/pkg/utils/cidr_test.go, tests/integration/templates/bootstrap-ipv6-only.yaml, tests/integration/templates/etcd/etcd-tls.conf, tests/integration/templates/nginx-ipv6-only.yaml, tests/integration/tests/test_networking.py, tests/integration/tests/test_util/util.py
Adds support for IPv6-only support on moonray. For the default k8s-snap this is not yet supported as Cilium loadbalancer does not support IPv6-only.
Most of the changes basically only ensure that the IPv6 address is properly put into brackets. We use different representations of IPs across the codebase (e.g. string, or net.IP or Addr by microcluster) so we cannot just simply use the same approach everywhere.
=> Add IPv6-only support for moonray

src/k8s/pkg/k8sd/database/schema.go
Migrations should be applied in the correct order with the latest migration being applied last.
Microcluster counts the migrations we have done. 
Changing the order can lead to mistakes: 
We previously apply schemaApplyMigration("feature-status", "000-feature-status.sql") at schema count 5, then we add in schemaApplyMigration("worker-tokens", "001-add-expiry.sql") at schema count 5, leading us to re-apply feature-status in count 6 when migrating the schema.
For instance, this issue occurred migrating moonray: https://github.com/canonical/k8s-snap/blob/archive/release-1.30-moonray/src/k8s/pkg/k8sd/database/schema.go
=> Correct microcluster schema migration order

.github/workflows/integration.yaml, tests/branch_management/tests/conftest.py, tests/branch_management/tests/test_branches.py, tests/branch_management/tox.ini
* Confirm that branches are available both in launchpad and github for the stable_release, the previous_stable and the current_release
* Raises awareness that stable releases needs a release branch
* Represents a clean-up/adjustment due to the track map policy changes
* Verifies that upstream stable, upstream previous stable, and this current version all have a stable release branch in Github and Launchpad
* Verify the tip recipes always exist (regardless of stable version)
* GH action must checkout with `depth:0` so it can "see" all the remote branches
=> Create more tests on branches and recipes

docs/src/snap/reference/annotations.md, src/k8s/cmd/k8s/k8s_bootstrap_test.go, src/k8s/cmd/k8s/testdata/bootstrap-config-full.yaml, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/k8sd/api/worker.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_remove.go, tests/integration/templates/bootstrap-skip-service-stop.yaml, tests/integration/tests/test_clustering.py
Requires https://github.com/canonical/k8s-snap-api/pull/8 - will update api version tag for the snap afterwards.
By default, all services on a leaving node are stopped. This PR adds logic to skip this step if the `k8sd/v1alpha/lifecycle/skip-stop-services-on-remove` annotation is set. 
This is required for Cluster API to properly drain nodes. See
Also adds an integration test to validate that this works as expected.
=> Do not stop Kubernetes services on node removal if annotation is set.

.github/workflows/go.yaml, .github/workflows/integration-informing.yaml, .github/workflows/integration.yaml, .github/workflows/python.yaml, .github/workflows/sbom.yaml
Currently, when docs are changed PR triggers all builds including code test which is unnecessary. This PR adds additional logic to workflows to skip builds when changes are only in the docs directory.
KU-1154
=> Skip Go/K8s test suite when docs are changed

src/k8s/cmd/k8s/k8s_x_snapd_config.go
Follow-up fix for: https://github.com/canonical/k8s-snap/pull/633
In the mentioned PR, we wait until k8sd is up to sync the config. We exit early if the node is not part of a cluster. However, a closer look at the implementation of `NodeStatus` shows that this would skip any error that we wait for:
```
func (c *k8sd) NodeStatus(ctx context.Context) (apiv1.NodeStatusResponse, bool, error) {
response, err := query(ctx, c, "GET", apiv1.NodeStatusRPC, nil, &apiv1.NodeStatusResponse{})
if err != nil {
// Error 503 means the node is not initialized yet
var statusErr api.StatusError
if errors.As(err, &statusErr) {
if statusErr.Status() == http.StatusServiceUnavailable {
return apiv1.NodeStatusResponse{}, false, nil
}
}
return apiv1.NodeStatusResponse{}, false, err <- Returns partOfCluster == …
```
=> x-snap-config: Do not check if node is part of the cluster

src/k8s/cmd/k8sd/k8sd.go, src/k8s/cmd/k8sd/k8sd_cluster_recover.go, src/k8s/cmd/main.go
At the moment, k8s and k8sd return 0 even if the command fails, which is a problem especially when used inside scripts.
We'll ensure that a non-zero exit code is returned if the commands fail.
=> Return non-zero exit code in case of errors

src/k8s/pkg/k8sd/features/metallb/loadbalancer.go
using `map[string]struct{}` instead of `map[string]bool` for a __very minimal__ performance gain.
=> Use map of struct instead of bool

src/k8s/pkg/k8sd/database/schema.go, src/k8s/pkg/k8sd/database/sql/migrations/worker-nodes/000-create.sql, src/k8s/pkg/k8sd/database/sql/migrations/worker-nodes/001-delete.sql
This PR backports the correction of our Microcluster migrations into 1.31.
Two PRs are backported: #689 #676. One corrects the order and the other properly drops a table instead of removing the migration.
=> [Backport release-1.31] Microcluster Migration History Restoration

src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/k8sd/features/calico/network.go, src/k8s/pkg/k8sd/features/calico/network_test.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/network_test.go, src/k8s/pkg/k8sd/features/interface.go, src/k8s/pkg/k8sd/setup/k8s_apiserver_proxy.go, src/k8s/pkg/k8sd/setup/k8s_apiserver_proxy_test.go, src/k8s/pkg/k8sd/setup/kube_apiserver.go, src/k8s/pkg/k8sd/setup/kube_apiserver_test.go, src/k8s/pkg/k8sd/types/cluster_config_merge.go, src/k8s/pkg/k8sd/types/cluster_config_network.go
Configure cilium to use the local port of apiserver or apiserver-proxy to communicate with the apiserver instead of the kube-proxy service which should address issues with `socketLB`
=> Point cilium to talk to the local apiserver or apiserver-proxy

src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/api/endpoints.go, tests/integration/tests/test_smoke.py
Add new CAPI endpoints to manage certificates refreshes
In this pull request, we have added a new set of handlers that allow access from CAPI to the refresh certificates endpoints using the node token as the authentication mechanism. Additionally, we have modified the handler to return the certificate refresh response earlier, deferring the restart until after the response has been flushed. Also, added a couple of drive-by fixes related to the RPC endpoints for Certificates Refreshes.
=> Add CAPI endpoints for Certificates Refresh

src/k8s/hack/env.sh
We have seen some issues recently while cloning the `libtirpc` repo from debian. This pull request points the build scripts to our Launchpad mirror.
=> Mirror `libtirpc` to Launchpad

src/k8s/pkg/k8sd/features/contour/chart.go, src/k8s/pkg/k8sd/features/contour/gateway.go, src/k8s/pkg/k8sd/features/contour/gateway_test.go, src/k8s/pkg/k8sd/features/contour/ingress.go, src/k8s/pkg/k8sd/features/contour/ingress_test.go, src/k8s/pkg/k8sd/features/contour/register.go
The unit tests for the contour feature are lacking this pr proves test coverage from 0% files, 0% statements to 100% files, 84.3% statements for github.com/canonical/k8s/pkg/k8sd/features/contour package.
=> Unit tests for contour k8sd feature

src/k8s/pkg/k8sd/features/cilium/gateway.go, src/k8s/pkg/k8sd/features/cilium/gateway_test.go, src/k8s/pkg/k8sd/features/cilium/ingress.go, src/k8s/pkg/k8sd/features/cilium/ingress_test.go, src/k8s/pkg/k8sd/features/cilium/loadbalancer.go, src/k8s/pkg/k8sd/features/cilium/loadbalancer_test.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/network_test.go, src/k8s/pkg/k8sd/features/cilium/status_test.go
There are lacks in unittest for cilium feature in k8sd  this pr proves test coverage form 42.9% files, 44.4% statements to  85.7% files, 86.7% statements for github.com/canonical/k8s/pkg/k8sd/features/cilium package
=> Unittests for cilium k8sd feature

.github/workflows/nightly-test.yaml, build-scripts/hack/sync-images.yaml, docs/src/snap/howto/install/offline.md, src/k8s/pkg/k8sd/features/metrics-server/chart.go, tests/integration/templates/etcd/etcd.service, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/etcd.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_version_upgrades.py, tests/integration/tox.ini
Resolves a number of tests issues the nightly tests were having to run effectively on arm64 and amd64 units. 
* Changes to the github workflow definition 
* Use system-wide tox installed through apt for arm64 workers to use
* Correctly upload the right TEST_SNAP after its downloaded
* Include inspection reports in failures
* Add tmate session for remote debugging
* Add support for arm64 in the etcd tests (correct release url, correct systemd file)
* Address pytest syntax issue for use of `pytest.mark.xfail`
* Adjust the testing `tox.ini` to be tox 3 and 4 compatible
=> Improve Nightly Test runs to pass

docs/src/capi/reference/annotations.md
This PR adds the `v1beta2.k8sd.io/refresh-certificates` to the CAPI annotations reference page.
=> Add refresh-certificates annotation to capi references

.github/workflows/integration-informing.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_clustering.py, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
* creates a new test which clusters two control-plane nodes from different versions of the same flavor
* improves the function scoped pytest marking to support `node_count` or `node_config` when you wish to configure the  nodes differently (say with a different snap version)
* Run informing tests with a new flag `TEST_FLAVOR` to help identify which flavor is being tested
* add a new pytest marker
* improves the `test_version_upgrades` test to not need to be skipped
* **new & improved** utils methods:
* `setup_k8s_snap` now with super powers to snap install a file, from a channel, from a track, and from a revision
* `tracks_least_risk` method to find the least risk revision in a specific track or channel
* `previous_track` method to find the snap track prior to a given one.
=> Create a test scenario for mixed version clustering

k8s/lib.sh
At the moment, the kubelet plugins in ``/var/lib/kubelet/plugins/`` are not removed, even though the Pods associated with those plugins have been removed.
This means that on reinstallation, kubelet will try to access those inexistent plugins through the ``*.sock`` files, including for plugins we don't want anymore, and delaying registration for the ones we do want.
Sample logs:
```
Oct 10 12:57:13 ubuntu k8s.kubelet[47511]: W1010 12:57:13.690383   47511 logging.go:55] [core] [Channel #75 SubChannel #77]grpc: addrConn.createTransport failed to connect to {Addr: "/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock", ServerName: "%2Fvar%2Flib%2Fkubelet%2Fplugins_registry%2Fdriver.longhorn.io-reg.sock", }. Err: connection error: desc = "transport: Error while dialing: dial unix …
```
=> Removes lingering kubelet plugins on snap removal

k8s/lib.sh
At the moment, we're unmounting the mounted Pod volumes (``/var/lib/kubelet/pods``) from the system when we remove the snap. However, there may still be volume mounts from certain CSI drivers like Longhorn still mounted (``/var/lib/kubelet/plugins``).
This commit addresses this issue.
Example leaked mounts from Longhorn:
```
cat /proc/mounts | grep /var/lib/kubelet
/dev/longhorn/pvc-14f3eced-66bb-4adc-9c12-d7edcbe80bc0 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b337ad411e8b121b6c392afc3578ff72103fdefddae0524b9b8459b1706259a1/globalmount ext4 rw,relatime 0 0
10.152.183.200:/pvc-8a8d1b75-aada-4360-ac44-315751149fe7 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/183ab2cffd14d3869ddd02e1d7b9fb3307b69a3bd3f8fef6f9224e1636496c15/globalmount nfs4 …
```
=> Removes lingering CSI plugin volume mounts on snap removal

.golangci.yml, src/k8s/pkg/client/snapd/refresh_status.go, src/k8s/pkg/utils/certificate.go
The other enabled linters did not yield any error in the existing codebase
=> Enable bodyclose linter

.golangci.yml, src/k8s/pkg/k8sd/features/contour/chart.go
Remove cyclop - we have intentional long code at some places 
Remove depguard - we don't want to deny any package 
Remove dupl - we have duplicate code by intention in some places.
=> Enable duplicate word check

.github/workflows/cron-jobs.yaml, .github/workflows/integration.yaml
`make go.unit` has to be run with elevated privileges since we now change the owner of /opt/cni/bin to root. See https://github.com/canonical/k8s-snap/blob/a2c00fb6be9951f582e139d83d97ad1dceb4ec13/src/k8s/pkg/k8sd/setup/directories.go#L72 
This operation fails if `make go.unit` is run as a regular user.
=> Fix TiCS action's permission error

docs/src/charm/howto/custom-registry.md, docs/src/charm/howto/index.md
Add a new How-To page to guide users on configuring custom registries for the `k8s` charm.
Custom registry on AWS.
```
Name:             nginx
Namespace:        default
Priority:         0
Service Account:  default
Node:             ip-172-31-17-168.ec2.internal/172.31.17.168
Start Time:       Wed, 16 Oct 2024 22:46:08 +0000
Labels:           run=nginx
Annotations:      <none>
Status:           Running
IP:               10.1.0.115
IPs:
IP:  10.1.0.115
Containers:
nginx:
Container ID:   containerd://f729364d3dc2636626b6c971ea1cbe95cb9d6febb39356c132959a862ca8707e
Image:          52.205.98.73:5043/nginx:latest
Image ID:       52.205.98.73:5043/nginx@sha256:719b34dba7bd01c795f94b3a6f3a5f1fe7d53bf09e79e355168a17d2e2949cef
Port:           <none>
Host Port:      <none>
State:          Running …
```
=> Add Configure Custom Registries How-To

src/k8s/pkg/k8sd/features/images.go
None of the 1.30 track snaps operate because the images within those channels don't function on arm64. 
* Update the images to versions built for arm64 and amd64
=> [Release 1.30] Update to arm64 versions of the same images

src/k8s/cmd/k8s/k8s_bootstrap_test.go, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/features/calico/internal.go, src/k8s/pkg/k8sd/features/calico/internal_test.go, src/k8s/pkg/k8sd/features/cilium/internal.go, src/k8s/pkg/k8sd/features/cilium/internal_test.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/network_test.go, src/k8s/pkg/k8sd/features/metrics-server/internal.go
Fixes #702
Cilium [excludes](https://github.com/cilium/cilium/pull/17560) `bridge` devices while performing auto detection and suggests providing the selection filtermanually through the `devices` flag if auto detection is not suitable.
This PR adds the `k8sd/v1alpha1/cilium/devices` and `k8sd/v1alpha1/cilium/direct-routing-device` annotations to let users configure which devices(interfaces) can be used by cilium. 
Initially we aimed to override this auto detection and select the device based on the node internal ip however the device names could be different on multiple machines which breaks this assumption. As an alternative we could set the `devices` field with a certain default value with wildcard filters to cover common interface names, e.g. `eth+ lxdbr+ enp+`.
=> Add annotations for configuring which devices cilium use for routing

tests/integration/tests/test_networking.py, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/util.py
* GH runners may be quick, but others may be slower
* how long to wait for k8s_ready can differ on these cloud substrates, the tests should be adjustable
* using OS env vars to set the RETRIES and DELAY_S for various clouds
* `wait_until_k8s_ready` will default to be `150s`, but can be extended to wait longer or shorter
=> Allow tests to override how long wait for slower clouds providers to pull images

tests/integration/tests/test_util/config.py
these should be treated like integers not strings
```
____________________________ test_version_upgrades _____________________________
Traceback (most recent call last):
File "/tmp/tmpzr1bsedy/tests/integration/tests/test_version_upgrades.py", line 40, in test_version_upgrades
util.wait_until_k8s_ready(cp, instances)
File "/tmp/tmpzr1bsedy/tests/integration/tests/test_util/util.py", line 207, in wait_until_k8s_ready
.exec(["k8s", "kubectl", "get", "node", node_name, "--no-headers"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/actions-runner/_work/canonical-kubernetes-release-ci/canonical-kubernetes-release-ci/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py", line 289, in wrapped_f
return self(f, *args, **kw)
^^^^^^^^^^^^^^^^^^^^ …
```
=> retries and delay_s values should be ints

.github/workflows/integration.yaml
Resolve a conflict trying to run trivy manually and using the trivy-action
The `trivy-action` clones itself into a directory called `trivy` overwriting the binary just downloaded in that same spot. 
By moving the downloaded file to another directory, they don't' conflict
=> Fix conflict using manual trivy and the trivy action

.github/workflows/cron-jobs.yaml
Similar to https://github.com/canonical/k8s-snap/pull/752
just for nightly runs
=> Remove stray TRIVY_* env vars for a manual run of trivy

.golangci.yml, src/k8s/cmd/util/hooks.go, src/k8s/pkg/docgen/json_struct.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/features/cilium/chart.go, src/k8s/pkg/k8sd/features/cilium/ingress_test.go, src/k8s/pkg/k8sd/features/cilium/loadbalancer.go, src/k8s/pkg/k8sd/features/metallb/loadbalancer.go, src/k8s/pkg/k8sd/features/metrics-server/metrics_server_test.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/utils/cidr.go, src/k8s/pkg/utils/pki/load.go
`gochecknoglobals` and `goconst` require some refactoring. Let's consider them later.
=> Enable gocritic linter

.golangci.yml, src/k8s/pkg/client/dqlite/util_test.go, src/k8s/pkg/client/helm/mock/mock.go, src/k8s/pkg/client/kubernetes/server_groups.go, src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/api/response.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/provider.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go, src/k8s/pkg/k8sd/controllers/csrsigning/const.go, src/k8s/pkg/k8sd/database/util_test.go, src/k8s/pkg/k8sd/features/cilium/internal.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/contour/gateway.go, src/k8s/pkg/k8sd/features/contour/ingress.go, src/k8s/pkg/k8sd/types/cluster_config_certificates.go, src/k8s/pkg/k8sd/types/cluster_config_datastore.go, src/k8s/pkg/utils/certificate.go, src/k8s/pkg/utils/time.go
Finally fixing the important issues!
Removed the `gocylic` linter as it is similar as the `cyclop` one.
=> Enable godot

src/k8s/pkg/k8sd/features/localpv/chart.go, src/k8s/pkg/k8sd/features/metrics-server/chart.go
Use multiarch versions of these images so that one can bootstrap from 1.30-moonray track
=> [Release 1.30-moonray] Update to arm64 versions of the same images

docs/src/snap/howto/networking/index.md, docs/src/snap/howto/networking/ipv6.md
This is quite similar to the dualstack documentation setup.
=> Add docs page for IPv6-only

tests/integration/tests/test_util/harness/lxd.py
Sometimes the removing an LXD container is stuck forever. Adding a timeout prevents the CI from hanging indefinitely in this case.
It is very likely that this happens because of how we configure the LXD profile. Since this will undergo significant changes in the future, I did not dig too deeply into this issue.
https://discourse.ubuntu.com/t/lxd-containers-not-removed-in-ci-even-with-force-flag/49039
=> Add timeout to integration tests LXD container removal

.github/workflows/integration.yaml, src/k8s/pkg/k8sd/features/implementation_default.go, tests/integration/tests/conftest.py, tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_util/util.py
This PR replaces the Cilium LoadBalancer with MetalLB in the default Canonical Kubernetes configuration. The Cilium LoadBalancer had a bunch of shortcomings, e.g. IPv6 support.
=> Replace Cilium LoadBalancer with MetalLB

src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/controllers/csrsigning/reconcile.go, src/k8s/pkg/k8sd/controllers/csrsigning/validate.go, src/k8s/pkg/k8sd/controllers/csrsigning/validate_test.go, tests/integration/requirements-test.txt, tests/integration/templates/bootstrap-csr-auto-approve.yaml, tests/integration/tests/test_clustering.py, tests/integration/tox.ini
There are few issues that affect the `k8s refresh-certs` command:
* auto-approving CSR requests does not work. K8sd denies the requests since the CSR signature is missing.
* in case of worker nodes, the specified certificate expiry date and additional Subject Alternative Names are ignored.
This PR addresses these issues and adds an e2e test that refreshes control-plane and worker node certificates, validating the resulting certificates.
=> Fix certificate refresh and add e2e tests

src/k8s/pkg/k8sd/setup/kube_apiserver.go, src/k8s/pkg/k8sd/setup/kube_apiserver_test.go, src/k8s/pkg/k8sd/setup/kube_controller_manager.go, src/k8s/pkg/k8sd/setup/kube_controller_manager_test.go, src/k8s/pkg/k8sd/setup/kube_scheduler.go, src/k8s/pkg/k8sd/setup/kube_scheduler_test.go
DISA requires a TLS version of 1.2 as a minimum.
=> Add min-tls-version flag

.github/workflows/nightly-test.yaml, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/snap.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Upgrading from 1.30 to 1.31 is not supported due to incompatible changes. The upgrade tests serve as a promotion gate, so we need to have a way to exclude this release from the tests.
=> Add minimum release for upgrade tests

docs/canonicalk8s/.sphinx/requirements.txt, docs/canonicalk8s/custom_conf.py, docs/src/_parts/template-explanation, docs/src/snap/explanation/clustering.md, docs/src/snap/explanation/ingress.md, docs/src/snap/reference/architecture.md, docs/tools/custom_conf.py
Kroki causes issues with:
- rate limiting as we are too lazy to host this ourselves
- build problems on different versions of Python
This PR removes the kroki extension, the directives in the text and replaces with static SVG images until we determine a better replacement.
=> remove kroki and replace with SVGS for now

src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/app/cluster_util_test.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/k8sd/features/calico/network.go, src/k8s/pkg/k8sd/features/calico/network_test.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/network_test.go, src/k8s/pkg/k8sd/features/interface.go, src/k8s/pkg/k8sd/types/cluster_config_merge.go, src/k8s/pkg/k8sd/types/cluster_config_network.go
Pass localhost address from the start hook instead of embedding into cluster config.
=> Pass localhost address from the start hook instead of embedding into cluster config

build-scripts/hack/generate-sbom.py, build-scripts/patches/strict/0001-Strict-patch.patch
We need to remove a trailing whitespace that was added by mistake as it breaks the linting job.
At the same time, the cilium rockcraft.yaml location changed after introducing a new version, for which reason we need to update the sbom generation script.
=> Fix lint and sbom jobs

tests/branch_management/tox.ini, tests/integration/tests/test_util/config.py, tests/integration/tox.ini
We're waiting about 5 minutes for new nodes to become ready, however sometimes this isn't enough. It can take around one minute just to pull the cilium image.
For this reason, we'll double the test timeouts again.
While at it, we're configuring pytest to log timestamps, which allows us to correlate test logs with the k8s logs.
=> Increase timeouts and log test timestamps

src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/client/snapd/snap_info.go, src/k8s/pkg/k8sd/app/hooks_bootstrap.go, tests/integration/tests/test_util/test_bootstrap.py
Adds a check that uses the snapd API to let the user know microk8s must be uninstalled.
=> Check if Microk8s is installed

k8s/lib.sh, snap/snapcraft.yaml, src/k8s/pkg/k8sd/features/cilium/cleanup.go
`cilium-dbg` seems to clean up interfaces, bpf programs, network namespaces properly. Seems like we are leaking some iptables rules so added a cleanup step for left-over iptables rules from kubeproxy and cilium.
=> Cleanup left-over iptables rules from kubeproxy and cilium

docs/src/capi/explanation/in-place-upgrades.md, docs/src/capi/explanation/index.md
This PR adds the explanation page for CAPI in-place upgrades.
=> Add in-place upgrade explanation

docs/src/assets/k8sd-component.puml, docs/src/snap/reference/architecture.md
Put diagrams back in correct order 
Fix typos in diagrams 
help clarify in diagram and text the difference in deploying with Juju vs snap
=> Arch diagrams

docs/src/_parts/bootstrap_config.md
Revert a spelling change in https://github.com/canonical/k8s-snap/commit/79f3145c038b1b5901264720a1c06daf0969517d that causes the `make go.doc` command to make a change during the workflow, which fails the subsequent `git diff` check.
=> revert spelling change

build-scripts/hack/sync-images.yaml
Follow-up fix on https://github.com/canonical/k8s-snap/pull/803/files
Adds sync-images version bump.
=> Update cilium version in sync-images.yaml

k8s/lib.sh, snap/hooks/remove, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/k8sd/setup/containerd_test.go, src/k8s/pkg/snap/snap.go
We need to properly clean up the containerd path on snap removal. For that, the path needs to be stored in a file.
This serves two purposes:
1. The existence of the file indicates that the cluster was already bootstrapped and the containerd directory is not created by some other service.
2. The containerd path is configurable, having this information in a file makes it easy to access even after the k8sd service is already stopped.
Also, updates the `PreInitCheck` to check for the existence of the containerd directory, not the unix socket as the service might just be stopped temporarily.
=> Add containerd path marker file

src/k8s/pkg/k8sd/app/hooks_remove.go
apiv1 is deprecated for annotations.
`apiv1_annotations` is the recommended package now.
=> Use new annotation path

SECURITY.md, security.md
This pr adds security.md and introduces a security policy enabling users to report security issues
KU-2046
=> add security policy

k8s/lib.sh, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/k8sd/setup/containerd_test.go, tests/integration/tests/test_cleanup.py
Currently, when removing the snap, the ``/var/run/containerd`` folder is not properly removed, as it is a folder. This fixes this issue.
Additionally removes other containerd-related folders: ``/etc/containerd`` and ``/var/lib/containerd``.
We're also removing ``/opt/cni/bin`` on snap removal, which is created when bootstrapping the node. As we're removing the k8s snap, we no longer need this folder either.
=> Cleans up all containerd-related resources on snap removal

docs/src/snap/howto/install/offline.md
This pr updates the instructions for exporting images for slide loading to pass the image name with the tag, which fixes issues with images not found on air-gaped environments.
Fixes #795
KU-2094
=> Update offline.md side-load instructions

tests/integration/tests/conftest.py, tests/integration/tests/test_util/registry.py
The registry mirror instance doesn't currently include the k8s snap, which is why the log collection script is missing.
This commit will install the k8s snap on the mirror instance and also capture the "inspect.sh" stderr output.
=> Fix registry mirror log collection

docs/src/charm/howto/ceph-csi.md, docs/src/charm/howto/index.md
We're adding a guide that describes the steps to deploy Ceph and the Ceph CSI plugin using Juju.
It mostly follows the steps outlined in the ceph-csi charm readme: https://github.com/charmed-kubernetes/ceph-csi-operator/blob/main/README.md
=> Add ceph-csi how-to (Juju)

.github/workflows/integration.yaml, .github/workflows/nightly-test.yaml, tests/integration/templates/gateway-test.yaml, tests/integration/templates/ingress-test.yaml, tests/integration/templates/loadbalancer-test.yaml, tests/integration/templates/nginx-pod.yaml, tests/integration/templates/storage-setup.yaml, tests/integration/templates/storage-test.yaml, tests/integration/tests/test_dns.py, tests/integration/tests/test_util/config.py
Our tests use busybox and nginx images from dockerhub, however the CI jobs often fail due to rate limit errors.
We'll use images from GHCR instead, where the CI jobs are authenticated.
While at it, we'll configure our registry mirror to cache images from rocks.canonical.com.
=> Change busybox image registry to avoid rate limit errors

tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_network.py, tests/integration/tests/test_networking.py
A few tests occasionally time out while waiting for load balancer addresses to become available.
We'll bump these timeouts to avoid flaky tests.
```
______________________________ test_loadbalancer _______________________________
Traceback (most recent call last):
File "/home/ubuntu/actions-runner/_work/k8s-snap/k8s-snap/tests/integration/.tox/integration/lib/python3.10/site-packages/tenacity/__init__.py", line 382, in __call__
result = fn(*args, **kwargs)
File "/home/ubuntu/actions-runner/_work/k8s-snap/k8s-snap/tests/integration/tests/test_util/util.py", line 103, in exec
resp = self._run(command_args, **command_kwds)
File "/home/ubuntu/actions-runner/_work/k8s-snap/k8s-snap/tests/integration/tests/test_util/harness/lxd.py", line 221, in exec
return run(
File …
```
=> Increase test timeouts

src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/pki/control_plane_test.go, src/k8s/pkg/utils/pki/validate.go
We'll validate user provided certificates, checking fields such as:
* Common Name
* Organization
* NotBefore, NotAfter
* DNS Subject Alternative Name
Also, we ensure that the certificates are signed by the specified CAs.
=> Validate user provided certificates

src/k8s/pkg/k8sd/features/cilium/ingress.go, src/k8s/pkg/k8sd/features/cilium/ingress_test.go
- Fixed Cilium ingress chart options according to https://github.com/cilium/cilium/blob/f221719170636b0e0da2c7b8227c18967a1201c8/install/kubernetes/cilium/values.yaml#L765-L774:
- `defaultTLSSecret` was replaced by `defaultSecretName`
- Refactored string literals and added constants
The `DefaultTLSSecret` field in the `Ingress` type is not changed because Contour ingress is using that field as well:
- https://github.com/canonical/k8s-snap/blob/main/src/k8s/pkg/k8sd/features/contour/ingress.go#L130-L132
- https://github.com/canonical/k8s-snap/blob/main/k8s/manifests/charts/ck-ingress-tls/templates/tlscertificatedelegation.yaml#L8
- https://github.com/canonical/k8s-snap/blob/main/k8s/manifests/charts/ck-ingress-tls/values.yaml#L4
=> Fix cilium ingress, Refactor string literals

k8s/scripts/inspect.sh
Adding proxy settings from `etc/environment` to the inspection report will help solve deployment problems.
KU-2197
=> Add proxy setting from/etc/environment to inspection report

tests/integration/tests/test_util/registry.py
The registry setup fails if we do not set config.SNAP. However, there a valid use cases, e.g. promotion tests in which a snap is not set. We don't really care about the concrete snap version that is deployed on the registry as it is only used to collect inspection reports.
This caused the Promotion CI to fail: https://github.com/canonical/canonical-kubernetes-release-ci/actions/runs/12041142807/job/33572453089
Recently, we [added](https://github.com/canonical/k8s-snap/pull/799) a registry/mirror to the integration tests to not run into rate limits when pulling images and to reduce the overall test time. 
In the first version, this registry - which runs as a separate container - did not include the k8s-snap (it does not need it to function). However, because of that we could not get …
=> Set default k8s snap track for registry

build-scripts/hack/generate-sbom.py
This PR adds a few minor SBOM improvements:
* move cilium rockcraft files to the correct location
*  ``1.16.3/cilium/rockcraft.yaml`` -> ``cilium/1.16.3/rockcraft.yaml``
* define constants for the rock image versions, making more visible and easier to update
=> Minor SBOM improvements

build-scripts/components/kubernetes/patches/v1.32.0/0001-allow-all-nodes-to-get-k8sd-config.patch, build-scripts/components/kubernetes/patches/v1.32.0/0001-single-kubernetes-binary.patch, build-scripts/components/kubernetes/patches/v1.32.0/0001-use-resolv.conf-file-with-non-loopback-nameservers.patch, build-scripts/components/kubernetes/patches/v1.32.0/0002-Allow-node-role-labels-on-kubelet-registration.patch
Adapt the patches to the 1.32 release
We slightly modify the upstream Kubernetes for various reasons. Those patches are applied on build and can be found in `build-scripts/components/kubernetes/patches/<release>`.
The patches might - as in this case - need to be adapted to fit the refactored code in new releases hence we need a folder for each release.
See https://github.com/canonical/k8s-snap/pull/837 for a run with the latest 1.32-rc
=> Add patches for Kubernetes 1.32

.github/workflows/integration-informing.yaml, .github/workflows/integration.yaml, .github/workflows/nightly-test.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_annotations.py, tests/integration/tests/test_bootstrap.py, tests/integration/tests/test_cilium_e2e.py, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_clustering.py, tests/integration/tests/test_clustering_race.py, tests/integration/tests/test_config_propagation.py, tests/integration/tests/test_control_plane_taints.py, tests/integration/tests/test_dns.py, tests/integration/tests/test_etcd.py, tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_metrics_server.py, tests/integration/tests/test_network.py, tests/integration/tests/test_networking.py, tests/integration/tests/test_smoke.py, tests/integration/tests/test_storage.py, tests/integration/tests/test_strict_interfaces.py, tests/integration/tests/test_util/tags.py, tests/integration/tests/test_version_upgrades.py
Adds a test level to each integration test and use them in the CI
The integration tests for each PR take way too long and test a lot of things that are very unlikely to break. It is sufficient to run those in the nightly test runs or even weekly (e.g. for conformance tests).
* Assigns a test level to each integration test 
* ensures that the integration tests fail if a tag is missing for a test.
* minor refactoring to ensure pull_request level tests and nightly tests are not in the same file
* Use tags in the CI
Note that there is currently no weekly CI but I already added the tag for it. This is work for later.
=> Use test-level tags in CI

src/k8s/pkg/k8sd/app/hooks_bootstrap.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/types/k8s_service_configs.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/snap/snap_test.go, src/k8s/pkg/utils/checks/checks.go, src/k8s/pkg/utils/net.go
``PreInitChecks`` is called on bootstrap or when joining another Kubernetes cluster. Kubernetes and its services open up several ports; if they're already in use, we cannot progress.
Adding these checks will make these error cases more explainable to the user, rather than a generic bootstrap / join error.
Sample error:
```
sudo k8s bootstrap
Bootstrapping the cluster. This may take a few seconds, please wait.
Error: Failed to bootstrap the cluster.
The error was: failed to POST /k8sd/cluster: failed to bootstrap new cluster: Failed to run post-bootstrap actions: pre-init checks failed for bootstrap node: Encountered error(s) while verifying port availability for Kubernetes services: Port 10250 (needed by: kubelet) is already in use.
Port 10249 (needed by: kube-proxy-metrics) is already in …
```
=> Checks k8s-related port availability in PreInitChecks

src/k8s/cmd/k8s/k8s_bootstrap.go
During bootstrap, we're checking if microk8s is installed. If so, we're throwing an error, asking the user to uninstall microk8s first.
The problem is that this check fails when running the CAPI tests under Docker.
```
k8s bootstrap --name '' --address :2380 --file /capi/etc/config.yaml
Error: failed to check if microk8s is installed: %w failed to get
snapd snap info: Get "http://localhost/v2/snaps/microk8s": dial unix
/run/snapd.socket: connect: no such file or directory
: exited with status: 1,
```
We'll change the code to log a warning instead of throwing an error when it's unable to check the microk8s snap status.
=> Fix microk8s snap check

tests/integration/tests/test_util/util.py
The commands in `shlex` need to contain only strings. Passing an `int` fails with
`TypeError: expected string or bytes-like object, got 'int'`
Relates to: https://github.com/canonical/canonical-kubernetes-release-ci/pull/14
=> Fix install by revision in integration tests

README.md, docs/canonicalk8s/reuse/substitutions.yaml, docs/src/_parts/install.md, docs/src/assets/how-to-epa-maas-cloud-init, docs/src/capi/tutorial/getting-started.md, docs/src/charm/howto/ceph-csi.md, docs/src/charm/howto/charm.md, docs/src/charm/tutorial/getting-started.md, docs/src/snap/howto/epa.md, docs/src/snap/howto/install/lxd.md, docs/src/snap/howto/install/offline.md, docs/src/snap/howto/install/snap.md, docs/src/snap/tutorial/add-remove-nodes.md, docs/src/snap/tutorial/getting-started.md
when updating the docs install commands with each release, now we only have to update 5 files rather than 15
- docs/canonicalk8s/src/snap/reference/releases.md
- docs/src/_parts/install.md
- README.md
- docs/canonicalk8s/reuse/substitutions.yaml
- docs/src/assets/how-to-epa-maas-cloud-init
Some linting errors also addressed
=> [Docs] replace install command with literalinclude

tests/integration/tests/test_util/util.py
The integration test backport needs to be backported because the promotion CI uses the integration test of the corresponding release branch.
If a 1.31 snap should be promoted, then the 1.31 integration tests suite is executed. 
See https://github.com/canonical/canonical-kubernetes-release-ci/pull/14
=> [Backport 1.31] Fix install by revision in integration tests (#865)

src/k8s/pkg/k8sd/features/metallb/chart.go
Looks like I forgot this image when I updated metallb.
=> use rock for metallb FRR instead of upstream

src/k8s/pkg/k8sd/pki/control_plane.go, src/k8s/pkg/k8sd/pki/control_plane_test.go
We recently introduced strict checks for pre-configured certificates. However, this broke cluster-api-k8s.
We'll loosen the checks, ignoring the certificate CN and O fields, checking only:
* NotBefore/NotAfter
* CA
* DNS SANs (fewer checks though)
=> Loosen pre-configured certificate checks

k8s/lib.sh, src/k8s/cmd/util/environ.go, src/k8s/pkg/k8sd/api/cluster_bootstrap.go, src/k8s/pkg/k8sd/api/cluster_join.go, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, tests/integration/templates/bootstrap-containerd-path.yaml, tests/integration/tests/test_cleanup.py
Adds configurable containerd base dir during bootstrap / join
Currently, for the classic k8s snap, the default locations for the containerd-related files are:
```
- /etc/containerd/
- /run/containerd/
- /var/lib/containerd/
```
These paths can conflict with other containerd installations on the host (e.g. from docker), meaning that the k8s snap cannot be installed. In a developer's usecase, we shouldn't require the other services to be disabled, but we can allow the k8s snap's containerd to be installed in a different location during bootstrap / node join.
Adds the ``--containerd-base-dir`` option for k8s bootstrap and join-cluster commands. If not given, the snap's default paths will be used instead. After the node was initialized, save the containerd base location in a file, so we can …
=> Adds configurable containerd base dir during bootstrap / join

docs/src/charm/howto/cos-lite.md
Update the `Integrating with COS Lite` How-To guide to use the `k8s-operator` charm as the deployment substrate instead of the MicroK8s snap.
=> Switch COS Lite How-To to use the `k8s-operator` charm

.github/workflows/integration.yaml, .github/workflows/nightly-test.yaml, src/k8s/pkg/k8sd/api/cluster_join.go, tests/integration/tests/conftest.py, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_util/registry.py
Fix nightly job
* fix yaml definition
* ensure that the containerd base path setting is properly parsed when joining nodes
* fix containerd test assertions
* run all tests whenever there are changes under the ``tests`` dir and in case of backports
=> Fix nightly tests

src/k8s/pkg/k8sd/api/capi_access_handler_test.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/k8sd/api/node_access_handler_test.go, src/k8s/pkg/k8sd/database/capi_auth_test.go, src/k8s/pkg/k8sd/database/cluster_config_test.go, src/k8s/pkg/k8sd/database/feature_status_test.go, src/k8s/pkg/k8sd/database/kubernetes_auth_tokens_test.go, src/k8s/pkg/k8sd/database/worker_test.go, src/k8s/pkg/snap/mock/provider.go, src/k8s/pkg/utils/microcluster/state.go
* TestValidateCAPIAuthTokenAccessHandler
* rename WithDB to WithState and move to a new location with package name microcluster_testenv
* WithState gives access to the whole state.State type instead of state.State.Database() only
Depends on https://github.com/canonical/k8s-snap/pull/880
=> implement TestValidateCAPIAuthTokenAccessHandler

src/k8s/cmd/k8s/k8s_get_join_token.go
There is no need to reach out to k8sd if the node name is not provided:
```
$ sudo k8s get-join-token 
Error: A node name is required for control-plane nodes.
Error: Could not generate a join token for "".
The error was: failed to POST /k8sd/cluster/tokens: failed to create token: failed to generate a new microcluster join token: Token name "" is not a valid FQDN: Name must be 1-255 characters long
```
=> Exit early if node name is not provided in CLI

k8s/lib.sh, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/k8sd/setup/containerd_test.go, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_util/util.py
`k8sd` automatically sets up some directories with the appropriate
ownership/permissions to be used by containerd in the early stages
of the `bootstrap` and `join-cluster` commands.
In the classic (non-strict) version of the k8s-snap, these
containerd directories are system-wide (e.g. `/etc/containerd`,
`/run/containerd`, etc).
Should any of the other setup steps fail after the containerd
directories were set up, the directories would still remain on
disk and thus lead to a 'partial installation' of on the host system.
This patch ensures that `k8s` will automatically remove any
containerd-related directories which were created in the event of
the  `bootstrap` / `join-cluster` commands failing.
The containerd Base Dir is the special path all other containerd-related
paths on the snap are …
=> fix: ensure containerd-related directories removed on failed `bootstrap/join-cluster`.

docs/src/charm/howto/index.md, docs/src/charm/howto/openstack.md
This PR adds docs: how to integrate Canonical K8s with the Openstack cloud it is deployed on, by adding a layer.
=> How-to Openstack Integration

docs/src/capi/tutorial/getting-started.md
Now that Canonical Kubernetes CAPI providers are in the list of [upstream Cluster API providers](https://cluster-api.sigs.k8s.io/reference/providers.html), we can remove the instructions to add a `clusterctl.yaml` file.
* Also bumped the `clusterctl` binary to the latest according to docs: https://cluster-api.sigs.k8s.io/user/quick-start 
Inspired by https://github.com/canonical/k8s-snap/issues/904
=> CAPI docs: Remove manual provider config for clusterctl

docs/src/assets/how-to-dualstack-manifest.yaml
The YAML file in the tutorial had incorrect indentation, resulting in the following error when applying the manifest:
```
ubuntu@juju-f7d895-1:~$ sudo k8s kubectl apply -f https://raw.githubusercontent.com/canonical/k8s-snap/main/docs/src/assets/how-to-dualstack-manifest.yaml
error: error parsing https://raw.githubusercontent.com/canonical/k8s-snap/main/docs/src/assets/how-to-dualstack-manifest.yaml: error converting YAML to JSON: yaml: line 17: mapping values are not allowed in this context
```
=> Fix dualstack yaml indentation

README.md, docs/canonicalk8s/reuse/substitutions.yaml, docs/src/_parts/install.md, docs/src/assets/how-to-epa-maas-cloud-init, docs/src/snap/reference/releases.md, docs/src/snap/reference/versions/1.32.md
=> 1.32 release docs

docs/canonicalk8s/about.md, docs/canonicalk8s/community.md, docs/canonicalk8s/index.md, docs/src/about.md, docs/src/community.md
It was reported in issue #537 that the edit this page button did not work. Previous work was done to fix most pages but the about and community page at the top level were still affected. This PR fixes that functionality
=> Move files under src so edit button works

docs/src/charm/howto/index.md, docs/src/charm/howto/install-terraform.md
This PR adds documentation on the k8s and k8s-worker terraform modules.
=> Add Terraform Documentation for k8s, k8s-worker charms

src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/k8sd/setup/directories.go, tests/integration/templates/bootstrap-fail.yaml, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_util/util.py
* cleanup: fix cleanup of non-symlink containerd paths on failed `bootstrap/join-cluster`.
* integration: rename `open_local_port()` testing utility for clarity.
* integration: fix test_containerd_path_cleanup_on_failed_init.
=> Fix containerd-related path cleanup on failed bootstrap/join and associated test.

src/k8s/go.mod, src/k8s/go.sum
Fixes https://github.com/canonical/k8s-snap/security/dependabot/25
=> Bump golang.org/x/net to v0.33.0

docs/canonicalk8s/index.md, docs/src/_parts/install.md, docs/src/charm/reference/releases.md, docs/src/charm/reference/versions/1.32.md, docs/src/releases.md
This PR adds the 1.32 Canonical Kubernetes charms release notes.
=> charms docs: Add 1.32 charms release notes

README.md, docs/canonicalk8s/index.md, docs/canonicalk8s/reuse/substitutions.yaml, docs/src/_parts/install.md, docs/src/assets/how-to-epa-maas-cloud-init, docs/src/charm/reference/releases.md, docs/src/charm/reference/versions/1.32.md, docs/src/releases.md, docs/src/snap/reference/releases.md, docs/src/snap/reference/versions/1.32.md
This PR backports #899 and #913 to release 1.32
* Add 1.32 snap release notes
* Add 1.32 charms release notes
* Update navigation and channel
* Update charm channel to 1.32 stable
* Reorganize the navigation side bar to be able to see both snap and charm release notes
---------
=> [Backport 1.32] charms docs: Add 1.32 charms release notes (#913)

tests/integration/tests/test_util/harness/lxd.py
The snapd systemctl unit might not be up yet when waiting for that seed.
This can cause  
```
error: cannot communicate with server: Get "http://localhost/v2/snaps/system/conf?keys=seed.loaded": dial unix /run/snapd.socket: connect: no such file or directory
```
See, e.g. https://github.com/canonical/k8s-snap/actions/runs/12394510604/job/34598141169?pr=915
=> Retry seed loading in case snap is not ready yet

.github/actions/install-lxd/action.yaml, .github/workflows/build-snap.yaml, .github/workflows/e2e-tests.yaml
- Add a check to determine if the `lxd` snap is already installed before attempting to refresh or install it. This is required because the LXD snap is not shipped by default in 24.04 anymore.
- Replace the use of `sg lxd -c` with `sudo --user "$USER"`. This eliminates the need for password entry during the `lxc` command execution.
See https://github.com/actions/runner-images/issues/9932#issuecomment-2573170305
=> Ensure lxd is installed before attempting snap refresh

docs/src/snap/howto/networking/alternative-cni.md, docs/src/snap/howto/networking/index.md
This PR adds a how-to page for installing an alternative CNI by the example of Calico.
=> Alternative CNI How-to

docs/src/charm/howto/custom-workers.md, docs/src/charm/howto/index.md, docs/src/charm/howto/install-custom.md
Add documentation pages for deploying the `k8s` operator charms using Juju custom configuration files.
The new documentation pages cover:
- How to deploy `k8s` using a custom configuration file.
- How to deploy multiple `k8s-worker` applications using custom configurations.
=> Add docs for Juju custom configuration

docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt, docs/src/.custom_wordlist.txt, docs/src/charm/howto/index.md, docs/src/charm/howto/upgrade-minor.md, docs/src/charm/howto/upgrade-patch.md, docs/src/charm/howto/validate.md
* Ported  upgrade docs from Charmed Kubernetes
* Ported validation docs from Charmed Kubernetes
* providing docs for minor upgrades
* providing docs for patch upgrades
* providing docs for cluster validation
=> Charm Upgrade documentation

k8s/lib.sh, k8s/systemd/containerd-defaults.conf, snap/hooks/configure
Closes #718
Adds a systemd `.conf`  override file to match upstream recommendations, see https://github.com/containerd/containerd/blob/release/1.6/containerd.service for example
File is only copied over if it does not exist to make sure changes are not over-written
This approach might not work in strict as we are editing `/etc/systemd/...`
=> Add a systemd override to add containerd defaults

docs/src/capi/reference/configs.md
This PR adds `bootstrapConfig` field docs to CAPI references.
- Also updates some missing fields in the same doc.
=> docs: Add bootstrap config docs to CAPI

docs/src/snap/howto/index.md, docs/src/snap/howto/upgrades.md
This PR adds a how-to guide on snap upgrades.
=> docs: Add snap upgrades how-to

docs/canonicalk8s/index.md, docs/src/capi/explanation/index.md, docs/src/capi/explanation/installation-methods.md, docs/src/charm/explanation/index.md, docs/src/charm/explanation/installation-methods.md, docs/src/snap/explanation/index.md, docs/src/snap/explanation/installation-methods.md
This PR adds an explanation page on the different installation methods available: Snap, Juju and CAPI.
=> Choosing an installation method documentation

docs/src/snap/howto/upgrades.md
This PR applies the left over comments in the other PR https://github.com/canonical/k8s-snap/pull/934
=> docs: Fix snap upgrade how to

src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/app/hooks_remove.go
``cfg.Datastore.GetType()`` may return an empty string if the bootstrap action failed before ``database.SetClusterConfig`` has been called. Because of this, we're not removing the state dir for k8s-dqlite, which will be wrongfully removed by ``setup.K8sDqlite`` on the next bootstrap attempt.
We're now opportunistically cleaning up the ``k8s-dqlite`` related state directory.
If a bootstrap attempt fails, the ``k8s-dqlite`` service will still be running, which will cause the next bootstrap attempt to fail, as the ``k8s-dqlite`` port will be currently in use.
=> Cleans up k8s-dqlite state dir and stops it on remove hook

docs/src/snap/howto/install/index.md, docs/src/snap/howto/install/uninstall.md
A brief docs page that explains how to (completely) remove the `k8s` snap.
=> docs: Add how-to uninstall the snap section

docs/src/snap/explanation/high-availability.md, docs/src/snap/explanation/index.md
Adds a page with an explanation what high-availability is and how it is set up with Canonical Kubernetes.
=> docs: High availability explanation page

docs/src/capi/reference/index.md, docs/src/capi/reference/ports-and-services.md
The CAPI clusters exposes the same services and ports as the normal snap, hence the reference directly links to the snap docs.
=> docs: Add ports and services reference for CAPI

docs/src/charm/reference/index.md, docs/src/charm/reference/ports-and-services.md
The charm exposes the same services and ports on a unit as the snap, hence the reference directly links to the snap docs.
=> docs: Add ports and services reference for the charm

.github/actions/install-lxd/action.yaml, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_strict_interfaces.py, tests/integration/tests/test_util/util.py
This PR adds ipv6-only and ipv6-dualstack load balancer tests. Note that the ipv6-only test is currently skipped due to a known cilium limitation:
* https://github.com/cilium/cilium/issues/15082
* https://github.com/cilium/cilium/issues/17240
=> Add ipv6 load balancer tests

docs/src/charm/tutorial/basic-operations.md, docs/src/charm/tutorial/getting-started.md, docs/src/charm/tutorial/index.md
Split the Getting Started tutorial in two tutorials, covering the basic operations of the charm.
- Tutorial for basic operations in the charm
- Drive-by fixes for the Getting started tutorial
=> Add Basic Operations with the Charm

docs/src/charm/howto/install-custom.md, docs/src/charm/reference/index.md, docs/src/charm/reference/troubleshooting.md
Indicate to users that the charm config `node-labels` is both additive and destructive and can be used for either purpose.
=> [Docs] Clarify node-labels are additive or destructive

docs/src/snap/howto/index.md, docs/src/snap/howto/troubleshooting.md
Adds a How-To page on troubleshooting a Canonical Kubernetes snap deployment
=> Add snap troubleshooting How-To

docs/src/_parts/bootstrap_config.md, tests/integration/tests/test_ingress.py
get_external_service_ip repeatedly attempts to retrieve the
specified service ip.
The problem is that it uses "is None" checks to determine if
an ip was retrieved. This returns "False" for empty strings,
so the loop exits prematurely.
Note that "is None" checks are strongly discouraged in Python.
While at it, we're bumpting the timeout as well.
=> test_ingress: fix service ip poller

docs/src/charm/howto/index.md, docs/src/charm/howto/troubleshooting.md, docs/src/charm/reference/index.md, docs/src/snap/howto/index.md
Adds a How-To page on troubleshooting a Canonical Kubernetes charm deployment
=> Add how-to troubleshoot for charm deployments

docs/src/snap/howto/networking/ipv6.md
If a user want to run an IPv6-only cluster on a dualstack host, it will fail without specified the bind address because the snap will bind to the default (IPv4) interface that is available.
Adding a note to make the user aware of this.
=> Clarify IPv6-only docs interface binding

docs/canonicalk8s/index.md, docs/src/snap/explanation/about.md
Updated the home page to try achieve these objectives:
- link beginner users to the snap tutorial 
- link to snap docs 
- link to charm docs 
- link to capi docs 
- link to why choose each page 
- link to about page 
- link to architecture page 
- brief overview of what the project is 
- project and community 
- make it easy to navigate these links
=> Update home page

CONTRIBUTING.md, docs/src/snap/howto/contribute.md
Expands the Contributing page, adds a CONTRIBUTING.md that links to the Contributing page.
=> Review Contributing docs

k8s/lib.sh
We're adding a mechanism to specify custom service env variables:
``/var/snap/k8s/common/args/${service_name}-env``
Note that this feature is already supported by microk8s[1] and documented by k8s-dqlite[2].
[1] https://github.com/canonical/microk8s/blob/master/microk8s-resources/wrappers/run-k8s-dqlite-with-args#L38-L43
[2] https://github.com/canonical/k8s-snap/blob/4615c0377b85e6708ffa144b4667b2dd0fb252cf/k8s/lib.sh#L184-L194
=> Allow specifying service env variables

docs/src/charm/howto/install/install-terraform.md
Ensure that the user provides a deployment channel for the charms rather than rely on a default in the charm modules. 
* stop ignoring the channel field, and make the user provide one -- one that matches for both charms
* source the tf modules from github rather than locally checked out modules
* indicates one should run `terraform plan` before running apply
=> Simplify the docs for installing via terraform

docs/src/snap/reference/config-files/bootstrap-config.md, docs/src/snap/reference/config-files/control-plane-join-config.md, docs/src/snap/reference/config-files/index.md, docs/src/snap/reference/config-files/worker-join-config.md, docs/src/snap/reference/index.md
* Remove redundant "reference" word from titles in files and therefore navbar
* Move config file references to their own folder, config-files.
* Reference config-files folder in the navbar.
* Use absolute path references to config files
=> docs: config file reference

docs/moonray/reference/annotations.md, docs/src/snap/reference/annotations.md
* Moves calico annotations to moonray docs
* Removes cilium annotations from moonray docs
* Adds warning about v1alpha annotations
=> docs: annotations

docs/src/charm/explanation/index.md, docs/src/charm/explanation/upgrade.md, docs/src/snap/explanation/index.md, docs/src/snap/explanation/upgrade.md
Explanation page that covers both snap and charm upgrades so {include} statement used to duplicate the page in both locations
=> Upgrading explanation page

docs/src/snap/howto/storage/ceph.md, docs/src/snap/howto/storage/cloud.md, docs/src/snap/howto/storage/storage.md
Include documentation updates for the snap storage guides.
=> docs: Fix snap storage

docs/src/snap/explanation/certificates.md, docs/src/snap/explanation/channels.md, docs/src/snap/explanation/cis.md, docs/src/snap/explanation/clustering.md, docs/src/snap/explanation/index.md, docs/src/snap/explanation/ingress.md, docs/src/snap/explanation/security.md
Reorder explanation index, ensure header style consistency
=> Reorder explanation index, ensure header style consistency

docs/src/snap/explanation/ingress.md
Here are some links that do not work:
-  https://documentation.ubuntu.com/canonical-kubernetes/latest/src/capi/explanation/ingress/#../howto/networking/default-ingress
-  https://documentation.ubuntu.com/canonical-kubernetes/latest/src/capi/explanation/ingress/#../howto/networking/alternative-cni
=> Fix broken links when the ingress.md gets included in other places

docs/src/snap/reference/commands.md
* Adds missing `k8s` commands to the command reference page:
- k8s refresh-certs
- k8s completion
* Remove redundant "reference" word from page title/nav
=> docs: add missing commands to ref

k8s/scripts/inspect.sh
* Declare + assign to a variable when there is no risk doing so (https://www.shellcheck.net/wiki/SC2155)
* Run shell-format
* Replace leftover magic number with NUM_SNAP_LOG_ENTRIES
* Add report directory location message to stdout
* Use only one log_warning_red when a private key is detected
Depends on: https://github.com/canonical/k8s-snap/pull/990
=> misc inspection script cleanup

docs/canonicalk8s/.sphinx/build_requirements.py, docs/canonicalk8s/.sphinx/requirements.txt, docs/tools/.sphinx/build_requirements.py, docs/tools/.sphinx/requirements.txt
Backports https://github.com/canonical/k8s-snap/pull/996 to `release-1.32`
Fixes: https://github.com/canonical/k8s-snap/security/code-scanning/128
This PR puts a >=3.1.41 constraint on the `GitPython` requirement which is suggested by the scanner.
The mentioned scan contains multiple CVEs, all pointing to the `GitPython` dependency and each one points to a different issue that is fixed in a different version of `GitPython`. The highest version (that should contain all the fixes) is `3.1.41`.
=> [Backport 1.32] docs: Bump GitPython to 3.1.41 to fix CVEs

.github/workflows/security-scan.yaml
Fixes https://github.com/canonical/k8s-snap/security/code-scanning/469
This PR removes the top level write permission and grants job level write permissions when necessary.
Does not need a backport since the job manifest is not available in `release-1.32`.
=> ci: Fix token permissions alert

docs/src/charm/howto/index.md, docs/src/charm/howto/install/charm.md, docs/src/charm/howto/install/install-custom.md, docs/src/snap/reference/config-files/bootstrap-config.md, docs/src/snap/reference/config-files/index.md
During a previous PR where these files were moved in the the config files folder, the reference to the _parts directory was not updated correctly. This was highlighted in issue #986 . I will create another PR to address the other comments about docs in this issue.
=> [Docs] Update outdated links

docs/src/snap/explanation/index.md, docs/src/snap/explanation/package-management.md
Adds the explanation page on package management with helm.
Not sure on the placement of this explanation page, where should this reside in?
=> Add package management with helm explanation

src/k8s/pkg/k8sd/app/hooks_remove.go
Currently, if the `k8sd/v1alpha/lifecycle/skip-stop-services-on-remove` annotation is set, we're not stopping the Kubernetes-related services, but we're still removing its certificates and containerd-related paths. This will end up paralyzing services like kubelet, which might have to do Pod evictions, blocking it from finishing its job, and resulting CAPI not being able to complete its downscaling or upgrade operations.
We should remove those certificates only if we're also stopping the services.
=> Don't remove Kubernetes certificates and containerd if skipped

docs/src/_parts/bootstrap_config.md, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/k8sd/types/cluster_config_defaults.go, src/k8s/pkg/k8sd/types/cluster_config_defaults_test.go, tests/integration/tests/test_smoke.py
We'll change the defalt value of cluster-config.load-balancer.l2-mode, enabling it by default.
Docstring update: https://github.com/canonical/k8s-snap-api/pull/22
=> Enable cluster-config.load-balancer.l2-mode by default

docs/src/snap/howto/contribute.md, docs/src/snap/howto/install/dev-env.md, docs/src/snap/howto/install/snap.md, docs/src/snap/howto/restore-quorum.md, docs/src/snap/reference/dqlite.md, docs/src/snap/reference/index.md, docs/src/snap/reference/troubleshooting.md, docs/src/snap/reference/versions/1.32.md
We'll recommend the users to use a clean virtual machine or LXD container when trying out k8s-snap.
At the same time, we'll document common problems that can arise when installing k8s-snap directly on the development machine along with possible workarounds:
* docker and containerd conflicts
* fixing the "FORWARD" rules
* custom containerd base dir
* changing ip addresses
* listening on "localhost"
Other changes:
* move dqlite docs to a separate reference page and add an example on how to connect to k8s-dqlite
* fix the release note on "containerd-base-dir", it's a bootstrap config yaml entry, not a cli parameter
=> Document k8s-snap installation on dev environments

.github/workflows/scorecard.yaml
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
=> Bump actions/upload_artifact to v4

src/k8s/go.mod, src/k8s/go.sum
This version includes this bug fix: https://github.com/canonical/microcluster/commit/7073b9ff5da2891fcc5b149016596d28da892954
which let microcluster return the correct error if the cluster is already bootstrapped.
This is required for the error handling and retry in https://github.com/canonical/k8s-snap/pull/992
=> Bump microcluster version

src/k8s/pkg/client/k8sd/query.go
When bootstrapping or starting a cluster, we wait for the k8sd server to be fully ready before interacting with it. However, there are edge cases—such as during a snap refresh—where the snap attempts to interact with the CLI (e.g., to configure snap settings) while the database is still initializing.
In these scenarios, immediate failure is unnecessary. The k8sd client now retries such requests, ensuring smoother operation.
This behavior applies only to specific edge cases where it is known that the microcluster database will eventually become available.
=> Retry Temporary API Failures in Microcluster

docs/src/charm/tutorial/basic-operations.md
The command "kubectl config show" does not exist and should be "kubectl config view".
```
kubectl config show
error: unknown command "show"
See 'kubectl config -h' for help and examples
```
=> The command "kubectl config show" does not exist

docs/moonray/howto/index.md, docs/moonray/howto/two-node-ha.md, docs/src/snap/howto/index.md
The two node high availability is more of a proof of concept rather than a fully supported feature. This was done at request for moonray so moving there.
=> [Docs] Move two-node HA page to /moonray

src/k8s/pkg/k8sd/app/cluster_util.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/k8sd/features/calico/network.go, src/k8s/pkg/k8sd/features/calico/network_test.go, src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/k8sd/features/cilium/network_test.go, src/k8s/pkg/k8sd/features/interface.go, src/k8s/pkg/utils/cidr.go, src/k8s/pkg/utils/localhost.go, src/k8s/pkg/utils/localhost_test.go
Tunneling/encapsulation is not supported for ipv6 only clusters https://github.com/cilium/cilium/issues/17240 .
This PR configures Cilium to run in native routing mode on ipv6 only setups.
=> Switch to cilium native routing mode for ipv6 only setup

k8s/lib.sh, k8s/scripts/inspect.sh, src/k8s/hack/dynamic-dqlite.sh, src/k8s/hack/dynamic-go-build.sh, src/k8s/hack/static-dqlite.sh, src/k8s/hack/static-go-build.sh, tests/integration/tests/conftest.py, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/harness/juju.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/harness/multipass.py, tests/integration/tests/test_util/util.py
We need core dumps in order to effectively debug crashes, especially the ones caused by external C libraries such as dqlite.
The service start wrapper will now set ``GOTRACEBACK=crash`` and adjust the core dump limit.
We'll also need debug symbols in order to make use of the collected core dumps, which is why we'll include debug symbols even for release builds. This increases the snap size from 107MB to 135MB, which seems reasonable.
``inspect.sh`` as well as the e2e tests are updated to collect the core dumps. The core dump location defaults to /var/crash.
=> Generate and collect core dumps

docs/src/_parts/commands/k8s.md, docs/src/_parts/commands/k8s_inspect.md, docs/src/charm/howto/troubleshooting.md, docs/src/snap/howto/troubleshooting.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_inspect.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go
We're adding a "k8s inspect" command that will invoke the "inspect.sh" script, aiming to improve the user experience.
Note that we'll avoid parsing the arguments twice since that's unnecessary and would complicate the process of adding new parameters.
=> Add k8s inspect command

src/k8s/pkg/k8sd/controllers/node_label.go
The node label controller is triggered for every node change event and is currently more verbose than it should.
We'll update it so that it logs a message only if there are actual configuration changes.
=> node label ctrl: clean up log messages

docs/src/capi/howto/index.md, docs/src/capi/howto/provision.md, docs/src/capi/howto/troubleshooting.md, docs/src/capi/reference/index.md, docs/src/capi/tutorial/getting-started.md
Split tutorial for CAPI so that creating a management cluster is the tutorial, provisioning a workload cluster is moved to a how-to page.
Add capi troubleshooting pages
=> Split tutorial for CAPI, add capi troubleshooting pages

docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt, docs/src/snap/reference/troubleshooting.md
There was an issue brought up on the dqlite repo about mis-configuration of small clusters appearing as memory leaks. Adding this to the troubleshooting page.
=> [Docs] add dqlite configuration to troubleshooting page

k8s/scripts/inspect.sh
The inspect.sh script will log an error if the core dump dir is empty. We'll add a check to improve the user experience.
INFO:  Copy dmesg entries
INFO:  Collecting core dumps from /var/crash. Size: 4.0K    /var/crash
cp: cannot stat '/var/crash/*': No such file or directory
Collecting snap and related information
=> inspect.sh: avoid logging an error if there are no core dumps

src/k8s/pkg/k8sd/controllers/node_configuration_test.go, src/k8s/pkg/k8sd/controllers/update_node_configuration_test.go
This PR suggests some more tests cases to include scenarios where configmaps are signed
=> Enrich node configuration controller tests with signed configmaps

tests/integration/tests/conftest.py
This change will collect all the inspection reports before initiating the node cleanup process. Otherwise we interfere with the observed cluster, potentially breaking it, which can impede the debugging process.
=> tests: collect all inspection reports before cleaning up nodes

src/k8s/pkg/k8sd/types/cluster_config_merge_test.go, src/k8s/pkg/k8sd/types/cluster_config_validate.go
Historically, we used the Cilium loadbalancer for the loadbalancer feature. With the move to Metallb, the dependency to the network feature is no longer required.
=> Remove obsolete loadbalancer feature check

docs/canonicalk8s/capi/howto/index.md, docs/canonicalk8s/capi/howto/intermediate-ca.md
We're adding a guide that shows how intermediate CAs can be generated using HashiCorp Vault and passed to CAPI using management cluster secrets.
=> capi docs: add intermediate ca how-to

build-scripts/k8s_release.py
The pre-release automation removes obsolete branches. For that, it collects all obsolete tags and then removes the corresponding branch.
However, we don't have patch level branches, so if the current release is 1.33.0-alpha.1, the current implementation removed the `autoupdate/1.33-alpha branch` since 1.33.0-alpha.0 is obsolete.
This fix now checks the risk level before removing the branch.
=> Fix pre-release update with same risk-level

docs/canonicalk8s/snap/howto/epa.md
Correct EPA doc default CNI mention.
Closes https://github.com/canonical/k8s-snap/issues/1051
=> docs: correct EPA doc typo of default CNI 

docs/canonicalk8s/charm/howto/openstack.md
This PR adds the `k8s:external-load-balancer,   openstack-integrator:lb-consumers` relation to the Openstack how-to docs.
=> docs: Add external load balancer relation to openstack how-to

.github/workflows/nightly-test.yaml
There are some errors in the TICS job, even though the job passes. Some of these errors relate to some missing dependencies for ``pylint``.
There is one other notable type of error (hundreds of errors), related to Coverity:
```
[ERROR 5336] No analysis data found for file '/home/runner/work/k8s-snap/k8s-snap/src/k8s/pkg/k8sd/controllers/csrsigning/const.go' in 'Coverity'. Please check if the file is analyzed properly, and whether the file is in the analysis scope of the tool.
```
These errors are currently unsolvable. The current version of TICS comes with the Coverity 2024.9.0 version (as seen in ``cov-build-console.log``):
```
Coverity Build Capture (64-bit) version 2024.9.0 on Linux 6.8.0-1020-azure x86_64
Internal version numbers: 950e903b4e p-2024.9-push-30
```
According to the …
=> actions: Address some of the TICS failures

tests/integration/tox.ini
The CI takes some time to run. We would like to catch all failing tests in one run so that they can be fixed all individually before doing another CI run.
=> test: Remove --maxfail 1 from integration tests

src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/k8sd/app/app.go
In microcluster, there is now a configuration that allows us to drain any current connections before shutting down the unix / http servers.
Note that the servers will also be shut down when removing a node, or if bootstrapping or joining a node fails. If we're not waiting for the connection to drain, we may close current connections before managing to write a response to the clients, resulting in them getting EOF errors.
=> Adds DrainConnectionsTimeout microcluster configuration

docs/canonicalk8s/charm/reference/troubleshooting.md
A common issue faced by users is the fact bridge interfaces are not automatically picked up by Cilium for direct routing mode. Adding to the troubleshooting page how to add the bridge interfaces to the device list.
=> Docs: add to charm troubleshooting 

docs/canonicalk8s/charm/howto/openstack.md
This PR adds the `fan-config` instructions to Openstack how-to guide.
Addresses: https://github.com/canonical/k8s-operator/issues/323
=> docs: Add fan-config instructions to Openstack how-to guide

docs/canonicalk8s/custom_conf.py
Remove the icon at the top of the docs of an eye to show the source code of the docs. Also removes show source from the footer
=> docs: Remove see source button

build-scripts/hack/auto-merge-successful-pr.py
There where two issues:
1. "neutral" test runs (e.g. Trivy) do not "pass" but are marked as "skipped"
2. All PRs must be approved
=> Fix auto-merge script

src/k8s/pkg/k8sd/features/coredns/coredns.go, tests/integration/tests/test_dns.py
The CIS 5.1.5 rule specifies: "Ensure that default service accounts are not actively used."
Currently, ``coredns`` is using the ``default`` service account. If this rule is being enforced, ``coredns`` will no longer be able to function properly, as it won't have the expected service account token mounted.
Closes: https://github.com/canonical/cluster-api-k8s/issues/107
=> Adds non-default coredns ServiceAccount

docs/canonicalk8s/snap/reference/troubleshooting.md
Introduces a section to make sure priority of custom `ip rule`s are greater than `100`.
=> docs(reference): Add `ip rule` priority issue to common issues

tests/branch_management/tests/test_branches.py, tests/integration/tests/conftest.py, tests/integration/tests/test_gateway.py, tests/integration/tests/test_ingress.py, tests/integration/tests/test_smoke.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/snap.py, tests/integration/tests/test_util/util.py
test_gateway performs a few retries, waiting for the service IPs to be set.
The problem is that the checks use "is None" syntax, which won't properly handle empty strings. For this reason, the retry loop stops prematurely, causing test flakiness.
```
Execute command ['curl', '', '-H', 'Host: foo.bar.com'] in instance k8s-integration-a6f840-37
```
In general "is None" / "is not None" checks should be avoided. We'll update the k8s-snap tests accordingly.
=> Fix test_gateway retries

tests/integration/requirements-test.txt, tests/integration/tests/test_external_certificates.py
Adds a test that sets up Vault in a harness instance, generates its root CA and intermediate CAs and passes them to ``k8s-snap`` at bootstrap. The test creates a cluster with 2 control plane nodes and a worker node.
Adds a test that sets up Vault in a harness instance, generates its root CA and a few roles, and generates the certificates required by the Kubernetes nodes. The test creates a cluster with 2 control plane nodes and a worker node.
=> tests: Adds Vault intermediate CA and external certificates integration tests

src/k8s/cmd/k8s/k8s_bootstrap.go, src/k8s/cmd/k8s/k8s_config.go, src/k8s/cmd/k8s/k8s_generate_docs.go, src/k8s/cmd/k8s/k8s_local_node_status.go, src/k8s/cmd/k8s/k8s_refresh_certs.go, src/k8s/cmd/k8s/k8s_status.go, src/k8s/cmd/k8s/k8s_x_cleanup.go, src/k8s/cmd/k8s/k8s_x_list_images.go, src/k8s/cmd/k8s/k8s_x_print_shim_pids.go, src/k8s/cmd/k8s/k8s_x_snapd_config.go, src/k8s/cmd/k8s/k8s_x_wait_for.go
We're updating the "k8s bootstrap" command to throw an error when receiving unknown positional arguments.
For example, when passing a bootstrap config as a positional argument instead of a named argument, the command will now error out instead of ignoring the parameter, which can be confusing to end users.
=> bug: reject unknown bootstrap arguments

docs/canonicalk8s/_parts/common_vault_intermediate_ca.md, docs/canonicalk8s/capi/howto/intermediate-ca.md, docs/canonicalk8s/snap/howto/index.md, docs/canonicalk8s/snap/howto/install/custom-bootstrap-config.md, docs/canonicalk8s/snap/howto/intermediate-ca.md
* add a document describing how intermediate CAs can be passed to k8s-snap
* based on the similar doc for the capi provider
* the common Vault section was moved to a separate file and reused (included)
=> doc: k8s-snap intermediate ca docs

.github/workflows/stale-cron.yaml
We're adding a nightly job that automatically closes PRs and issues that have been inactive for 6 months.
It applies an "inactive" label after 5 months and then proceeds to close them after another month.
=> Automatically close inactive PRs and issues

.github/workflows/charm-e2e-tests.yaml, .github/workflows/lint_and_integration.yaml
We'll run the k8s-operator (charm) e2e tests for every PR to ensure that we aren't breaking the charm.
For now, we'll only run ``test_k8s.py::test_nodes_ready`` on amd64.
=> CI: Add charm e2e tests

docs/canonicalk8s/snap/explanation/index.md, docs/canonicalk8s/snap/howto/index.md, docs/canonicalk8s/snap/howto/install/index.md, docs/canonicalk8s/snap/howto/networking/index.md, docs/canonicalk8s/snap/howto/security/index.md, docs/canonicalk8s/snap/howto/storage/index.md, docs/canonicalk8s/snap/reference/index.md, docs/canonicalk8s/snap/tutorial/index.md
Rework the landing pages to conform to the recommended pattern. The landing pages should provide more information than just list the contents of the tree. 
This will also affect the order in which the pages will appear in the navigation bar at the side.
=> docs:  snap landing pages rework

docs/canonicalk8s/charm/tutorial/getting-started.md
This commit updates the getting-started guide to fix spelling and grammatical errors. The changes include:
* Correcting typos
* Adding punctuation to fix grammatical mistakes throughout the document
=> docs: Improve getting-started.md documentation

docs/canonicalk8s/charm/howto/custom-registry.md
The charm configurations use dashes instead of underscores.
=> docs: Fix configuration name

build-scripts/components/runc/patches/v1.2.5/0001-Disable-static-PIE-on-arm64.patch
The runc version was bumped, we need to update the arm patch, which no longer applies correctly.
=> fix: Add runc 1.2.5 arm patch

.github/workflows/docs-checks.yml, docs/canonicalk8s/index.md
In the documentation workflows where we pull the inclusive language check from, there was some issues  from an update with Vale not pulling the correct dictionaries. Until this is fixed, disable the check. Added small doc change to activate the doc check pipeline
=> CI: remove inclusive language check

docs/canonicalk8s/snap/howto/security/index.md, docs/canonicalk8s/snap/howto/security/report-security-issue.md, docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
Adding a how-to guide to report a security concern. This is very similar to the SECURITY.md file.
=> docs: how-to guide for reporting security issues

docs/canonicalk8s/charm/howto/ceph-csi.md
Feature addition of documenting how to relate to multiple ceph clusters with the ceph-csi charm
=> feat: Document how to deploy with ceph-csi against multiple ceph clusters

docs/canonicalk8s/custom_conf.py
Recently, stigviewer.com renewed their certificate, but they are missing their intermediate CA certificates. Because of this, creating a request in Python results in the following error:
```
>>> import requests
>>> requests.get("https://stigviewer.com")
...
requests.exceptions.SSLError: HTTPSConnectionPool(host='stigviewer.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')))
```
It is a known issue that Python does not perform AIA chasing for missing intermediate certificates on TLS connections [1].
[1] https://github.com/python/cpython/issues/62817
Until this issue is resolved, we're adding https://www.stigviewer.com/.* links …
=> docs: Ignores stigviewer.com links in linkchecker

.github/workflows/auto-merge-successful-prs.yaml, .github/workflows/backport.yaml, .github/workflows/update-components.yaml
The backport job creates the PRs using the cdkbot token but approves them using "GITHUB_TOKEN". For this reason, the approval is ignored and the backports cannot be merged automatically.
At the same time, the job that updates components uses the GH token to create the PRs, which do get merged but the e2e tests are not executed, potentially introducing regressions. Again, we'll have to use the cdkbot token.
Since the same account can't approve its own PRs, we'll try using the GH account to approve/merge PRs.
=> CI: use cdkbot token for automated jobs

.github/workflows/e2e-tests.yaml, .github/workflows/lint_and_integration.yaml, build-scripts/components/runc/patches/v1.2.5/0001-Disable-static-PIE-on-arm64.patch
This PR backports the following to 1.32 release branch:
- #1123
- #1121 (partially, only the switch to noble part, not the k8s-dqlite)
Also because of the chicken and egg problem, we need to backport the "switch to noble runners" as well, otherwise the tests won't pass. And if we want to have a separate PR for the switch to noble runners backport, the tests on that PR won't pass because of the runc patch issue.
=> [Backport 1.32] fix: Add runc 1.2.5 arm patch (#1123), Switch to noble 24.04 runners (#1121)

.github/workflows/e2e-tests.yaml
Resolves error: `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run` by adding `arch` in the artifact name.
=> CI: fix artifact name e2e test

.github/workflows/e2e-tests.yaml, .github/workflows/lint_and_integration.yaml, .github/workflows/nightly-test.yaml
There is a lot of duplicated information in the action names right now. this aims to simplify the names.
The duplication is caused by callers (lint_and_integration.yaml, nightly-test.yaml) duplicating information that the callee (e2e-tests.yaml) already outputs.
**Original**
Nightly Tests / Integration Test ubuntu:20.04 amd64 / Integration Test ubuntu:20.04 amd64
Lint and integration tests / Test ubuntu:24.04 / Integration Test ubuntu:24.04 amd64 k8s.snap
**Simplified**
Nightly / Integration (ubuntu:20.04, arm64, latest/edge) / Tests
Lint and Integration / Integration (ubuntu:20.04, arm64, latest/edge, k8s.snap) / Tests
Removes redundant words and platform mentions while preserving essential context.
None.
No.
If any item on the checklist is not …
=> ci: simplify names

docs/canonicalk8s/charm/reference/az.md, docs/canonicalk8s/charm/reference/index.md
This PR adds the reference docs for the AZ node labels applied by the charm.
=> docs: Add charm AZ node labels

docs/canonicalk8s/_parts/commands/k8s.md, docs/canonicalk8s/_parts/commands/k8s_certs-status.md, docs/canonicalk8s/snap/reference/commands.md, src/k8s/cmd/k8s/k8s.go, src/k8s/cmd/k8s/k8s_certs_status.go, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/client/k8sd/interface.go, src/k8s/pkg/client/k8sd/manage.go, src/k8s/pkg/client/k8sd/mock/mock.go, src/k8s/pkg/k8sd/api/certificates_status.go, src/k8s/pkg/k8sd/api/endpoints.go, src/k8s/pkg/utils/pki/load.go
> [!WARNING]  
> DO NOT MERGE until we change the version of the `k8s-snap-api` go module ([PR](https://github.com/canonical/k8s-snap-api/pull/29)).
Add a new command to display a detailed view of the certificates status on a node.
This pull request adds the `certs-status` command, which prints the status of the node's certificates. On control plane nodes, it displays the certificate authorities along with all certificates, including those in the kubeconfigs. On worker nodes, it shows the certificates and kubeconfig certificates.
=> feat: add `certs-status` command

.github/workflows/e2e-tests.yaml
Right now, only the airgapped tests run on the main branch as this was left-over from the airgapped tests PR
Remove the accidentally introduced airgapped test filter
=> fix: remove airgapped test filter

snap/hooks/post-refresh, snap/hooks/pre-refresh
The snap and k8sd configurations are synchronized via k8s x-snapd-config in the configure hook. However, this process requires access to the k8sd API, which may be unavailable during an upgrade. For instance, in a clustered setup with microcluster, the upgrade process can be blocked until all nodes are on the same version, causing the reconciliation to time out.
We now explicitly disable the config sync during the snap upgrade to avoid such scenarios.
After the refresh the sync is enabled again by doing a reconcilation.
We use the pre/post-hooks of the snap to inject that logic in the snap lifecycle. Read more on hooks [here](https://snapcraft.io/docs/supported-snap-hooks#heading--the-configure-hook)
* 1.32
=> fix: Temporarily disable snap/k8sd config sync during snap upgrade

docs/canonicalk8s/charm/howto/install/install-lxd.md, docs/canonicalk8s/snap/howto/install/lxd.md
LXD privileged containers are about to become deprecated and Cilium doesn't currently work with unprivileged containers. That might change soon: https://github.com/canonical/lxd/pull/15009
For now, we'll update the documentation and tell the users to go with LXD vms instead of containers.
=> docs: use lxd vms instead of containers

.github/workflows/lint_pr.yaml
According to the documentation [1], ``pull_request_target`` events should be used in a fork-based workflow.
If ``pull_request`` is being used intead, it will only work with PRs from the same repository. With this configuration, if a PR is sent from a fork, an error will occur.
Note that, according to the documentation, PRs that introduce this GitHub action won't trigger the action (including this one), and PRs that change the action's configuration will not be reflected in the updating PRs.
[1] https://github.com/amannn/action-semantic-pull-request?tab=readme-ov-file#event-triggers
Updates even trigger from ``pull_request`` to ``pull_request_target``.
If any item on the …
=> ci: Changes PR linter event trigger

docs/canonicalk8s/charm/tutorial/basic-operations.md
The command:
```shell
juju run k8s/0 get-kubeconfig | yq '.kubeconfig' >> ~/.kube/config
```
in [Basic Canonical Kubernetes charm operations](https://documentation.ubuntu.com/canonical-kubernetes/latest/charm/tutorial/basic-operations/#set-up-kubectl) produces an unreadable config as it escapes and quotes the given string.
This leads to `kubectl config view` failing with:
```
error: error loading config file "/home/me/.kube/config": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
Using raw output with the `-r` flag to `yq` solves this, i.e. changing the command to:
```shell
juju run k8s/0 get-kubeconfig | yq -r '.kubeconfig' >> …
```
=> docs: use raw output for `yq`

.github/workflows/lint_and_integration.yaml
If the Kubernetes components / features are updated, we should be more thorough with the tests we run.
If there are any updates to ``src/k8s/pkg/k8sd/features/.*/``, we're now running more tests (``up_to_weekly``).
``release-1.32``, ``release-1.31``.
=> ci: Run all tests on Kubernetes component / feature updates

src/k8s/pkg/k8sd/features/cilium/network.go
Session affinity is disabled by default in the cilium helm chart. Note that there are a few session affinity related Conformance tests which are failing because of this fact:
```
[sig-network] Services should be able to switch session affinity for NodePort service [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity work for service with type clusterIP [LinuxOnly] [Conformance]
[sig-network] Services should have session affinity work for NodePort service [LinuxOnly] [Conformance]
[sig-network] Services should be able to switch session affinity for service with type clusterIP [LinuxOnly] [Conformance]
```
Enabling this should resolve the failures for the tests mentioned above.
Note that the ``sessionAffinity`` helm chart option was introduced in 1.12.0.
Include a …
=> cilium: Enables cilium session affinity

tests/integration/tests/test_airgapped.py
A few tests have been introduced recently, adding airgapped scenarios. However, it seems that it may have some networking-related side effects, causing other tests to fail, no longer being to pull images afterwards:
```
Mar 11 01:44:51 k8s-integration-99c42d-1 registry[1280]: time="2025-03-11T01:44:51.314497836Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=1.27.0" err.message="manifest unknown" go.version=go1.20.8 http.request.host="10.94.42.78:5000" http.request.id=94e2d706-b8d2-4d13-b23e-ec6e8ffad355 http.request.method=HEAD http.request.remoteaddr="10.94.42.193:47676" http.request.uri="/v2/containerd/nginx/manifests/1.27.0?ns=ghcr.io" http.request.useragent="containerd/v1.6.37" http.response.contenttype="application/json; …
```
=> test: Skip airgapped tests

tests/integration/tests/test_util/snap.py, tests/integration/tests/test_version_upgrades.py
It seems that at the moment there are some issues with ``test_version_upgrades``, causing it to fail. Specifically, it fails while upgrading from 1.32 to 1.33.
Filters out upgrade versions newer than 1.32 and latest.
=> test: Skips upgrade test to 1.33 and newer

tests/integration/tests/test_util/snap.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
This PR fixes the `test_mixed_versions_join` test.
- https://github.com/canonical/k8s-snap/actions/runs/13701285429/job/38324949769?pr=1155 
We're trying to install the previous k8s snap in this function. For our tests, since the main snap is the one built in the CI, we either need to install 1.32-classic/stable or 1.31-classic/stable.
This PR makes it so that we install 1.32-classic/stable since 1.31-classic/stable is not supported
=> [1.32] ci: Fix `test_mixed_versions_join`

src/k8s/pkg/k8sd/features/cilium/network.go
A few CNCF Conformance tests would fail on a Canonical Kubernetes cluster. This PR will address those failures by enabling a few Cilium features.
Starting with cilium 1.17 [1][2], it now supports protocol differentiation. Setting the ``loadBalancer.protocolDifferentiation.enabled`` will result in ``bpf-lb-proto-diff`` being set in cilium's configmap, which corresponds to this feature. We need this feature in order for the following Conformance test to pass:
```
[sig-network] HostPort validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance] [sig-network, Conformance]
```
However, that is not enough for the test to pass. We also need to support `HostPort`s. According to the documentation [3], because we're the standard …
=> feat: Enables cilium protocol differentiation 

.github/workflows/integration-informing.yaml, .github/workflows/integration.yaml, .github/workflows/nightly-test.yaml, tests/integration/tests/test_util/snap.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Note: no need to update ``k8s-dqlite`` in ``release-1.31``.
=> [Backport release-1.31] switch to noble (24.04) runners (#1121), Fix test_mixed_versions_join (#1165), Skips upgrade test to 1.33 and newer (#1178)

.github/workflows/lint_and_integration.yaml
If the Kubernetes components / features are updated, we should be more thorough with the tests we run.
If there are any updates to ``src/k8s/pkg/k8sd/features/.*/``, we're now running more tests (``up_to_weekly``).
=> [Backport release-1.32] ci: Run all tests on Kubernetes component / feature updates (#1171)

tests/integration/tests/test_airgapped.py
The airgapped tests used and modified the global registry which caused connectivity issues in in follow-up test-cases.
The test now creates a separate registry instead.
-
Not required.
=> fix: Use function-scoped registry for airgapped tests

.github/workflows/markdown.yaml
Backport of https://github.com/canonical/k8s-snap/pull/1189 to `release-1.31`.
=> [Backport release-1.31] ci: remove compromised dependency

docs/canonicalk8s/charm/howto/install/install-terraform.md
This PR suggests a tiny typo fix on how to install Canonical k8s using Terraform
=> fix: Terraform installation doc typo

docs/canonicalk8s/snap/explanation/load-balancer.md
Update a broken link in the load balancer explanation page 
Link updated
#1187 
1.32
=> docs: fix broken link issue #1187

.github/workflows/e2e-tests.yaml, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/snap.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
It is possible that during a refresh something goes wrong and snapd decides it should rollback.  To simulate this we should have a test as part of the upgrade suite that would do a refresh to the new revision.
This test will downgrade the snap through the channels, and at each downgrade, attempt a rollback.
Example of downgrading while rolling back through channels:
Channels:  1.32-classic/stable, 1.31-classic/stable
Segment 1: 1.32-classic/stable -> 1.31-classic/stable -> 1.32-classic/stable
Segment 2: 1.31-classic/stable -> 1.30-classic/stable -> 1.31-classic/stable
=> test: implement version_downgrade_with_rollback test

.github/workflows/markdown.yaml
Updates the markdown lint job to pass globs instead of using `changed-files`.
release-1.32
release-1.31
=> ci: markdown lint calculate changed files through git

.github/workflows/lint_pr.yaml
Prevent command substitution in this CI check.
Reproduce example:
```bash
#!/bin/bash
PR_TITLE="fix: `env | sort`"
IS_DRAFT="false"
echo "PR Title value:"
echo "$PR_TITLE"
if [[ "$PR_TITLE" == \[WIP\]* ]] || [[ "$IS_DRAFT" == "true" ]]; then
echo "is_wip=true"
else
echo "is_wip=false"
fi
echo "======= FIXED ======="
PR_TITLE='fix: allow read unmanaged/managed PKI in `env | sort`'
IS_DRAFT='false'
echo "PR Title value:"
echo "$PR_TITLE"
if [[ "$PR_TITLE" == \[WIP\]* ]] || [[ "$IS_DRAFT" == "true" ]]; then
echo "is_wip=true"
else
echo "is_wip=false"
fi
```
Output:
```
❯ ./vuln-test.sh
PR Title value:
fix: COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_SESSION=ubuntu
DISPLAY=:0
... (whole ENV dumped)
is_wip=false
======= FIXED =======
PR Title value:
fix: …
```
=> fix: command substitution in `lint-pr` action

.github/workflows/lint_and_integration.yaml, .github/workflows/security-scan.yaml
We're fixing the security scan job, adding a missing bracket.
Also, the trivy-scan.sh script tries to locate the project base dir based on its own location, we'll need to update the gh action accordingly.
=> ci: fix security scan job

snap/hooks/post-refresh, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go
We disable the snapd/k8sd sync on upgrades because k8sd is not available at that time. Right now, we re-enable the sync in the snap `post-refresh` hook
The snapd/k8sd sync requires access to k8sd to obtain/sync the values. The snap `post-refresh` hook [is executed before the services started](https://snapcraft.io/docs/supported-snap-hooks#heading--post-refresh) and therefore wait until timeout.
This commit introduces a custom post-refresh hook that runs after k8sd started and moves the config sync into that hook. In the future, other machinery also depends on k8sd after a refresh (e.g. feature upgrades) so it makes sense to have this kind of common entry point to extend later.
I verified the upgrade from rev 2500 to this version (`latest/edge/ben-refresh-hook`) works for a three node …
=> fix: Move snapd sync to custom post-refresh hook

tests/branch_management/tests/conftest.py, tests/branch_management/tests/test_branches.py
We'll check the k8s version from the following files and ensure that there are no mismatches:
* build-scripts/components/kubernetes/version
* docs/canonicalk8s/_parts/install.md
* docs/canonicalk8s/reuse/substitutions.yaml
* README.md
Implements KU-2196
=> ci: add a test ensuring that there are no k8s version mismatches

.github/workflows/markdown.yaml
Backport of #1201 to `release-1.31`.
=> [Backport release-1.31] ci: markdown lint calculate changed files through git

src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/api/certificates_update.go, src/k8s/pkg/k8sd/setup/certificates.go, src/k8s/pkg/k8sd/setup/certificates_test.go
Allow the snap to partially refresh the CAs in the Control Plane PKI.
Currently, when refreshing certificates, we cannot refresh unmanaged or managed CAs in the cluster. For example, a user cannot refresh the client CA if they are using an external managed root CA. This capability is particularly useful in automated deployment mechanisms, like Juju.
**No backport needed**
- Integration tests will be addressed in KU-2844
=> fix: allow read unmanaged/managed PKI in `refresh-certs`

.github/workflows/nightly-test.yaml
* The returncode of `jq` was not properly evaluated causing the statement to always succeed
* Only ping @k8s-engineers to avoid management pings
=> fix: Mattermost bot returncode and ping

src/k8s/pkg/k8sd/setup/certificates_test.go
The #1151 issue is already addressed in #1203. This PR adds a single test to check the `client-ca.key` is created.
=> chore: add test to check client-ca.key is generated

.github/actions/install-lxd/action.yaml, tests/integration/tests/test_util/util.py
Recently, installing LXD has triggered rate-limit problems, resulting in context cancelled errors during snap install. 
Based on feedback from the Snap Store team, pre-installing xdelta3 helps alleviate these issues.
This is a temporary solution until the snapd team resolved the issue.
=> fix: Pre-install xdelta3 to mitigate LXD rate-limit issues

src/k8s/hack/dynamic-dqlite.sh, src/k8s/hack/static-dqlite.sh
Launchpad occasionally returns 500 error during clone which fails the whole CI. This adds a simple retry to try and prevent the fail if possible.
=> ci: retry launchpad clone

.github/pull_request_template.md
We now expect the PR titles to be formatted based on the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/)
The problem is that it's hard to remember the list of allowed PR title prefixes, so we'll include it in the PR template.
=> chore: update PR template, including allowed PR title prefixes

.github/workflows/lint_and_integration.yaml, .github/workflows/nightly-test.yaml
At the moment, we're running the e2e tests on 20.04, 22.04 and 24.04.
To reduce the test runner load and the time it takes for a job to be picked up, we'll only run 24.04 tests as part of the PR job.
Other versions and architectures (arm64) will be covered by the nightly tests.
While at it, we'll also drop 20.04 from the nightly job. It's going to hit EOL in two months and the charm tests dropped 20.04 as well.
=> ci: update the PR test job, dropping 20.04 and 22.04

src/k8s/go.mod, src/k8s/go.sum
Update dependency from v25.0.6 to v28.0.4 to address potential vulnerabilities in this library
```
go get github.com/docker/docker@latest
```
Unsure
=> fix: Update github.com/docker/docker v28.0.4

tests/integration/tests/test_airgapped.py
Right now, the airgapped tests fail on the Github runners for unknown reasons. This blocks several other work items so we disable them for now to unblock other work
=> test: Disable airgapped tests

build-scripts/hack/generate-sbom.py, build-scripts/hack/requirements.txt, build-scripts/hack/util.py, tests/integration/tests/conftest.py
The SBOM step clones launchpad repositories. These clones sometimes result in a failed SBOM step, even though a retry could have prevented the failure. This implements a retry mechanism by adding retry_n and retry_delay with 5 as the default values.
=> ci: add sbom retry

.github/workflows/nightly-test.yaml
There seems to be an issue with TICS and the test is constantly failing right now.
We remove the test for now. I added a card to investigate this in the upcoming pulse.
=> test: Disable failing TICS test

tests/integration/tests/conftest.py, tests/integration/tests/test_annotations.py, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_clustering.py, tests/integration/tests/test_config_propagation.py, tests/integration/tests/test_external_certificates.py, tests/integration/tests/test_networking.py, tests/integration/tests/test_node_availability_zone.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
To make the upgrade and rollback tests more comprehensive, we'll use a multi-node cluster with 3 control plane nodes and one worker node.
Other fixes introduced by this PR:
* avoid using duplicate names for the inspection report artifacts
* improve cluster status checks, avoiding test flakiness and redundant code while improving logging
=> test: Use multi-node cluster as part of upgrade/rollback tests

.github/workflows/nightly-test.yaml, .github/workflows/security-scan.yaml
Uses the ``send-scan.py`` script from the k8s-workflows repository to send cards to Jira. These are generated from the Trivy scan results.
=> ci: Send trivy vulnerability records to Jira

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/_parts/common_hardening.md, docs/canonicalk8s/snap/howto/security/cis-assessment.md, docs/canonicalk8s/snap/howto/security/disa-stig-assessment.md, docs/canonicalk8s/snap/howto/security/hardening.md, docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
The spec **SEC0030** requires us to have “security documentation that enables our users to be in control and informed of the security posture, and usage of our products”. We have worked on the content in the SSDLC Documentation effort. 
Let’s turn it into a page that we can publish.
=> feat: reorganize common-hardening to be a more generic security posture

tests/integration/tests/conftest.py, tests/integration/tests/test_util/etcd.py
This change will ensure that etcd instances are cleaned up immediately after the test instead of waiting until the end of the test suite.
By doing so, we avoid the situation in which subsequent tests run out of resources due to the leaked instances.
=> test: cleanup etcd instances immediately after the test

docs/canonicalk8s/charm/howto/install/charm.md, docs/canonicalk8s/charm/howto/upgrade-minor.md, docs/canonicalk8s/charm/howto/upgrade-patch.md, docs/canonicalk8s/charm/reference/az.md
Switch Juju docs to `documentation.ubuntu.com`
=> fix: juju links in docs

tests/integration/tests/test_cncf_conformace.py
The test ``validates resource limits of pods that are allowed to run [Conformance]`` currently fails randomly due to a scheduling error. If a node is labeled, and immediately afterwards a Pod targeting that node label is created, the Pod has a chance of failing to be scheduled properly, causing the test to fail.
We're skipping the test until this issue is addressed.
xref: https://github.com/kubernetes/kubernetes/issues/131150
Should this PR be backported? If so, to which release? No.
=> test: Skips the flaky CNCF test

tests/integration/tests/test_version_upgrades.py
We had to disable worker refresh tests due to a known issue. Once the fix gets backported and promoted to all the tracks covered by the refresh tests, we can test worker nodes as well.
Follow-up of: https://github.com/canonical/k8s-snap/pull/1233
Requires the following backport to be merged and promoted: https://github.com/canonical/k8s-snap/pull/1239
=> test: enable worker refresh tests

tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/harness/multipass.py
At the moment, the harness instances are named like this:
```
instance_id = f"k8s-integration-{os.urandom(3).hex()}-{self.next_id()}"
k8s-integration-d8ebed-24
...
k8s-integration-795f32-25
```
Let's move the id number in front so that instances belonging to the same test will reside next to each other, making them easier to find in the inspection reports:
```
instance_id = f"k8s-integration-{self.next_id()}-{os.urandom(3).hex()}"
k8s-integration-24-d8ebed
k8s-integration-25-795f32
```
=> test: change harness instance naming

src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/docgen/godoc.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/node.go, src/k8s/pkg/k8sd/setup/kubelet_test.go, tests/integration/templates/bootstrap-node-taints.yaml, tests/integration/templates/worker-join-node-taints.yaml, tests/integration/tests/test_node_taints.py, tests/integration/tests/test_util/util.py
- Add `taints` to the `GetNodeStatus` RPC.
- Add `datastore`, `pod-cidr`, and `service-cidr` to the `GetClusterConfig` RPC.
`k8s-operator` needs to know certain things about the node and cluster to prevent the user from changing some charm configs that should only be set on bootstrap time and can't be changed later.
=> feat(k8sd): Update GetNodeStatus and GetClusterConfig RPCs

.github/workflows/e2e-tests.yaml, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/util.py
This PR enables the tests to use the correct default previous snap track in e2e tests.
=> ci: Use correct assume previous snap track in tests

src/k8s/pkg/k8sd/types/worker.go, src/k8s/pkg/k8sd/types/worker_test.go
In some cases, a worker token was wrongly interpreted as an control-plane/microcluster token because the decoding mechanism used `base64.RawStdEncoding` which caused a decoding error if the worker node contained [padding](https://medium.com/@partha.pratimnayak/understanding-base64-encoding-7764b4ecce3c).
Ensure that Base64 encoding of the worker token uses standard encoding with padding to avoid decoding errors. 
This is a bugfix which we need to backport to 1.32
=> fix: ensure worker token base64 decoding handles padding correctly

.github/workflows/charm-e2e-tests.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/nightly-test.yaml, build-scripts/hack/requirements.txt, src/k8s/go.mod, src/k8s/go.sum, src/k8s/pkg/docgen/godoc.go, src/k8s/pkg/k8sd/api/cluster_config.go, src/k8s/pkg/k8sd/api/node.go, src/k8s/pkg/k8sd/setup/kubelet_test.go, tests/integration/templates/bootstrap-node-taints.yaml, tests/integration/templates/worker-join-node-taints.yaml, tests/integration/tests/test_external_certificates.py, tests/integration/tests/test_node_taints.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Introduce testing for the external certificate updates using the `refresh-certs` command.
This pull request enhances the existing nightly tests for validating the external certificates functionality in the snap by adding the `refresh-certs` command to update the external certificates as part of the process.
=> test: update external certs

src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/utils/chan.go
This PR resets the "is reconciled" state before starting a new reconciliation, by making sure the `reconciledCh` is empty.
This channel is basically a thread-safe boolean.
It's worth noting that while this PR improves how we're informed about the reconciliation state of the features, it's still prone to race conditions, as the whole operation of "triggering a reconciliation and emptying the `reconciledCh`" is not atomic (we might trigger a reconciliation, immediately successfully read from the `reconciledCh` afterwards and think that the reconciliation that WE triggered was successful, but that might not be the case. What we've read from the `reconciledCh` might have been for a previous successful reconciliation that is yet to be emptied in the next reconciliation loop).
=> fix: Reset reconciled state before reconciling

src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/controllers/node_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_label.go, src/k8s/pkg/k8sd/controllers/node_label_test.go
The k8sd controller unit tests will emit a test event and wait for the reconcile loop to handle it.
UpdateNodeConfigurationController uses a channel to notify that the reconciliation finished, however the other tests will just wait for about 100ms and expect the reconcile to finish.
The 100ms sleep is flaky, sometimes it takes longer for the events to be processed.
To address this, we'll use the same post-reconciliation notification in all k8sd controllers.
=> test: properly wait for k8sd controllers to finish reconciling

k8s/crds/upgrades.k8sd.io.yaml, src/k8s/go.mod, src/k8s/pkg/client/kubernetes/crds.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_node_ready.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/utils/file.go, src/k8s/pkg/utils/file_test.go, tests/integration/templates/upgrade.yaml, tests/integration/tests/test_version_upgrades.py
Add a custom resource to track upgrades of the cluster. Also, a mechanism for loading all CRDs in the k8s/crds directory is created. This is preparation work for the feature upgrades.
-
The feature upgrade work will not be backported.
=> feat: Add Update CRD

docs/canonicalk8s/snap/howto/install/lxd.md
The information about privileged LXD containers not being supported anymore is inaccurate. 
Clarify while they are supported, it is not recommended. 
#1197
1.32
=> docs: Update LXD privileged container info

tests/integration/tests/conftest.py, tests/integration/tests/test_airgapped.py, tests/integration/tests/test_clustering_race.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_strict_interfaces.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_util/harness/juju.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/harness/multipass.py, tests/integration/tests/test_util/registry.py
* use pytest.mark.xfail decorator to avoid initializing instances for skipped tests
* avoid creating the registry instance if the local mirror is disabled
* add a "-registry" suffix to the registry instance name
=> test: small e2e test improvements

src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/api/certificates_update.go, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/controllers/node_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_label.go, src/k8s/pkg/k8sd/controllers/node_label_test.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/pebble.go, src/k8s/pkg/snap/pebble_test.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/snap/snap_test.go, src/k8s/pkg/snap/util/services.go, src/k8s/pkg/snap/util/services_test.go, tests/integration/tests/test_clustering_race.py
Some services (e.g. k8s-dqlite) take a considerable amount of time to shutdown in some cases. Microcluster has a fixed 30s timeout for the remove hook which caused removing a node to fail in some scenarios.
With this commit, the remove hook will not wait anymore on services to terminate. The cleanup on a removed node is on a best-effort basis so in that case we don't care when (and even if) a service is actually stopped.
Code changes:
* Renames/refactored `Start/Stop/RestartService` to `...Services` and accept a slice instead of single string name. If we don't want to wait for snap services to stop, we need to have a way to pass all services at once. If we would do a `--no-wait` and then sequentially call `snap service stop`, this would fail with `snap: change in-progress`. 
* Use `snap` …
=> fix: Don't wait for services to terminate on removed node

docs/canonicalk8s/snap/reference/dqlite.md
Minor typo caused this command to not be copy&paste-able
=> docs: Fix dqlite command

src/k8s/pkg/k8sd/api/certificates_refresh.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_node_ready.go, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/controllers/node_configuration_test.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/pebble.go, src/k8s/pkg/snap/pebble_test.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/snap/snap_test.go, src/k8s/pkg/snap/util/services.go, src/k8s/pkg/snap/util/services_test.go, tests/integration/tests/conftest.py, tests/integration/tests/test_annotations.py, tests/integration/tests/test_clustering_race.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_strict_interfaces.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_util/harness/juju.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/harness/multipass.py, tests/integration/tests/test_util/registry.py, tests/integration/tests/test_util/util.py
Manual backport of: 
* https://github.com/canonical/k8s-snap/pull/1262 - bugfix 
* https://github.com/canonical/k8s-snap/pull/1228 - bugfix
* https://github.com/canonical/k8s-snap/pull/1279 - not strictly required but only touches test-code and makes the test run faster
This could not be auto-created because there was a merge conflict. Putting both PRs in on backport to make the CI pass.
=> Backport 1228 and 1262

.github/workflows/e2e-tests.yaml, tests/integration/tests/test_version_upgrades.py
Ensures the following upgrades:
For PRs against main:
1.32-<flavor>/stable -> latest/edge/<flavor> -> PR
For PRs against release-1.XX:
1.XX-<flavor>/stable -> 1.XY-<flavor> -> PR
=> fix: Include latest channel if testing against main

tests/integration/tests/conftest.py, tests/integration/tests/test_airgapped.py, tests/integration/tests/test_util/config.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/registry.py, tests/integration/tests/test_util/util.py
The airgap tests are known to fail and currently marked as xfail.
We'll re-enable them and make a few improvements aiming to eliminate flakiness:
* ensure that the registry instance is cleaned up at the end of the
tests
* avoid pulling snaps unless really necessary
* use snaps provided through TEST_SNAP
* use preloaded snaps (snapd, core20)
* move this to a separate helper called "preload_snaps"
=> test: re-enable airgapped tests

docs/canonicalk8s/assets/k8s-container.puml, docs/canonicalk8s/assets/k8sd-component.puml, docs/canonicalk8s/charm/explanation/architecture.md, docs/canonicalk8s/charm/explanation/index.md, docs/canonicalk8s/charm/index.md, docs/canonicalk8s/charm/reference/architecture.md, docs/canonicalk8s/charm/reference/index.md, docs/canonicalk8s/snap/explanation/architecture.md, docs/canonicalk8s/snap/explanation/index.md, docs/canonicalk8s/snap/howto/install/lxd.md, docs/canonicalk8s/snap/index.md, docs/canonicalk8s/snap/reference/architecture.md, docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
Our current architecture reference page goes between reference and explanation in terms of the Diataxis framework. 
Create another architecture page under explanation. 
Remove the explanation material from the reference architecture page. 
Create the same pages under charms.
Update links to architecture page.
N/A
=> docs: Update architecture reference page

tests/integration/tests/test_cleanup.py
One of the tests uses a custom containerd base directory. The problem is that it places the registry configuration at a wrong location that gets ignored.
For this reason, this test will always try to pull the images from the upstream registry, which causes flakiness (timeouts due to the image size and api rate limiting).
We'll solve the issue by using the same directory that is specified in the containerd config file:
```
[plugins."io.containerd.grpc.v1.cri".registry]
config_path = "/home/ubuntu/k8s-containerd/etc/containerd/hosts.d"
```
=> test: ensure that the containerd test uses local mirror

src/k8s/pkg/docgen/godoc.go
Backport of https://github.com/canonical/k8s-snap/commit/1152871a85e2adaec5f126d28899c6f3d37fd376 to `release-1.32`
=> [Backport release-1.32] godoc: ignore _test packages

.github/workflows/backport.yaml
Update token used for approving backports and pin the backport-action to specific commit hash.
=> chore: update token used for approving backports

docs/canonicalk8s/.sphinx/.markdownlint.json, docs/moonray/doc-cheat-sheet-myst.md
Backport https://github.com/canonical/k8s-snap/pull/1296/commits/d249120a720f2ea3d66fcb1a7c3cbfba9a522512 and https://github.com/canonical/k8s-snap/pull/1296/commits/e4e628275414c513c6317e99f57d446d08d31885 to `release-1.32`
=> [Backport 1.32] fix: Disable markdown lint

tests/integration/tests/test_annotations.py, tests/integration/tests/test_util/util.py
When a node is removed from a cluster, microcluster removes the k8sd state folder, which includes the `daemon.yaml` file required for the service to start. Because of this, the service is in a constant loop of starting and crashing. We cannot expect the service to be running in this case.
Skip checking if k8sd is active for the `test_skip_services_stop_on_remove` test.
=> test: Do not expect k8sd to be active after node removal

.github/workflows/security-scan.yaml
Using this option will bump the CVEs in the CISA KEV list at least "HIGH" priority.
No.
=> ci: Bump CISA KEV CVEs priority

tests/integration/tests/test_util/util.py
Currently, we're assuming that a process' ``stdout`` and ``stderr`` are bytes, but that's not always the case. First of all, if the output is not captured, they are None, and if ``text=True``, then the output will be strings.
Decode only if the output is in bytes.
=> test: Avoid decoding strings

tests/integration/tests/conftest.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Support running test_version_upgrades without a local snapfile
* pairs nicely with https://github.com/canonical/canonical-kubernetes-release-ci/pull/28 to run the promote automation
=> test: Run test upgrades without needing a local snap

docs/canonicalk8s/snap/howto/install/offline.md, src/k8s/pkg/k8sd/features/localpv/chart.go
Bump rawfile-localpv image from 0.8.1 -> 0.8.2
Component upgrade
Should this PR be backported? If so, to which release? Yes
=> chore: Bump rawfile-localpv image

k8s/crds/upgrades.k8sd.io.yaml, src/k8s/pkg/client/kubernetes/node.go, src/k8s/pkg/client/kubernetes/node_test.go, src/k8s/pkg/client/kubernetes/upgrades.go, src/k8s/pkg/client/snapd/snap_info.go, src/k8s/pkg/k8sd/api/cluster_remove.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/hooks_node_ready.go, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/snap/snap_test.go, tests/integration/tests/test_version_upgrades.py
Introduces support for a controlled feature upgrade with a rolling upgrade strategy as done e.g. in CAPI.
See spec KU-137 for details.
=> feat: Feature upgrade rollout upgrade

docs/canonicalk8s/charm/howto/install/charm.md, docs/canonicalk8s/charm/howto/upgrade-minor.md, docs/canonicalk8s/charm/howto/upgrade-patch.md, docs/canonicalk8s/charm/reference/az.md
Resolve broken links quickly
Honestly, it is likely a short term fix
move `juju/latest` -> `juju/3.6`
I don't know
=> docs: Move from juju/latest to juju/3.6 docs

tests/integration/tests/test_annotations.py, tests/integration/tests/test_util/util.py
(cherry picked from commit 48917ca2a805abf777d280e14139099b24aa47a8)
When a node is removed from a cluster, microcluster removes the k8sd state folder, which includes the `daemon.yaml` file required for the service to start. Because of this, the service is in a constant loop of starting and crashing. We cannot expect the service to be running in this case.
Skip checking if k8sd is active for the `test_skip_services_stop_on_remove` test.
=> [Backport release-1.32] test: Do not expect k8sd to be active after node removal (#1311)

docs/canonicalk8s/snap/howto/install/dev-env.md
Fix small typo `boostrap` -> `bootstrap`.
=> chore: fix typo in code example

docs/canonicalk8s/snap/howto/install/offline.md, src/k8s/pkg/k8sd/features/localpv/chart.go
Backports #1323 
Bump rawfile-localpv image from 0.8.0-ck4 -> 0.8.2
Component upgrade
Should this PR be backported? If so, to which release? [this is the backport]
=> fix: Backport #1323 to release 1.32

docs/canonicalk8s/charm/howto/hardening.md, docs/canonicalk8s/charm/howto/index.md
We're mostly reusing the snap how-to guide, just adding a note that the same settings can be applied by either connecting to the Juju units or using settings such as `kube-apiserver-extra-args`.
=> docs: add charm hardening page

docs/canonicalk8s/charm/howto/upgrade-minor.md, docs/canonicalk8s/charm/howto/upgrade-patch.md, docs/canonicalk8s/charm/reference/versions/1.32.md, docs/canonicalk8s/custom_conf.py, docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
<I want to make sure the changes are all in stable before we merge this PR >
Our current release notes do not include any information on back ported PRs. 
We have come up with a plan to keep these up to date in the future and the PR will get the doc up to date for now. 
1.32
=> docs: Add charm patch notices for 1.32

tests/integration/tests/test_clustering.py
This test was originally introduced to validate that minor version upgrades work by allowing nodes with different versions to join the same cluster. However, we now have dedicated version upgrade tests that more accurately cover this scenario.
With the introduction of the rollout upgrade feature, this test has started to fail—nodes attempting to join a cluster with a different patch version are now rejected, as expected. The correct process is to upgrade the cluster first, then join the node.
Since the test no longer reflects a valid upgrade path and has become obsolete, it is being removed.
=> test: Remove mixed-version join test

docs/canonicalk8s/snap/howto/security/disa-stig-assessment.md
We had to disable the markdown linter on this file as it was failing. 
This PR fixes this issue. It is mainly formatting that I changed so the easiest way to review this I think would be to view the RTD preview in the checks below docs/readthedocs.com:canonical-k8s-snap
=> docs: Fix markdown errors

docs/canonicalk8s/capi/explanation/capi-ck8s.md, docs/canonicalk8s/capi/explanation/index.md
It was highlighted that this page was quite dense with information. 
This rework is to try make the info more manageable
N/A
=> docs: Update CAPI explanation page

.gitignore
We're now generating subunit reports as part of the e2e tests.
Let's add these files to .gitignore to avoid commiting them by mistake.
=> test: add subunit report files to .gitignore

.github/workflows/update-pre-release-branches.yaml, build-scripts/k8s_release.py
Right now, only the latest pre-release is supported. However, in transition times there might be multiple non-stable releases (e.g. 1.33.0-rc1 and 1.34.0-alpha) which both need to be supported.
Related PR: https://github.com/canonical/canonical-kubernetes-release-ci/pull/29 (why probably should put those related functions into a util repo or so at some point...)
=> feat: Support multiple pre-releases (#29)

.github/renovate.json
Automatically update go dependencies when they go out of sync with upstream.
Create a renovate config to allow renovate to update the dependencies within the k8sd app.
=> chore: Allow renovate to update go packages in the project

src/k8s/pkg/k8sd/features/cilium/chart.go
We have recently reduced the image size of the cilium rock from 1.47 GB to 811 MB. This should reduce the amount of time spent by the Kubernetes nodes to become Ready as well.
Related: https://github.com/canonical/cilium-rocks/pull/21
Updated the rock versions to the latest ones built.
The PR title is expected to contain one of the following prefixes, following the
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/):
* feat: A new feature
* fix: A bug fix
* docs: Documentation only changes
* style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* refactor: A code change that neither fixes a bug nor adds a feature
* perf: A …
=> feat: update cilium rock version

src/k8s/pkg/client/kubernetes/client.go, src/k8s/pkg/client/kubernetes/scheme.go, src/k8s/pkg/client/kubernetes/upgrades.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/controllers/upgrade/controller.go, src/k8s/pkg/k8sd/controllers/upgrade/reconcile.go
This PR uses the `controller-runtime` client to manage the Upgrade CRD. This is less error prone, and simplifies how we handle this resource significantly.
=> feat: Use controller-runtime client for Upgrade CRD

docs/canonicalk8s/charm/howto/proxy.md
Fixes https://github.com/canonical/k8s-snap/issues/1235
In the original text the CIDR for pods isn't covered. (10.0.8.0/24 doesn't cover 10.1.0.0/16). I changed the no-proxy to 10.0.0.0/8 to address this overlook.
=> docs: update proxy.md

docs/canonicalk8s/snap/howto/install/dev-env.md, docs/canonicalk8s/snap/tutorial/getting-started.md
There has been an effort this cycle to improve our tutorials.
Update the snap getting started tutorial based on feedback from a user experience research session. 
Also drive by fix of the dev env install how to guide as LXD privileged containers are no longer recommended
n/a
no
=> docs: update the tutorial based on UXR

tests/integration/tests/conftest.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Backports  #1314 to the 1.32 release branch
=> test: [Backport 1.32] Run test upgrades without needing a local snap

docs/canonicalk8s/snap/howto/security/refresh-certs.md, docs/canonicalk8s/snap/howto/security/refresh-external-certs.md
Update the `refresh-certs` docs to reflect the new user experience.
This pull request updates the `refresh-certs` docs to provide clearer guidance on selective certificate renewal using the `--certificates` flag. The changes include new notes to help users understand how to target specific certificates during the refresh process.
N/A
N/A
=> docs: add notes for new `refresh-certs` ux

docs/canonicalk8s/capi/explanation/capi-ck8s.md, docs/canonicalk8s/capi/explanation/in-place-upgrades.md, docs/canonicalk8s/capi/howto/custom-ck8s.md, docs/canonicalk8s/charm/howto/validate.md
Drive by fixes of the versions in our 1.32 branch that were missed
Versions updated to 1.32. Automatic md linter also applied to some of the files
n/a
Main has moved on so merging directly to 1.32
=> docs: update version to 1.32 in the docs

docs/canonicalk8s/snap/reference/versions/1.32.md, docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
<I want to make sure the changes are all in stable before we merge this PR >
Our current release notes do not include any information on back ported PRs. 
We have come up with a plan to keep these up to date in the future and the PR will get the doc up to date for now. 
1.32
=> docs: Add snap patch notices for 1.32

src/k8s/pkg/k8sd/features/cilium/gateway.go
Cilium automatically creates a gateway class which is not intended since k8s-snap already creates the `ck-gateway` class. 
Fixes #1331
We should probably avoid backporting this change since some users might depend on the removed class.
=> fix: remove gateway class auto created by cilium

src/k8s/pkg/client/kubernetes/endpoints.go, src/k8s/pkg/proxy/endpoints.go, src/k8s/pkg/utils/endpoints.go, src/k8s/pkg/utils/endpoints_test.go
Currently, in scenarios with clusters with IPv6, we will end up with improper IPv6 addresses in the k8s-apiserver-proxy.json, causing the k8s-apiserver-proxy service to always fail with the following error:
"Failed to start" err="failed to parse endpoint \"fd42:6db9:e49a:486b:216:3eff:fe48:5318:6443\": address fd42:6db9:e49a:486b:216:3eff:fe48:5318:6443: too many colons in address"
According to the documentation [1], the expectation is that the IPv6 address to be enclosed in brackets ([IPv6]:port).
We're writing the k8s-apiserver-proxy.json in 2 cases:
- when joining a worker node.
- when a new control plane node joined the cluster.
In the first scenario, we are properly handling the IPv6 addresses, but not in the second. This PR addresses this issue.
[1] …
=> fix: Properly parse IPv6 endpoints for k8s-apiserver-proxy.json

.github/workflows/backport.yaml
prefixing the title with `[Backport XXXX]` is not conventional commit conformant, hence we put it at the end.
=> fix: Make backport conventional commit conformant

.github/workflows/lint_and_integration.yaml
For 1.33 and beyond, we don't want to support moonray anymore and disable testing for this flavor.
=> test: Disable moonray testing for 1.33+

tests/integration/tests/test_cncf_conformace.py
The default value for `--e2e-skip` is `"\[Disruptive\]|NoExecuteTaintManager"`, which we've overridden when we started skipping a particular test.
Added the tests to ``--e2e-skip`` parameter.
N/A
=> test: Skip CNCF Disruptive tests

src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/client/kubernetes/node.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration.go, src/k8s/pkg/k8sd/controllers/control_plane_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_configuration.go, src/k8s/pkg/k8sd/controllers/node_configuration_test.go, src/k8s/pkg/k8sd/controllers/node_label.go, src/k8s/pkg/k8sd/controllers/node_label_test.go, src/k8s/pkg/k8sd/controllers/update_node_configuration.go, src/k8s/pkg/k8sd/controllers/utils.go, src/k8s/pkg/snap/util/dqlite.go, tests/integration/tests/test_node_availability_zone.py
Backports #989 and #1020 to add AZ support based on kubernetes topology labels.
=> [Backport 1.32] Set dqlite failure-domain based on the k8s node AZ label (#989) 

docs/canonicalk8s/capi/reference/configs.md
`cluster-config` does not have the correct indentation in the CAPI docs.
Indent the `cluster-config`.
https://github.com/canonical/k8s-snap/issues/1405
No
The PR title is expected to contain one of the following prefixes, following the
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/):
* feat: A new feature
* fix: A bug fix
* docs: Documentation only changes
* style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* refactor: A code change that neither fixes a bug nor adds a feature
* perf: A code change that improves performance
* test: Adding missing tests or correcting existing tests
* build: Changes that affect the …
=> docs: Fix indentation in CAPI reference page

tests/integration/tests/test_cilium_e2e.py
Currently, there are a few issues preventing the test from passing:
- `instance.exec(["bash", "-c", "k8s config > ~/.kube/config"])` results in k8s' help being saved into `~/.kube/config`, which causes the cilium binary to fail.
- 
- `instance.exec(["k8s", "status", "--wait-ready"])` fails with the error:
```
Error: Failed to retrieve the cluster status.
The error was: context deadline exceeded
```
- The error above is a timeout while waiting for it to become ready. The check is redundant, as we're already waiting for networking and dns to be ready.
This PR fixes the issues mentioned.
`release-1.32`
=> test: Fixes test_cilium_e2e test

docs/canonicalk8s/capi/reference/index.md
I just noticed that there is duplication of the Providers configurations section in the capi reference section.
Removed duplicate
N/A
The landing page rework was not back ported so no need to update 1.32. Need to update 1.33.
=> docs: remove duplicate section in reference landing page

docs/canonicalk8s/snap/explanation/security/auth.md, docs/canonicalk8s/snap/explanation/security/index.md
Adds an explanation page for the different authentication and authorization features present in Kubernetes.
N/A
=> docs: Adds explanation page for authentication and authorization

src/k8s/pkg/k8sd/app/hooks_join.go
Currently, when a control plane joins, and ``handleRollOutUpgrade`` returns an error, the node is then removed from the cluster. The reason for this failure is not logged, which makes it harder to debug.
Adds a log line for this scenario.
=> fix: Adds logging when rollout upgrade fails

src/k8s/pkg/snap/pebble.go, src/k8s/pkg/snap/pebble_test.go, src/k8s/pkg/snap/snap.go
The `Upgrade.k8sd.io` CRD has the following regex for its name:
```
[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*
```
However, if `snap.Revision()` would return an empty string, we'd create an resource with the name `cluster-upgrade-to-rev-`, which is invalid.
For pebble, we are returning `""`, and pebble is being used in `cluster-api-k8s`, which results in the following error:
```
[k8sd] E0507 145 app/hooks_join.go:273] "Failed to handle rollout-upgrade" err="failed to create upgrade: Upgrade.k8sd.io \"cluster-upgrade-to-rev-\" is invalid: metadata.name: Invalid value: \"cluster-upgrade-to-rev-\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', …
```
=> fix: Implement Revision for pebble

src/k8s/pkg/k8sd/app/hooks_join.go
When a second upgraded node joins the cluster, the ``Upgrade.k8sd.io`` object is updated. However, the updated ``upgrade.status`` object does not contain the ``strategy`` field, which is required. This leads to errors like this:
```
err="failed to patch upgrade status: Upgrade.k8sd.io \"cluster-upgrade-to-rev-foo\" is invalid: [status.phase: Required value, status.strategy: Required value]"
```
Patch existing `upgrade.status`.
`release-1.33`, `release-1.32`
=> fix: patch same upgrade status object

docs/canonicalk8s/charm/howto/install/install-terraform.md, docs/canonicalk8s/charm/reference/troubleshooting.md, docs/canonicalk8s/snap/reference/troubleshooting.md
Users have faced issues when there are other installations of cilium / other networking services also installed on the hose trying to use the default port for VXLAN encapsulation.
Now you can alter the default Cilium tunnel port through annotations but this is not in our docs yet
1.32, 1.33
=> docs: Update troubleshooting with cilium tunnel port fix 

tests/integration/tests/test_version_upgrades.py
The in-place upgrade test sets up 3 instances before it finds out it should skip the test.  Mark the test as skipped earlier.
=> test: skip feature upgrades inplace early

tests/integration/tests/test_util/config.py
Currently, the ``test_version_upgrades`` fails on previous release branches if ``TEST_VERSION_UPGRADE_CHANNELS`` is set to ``"recent N"``. The test is supposed to get a list of snap channels to test the upgrades.
However, by default, ``config.FLAVOR`` (``TEST_FLAVOR`` env var), is ``""``, and that flavor is used by ``snap.get_most_stable_channels`` to filter the snap channels. As it is empty, it creates an invalid regex:
```
(\d+)\.(\d+)-\/(stable|candidate|beta|edge)
```
This regex cannot match the snap channels we'd expect (e.g.: ``1.32-classic/stable``).
Sets ``config.FLAVOR`` to classic, as that's the currently supported version.
`release-1.33`, `release-1.32`.
=> test: Sets default FLAVOR to classic

tests/tics-scan.sh
Running `add-apt-repository -y ppa:dqlite/dev` may flake with a `504 Gateway Time-out` from Launchpad.
We may avoid this by adding the apt source lists manually.
`release-1.33`, `release-1.32`
The PR title is expected to contain one of the following prefixes, following the
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/):
=> ci: Add dqlite deb source lists manually for TICS job

docs/canonicalk8s/snap/howto/install/offline.md, snap/snapcraft.yaml, tests/integration/README.md, tests/integration/lxd/setup-image.sh, tests/integration/tests/test_util/config.py
Added `enable-patchelf` to build attributes to preserve old behavior since it is not enabled by default from core22+.
Updated references of core20 to core22.
=> feat: bump snap base to core22

.github/workflows/e2e-tests.yaml, .github/workflows/nightly-test.yaml, tests/integration/tox.ini
This PR does two things:
1. Spin up a job for each test which massively reduces our CI/PR testing time
2. Move to official Github runners instead of self-hosted runners
Notes:
* For normal PRs, we don't run the nightly tests so we *only* spin up ~15 jobs
* We could think about not doing this for our nightly runs since iteration speed is not critical in this scenario.
=> test: Run all tests in parallel on Github runners

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/snap/howto/install/dev-env.md
This PR adds a section to provide a troubleshooting steps when encountered with disk pressure error caused by insufficient space in custom containerd's state dir. This is a possible solution for #1456.
=> chore: update docs to address disk pressure troubleshooting

k8s/lib.sh, k8s/profiles/containerd, src/k8s/cmd/k8s/k8s_x_cleanup.go, src/k8s/pkg/k8sd/app/hooks_remove.go, src/k8s/pkg/k8sd/setup/containerd.go, src/k8s/pkg/snap/interface.go, src/k8s/pkg/snap/mock/mock.go, src/k8s/pkg/snap/snap.go, src/k8s/pkg/snap/util/cleanup/cleanup.go, src/k8s/pkg/snap/util/cleanup/internal/containerd_paths.go, src/k8s/pkg/snap/util/cleanup/internal/containerd_paths_test.go, src/k8s/pkg/snap/util/cleanup/internal/containers.go, src/k8s/pkg/snap/util/cleanup/internal/kube_proxy.go, src/k8s/pkg/snap/util/cleanup/internal/loop_devices.go, src/k8s/pkg/snap/util/cleanup/internal/loop_devices_test.go, src/k8s/pkg/snap/util/cleanup/internal/network_namespaces.go, src/k8s/pkg/snap/util/cleanup/internal/network_namespaces_test.go, src/k8s/pkg/snap/util/cleanup/internal/plugins.go, src/k8s/pkg/snap/util/cleanup/internal/plugins_test.go, src/k8s/pkg/snap/util/cleanup/internal/volume_mounts.go, src/k8s/pkg/snap/util/cleanup/internal/volume_mounts_test.go, src/k8s/pkg/snap/util/containerd.go, src/k8s/pkg/utils/mount/mock.go, src/k8s/pkg/utils/mount/mount.go, src/k8s/pkg/utils/mount/unix.go, src/k8s/pkg/utils/netns/mock.go, src/k8s/pkg/utils/netns/netns.go, src/k8s/pkg/utils/netns/unix.go
* moves cleanup logic from bash to go so it can be used both in snap hooks and k8sd hooks.
* adds the container cleanup step to remove hook before containerd paths are cleaned up
Fixes #1326 
`release-1.32`
`release-1.33`
=> fix: move cleanup code to go and handle custom containerd path

build-scripts/components/kubernetes/patches/default/0001-Increase-the-timeout-and-interval-for-populating-cac.patch, build-scripts/components/kubernetes/patches/v1.32.0/0001-Increase-the-timeout-and-interval-for-populating-cac.patch
We have seen that often the provisioning of pods is stuck with messages like:
```
Warning  FailedMount  2m50s (x169 over 5h33m)  kubelet  MountVolume.SetUp failed for volume "secret-cinderplugin" : failed to sync secret cache: timed out waiting for the condition
```
This indicates that the secret is not loaded in the cache quick enough.
We increase the timeout set for loading a secret.
This PR should be ported to 1.33 and main.
=> fix: patch k8s to relax the timeouts for populating resource caches

src/k8s/pkg/k8sd/app/app.go
Disabling the feature controller via a k8sd argument causes the daemon to crash.
We use the same argument to stop both the feature and update controller.
This is a fix only for 1.32. Future branches have this issue addressed.
=> fix: disable feature and update controllers on 1.32

src/k8s/pkg/k8sd/app/app.go
Disabling the feature controller via a k8sd argument causes the daemon to crash.
We use the same argument to stop both the feature and update controller.
This is a fix only for 1.33. Future branches have this issue addressed.
=> fix: disable feature and update controllers on 1.33

tests/integration/pytest.ini, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_util/util.py
The test_loadbalancer tests are flaky. This PR addresses some of the flakiness issues.
The following changes/fixes are introduced:
1. A pytest.ini is introduced so we see the LOG messages in the tests
2. The IP v6 test is set to run as part of this test because we have now transitioned main to Cilium 1.17
3. We enable the network and wait for it to some up before we start the loadbalancer (metallb). We wait for metallb to come up and then we configure it. The way we had it before there was a race condition that resulted in an error like this:
```
load-balancer:            Failed to deploy MetalLB, the error was: failed to enable LoadBalancer: failed to apply MetalLB LoadBalancer configuration: failed to upgrade metallb-loadbalancer: failed to create resource: Internal error occurred: …
```
=> fix: address test_loadbalancer flakiness

tests/integration/tests/test_clustering.py
Some flakiness may come from trying to join a node to a cluster that is not ready yet.
Wait for the cluster to get ready before joining nodes
Yes, 1.32 and 1.33
=> fix: address test_clustering flakiness

src/k8s/pkg/k8sd/app/hooks_join.go
Backport of https://github.com/canonical/k8s-snap/pull/1425 to ``release-1.32``.
=> fix: patch same upgrade status object [Backport release-1.32]

src/k8s/pkg/k8sd/app/hooks_join.go
Backport of https://github.com/canonical/k8s-snap/pull/1425 to ``release-1.33``.
=> fix: patch same upgrade status object [Backport release-1.33]

.github/workflows/lint_and_integration.yaml, tests/integration/tests/test_annotations.py
* We join a node to the cluster and immediately trigger a snap refresh.
At this point, the k8sd cluster reflects both nodes, but the k8s-dqlite cluster appears to be out of sync:
* On [node 1](https://github.com/canonical/k8s-snap/actions/runs/15565098315/job/43839259681? pr=1529#step:10:350), the newly joined node doesn't appear yet.
* On [node 2](https://github.com/canonical/k8s-snap/actions/runs/15565098315/job/43839259681?pr=1529#step:10:355), it is already registered.
* Then, k8s-dqlite is stopped due to the snap refresh, and this inconsistency seems to be persisted (visible in the [inspection reports](https://github.com/canonical/k8s-snap/actions/runs/15492797421/artifacts/3294837888) from the failed runs).
* After the refresh, k8s-dqlite restarts but fails to recover correctly, …
=> test: Fix annotation test

tests/integration/tests/test_version_upgrades.py
With the latest changes to reduce API server calls, `helm apply` is only called if necessary, and not all the time (like before).
Therefore, we can not rely on a Helm release to be updated necessarily after a feature reconciliation. This change prevents the tests from failing in case a release is not updated.
=> test(feature_upgrades): Don't expect updated helm releases

src/k8s/cmd/k8s/k8s_status.go, src/k8s/cmd/k8sd/k8sd.go, src/k8s/pkg/client/helm/client.go, src/k8s/pkg/k8sd/app/app.go, src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/app/provider.go, src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/k8sd/controllers/upgrade/controller.go, src/k8s/pkg/k8sd/controllers/upgrade/reconcile.go, src/k8s/pkg/snap/snap.go, tests/integration/pytest.ini, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
This PR aims to reduce the API server calls that are made by k8sd. Each commit corresponds to a specific improvement.
This PR also backports https://github.com/canonical/k8s-snap/pull/1537 which will fix the feature upgrades tests failure.
=> chore: [Backport 1.33] Reduce API server calls

src/k8s/pkg/snap/snap.go
In #1423, a pre-init check was introduced on the client-side. In this check, the k8s binaries are started to ensure they do not hang later. However, the output was printed to stdout causing e.g. the `k8s bootstrap` command to be polluted with debug messages.
This commit pipes the output into the void instead.
=> fix: Don't print k8s binary outputs in CLI

docs/canonicalk8s/charm/howto/custom-registry.md, docs/canonicalk8s/snap/howto/install/offline.md
Applicable spec: [KU167](https://docs.google.com/document/d/1FLAFY5DgYabJHM-D48qdgLJJy86wYtNa3MSKYC3qq2E/edit?tab=t.0)
Addresses documentation gap with respect to `override_path`
Updates both snap and charm documentation
=> docs: configure with containerd override_path

tests/integration/tests/test_util/util.py
Running `k8s get-join-token` right after `k8s bootstrap` may result in error in case microcluster state is not ready. This PR adds a retry logic to the `get_join_token` helper to account for such situations.
=> fix: add retry to get_join_token helper

docs/canonicalk8s/snap/howto/security/disa-stig-assessment.md, docs/canonicalk8s/snap/reference/ports-and-services.md
DISA STIG expects us to specify the set of ports, protocols and services use use.
With this PR we update the ports and services page and point the respective DISA STIG guidelines to it. 
Yes. To 1.32 and 1.32.
=> docs: update the ports and services page for DISA PPS

src/k8s/pkg/k8sd/features/cilium/network.go, src/k8s/pkg/utils/netlink.go
=> fix: update vxlan port check to ignore 0 unset or missing port number

docs/canonicalk8s/conf.py, docs/canonicalk8s/snap/howto/install/custom-worker.md
The previous example where the --name is set should only be used when the hostname cannot be resolved. It is not the default or recommended behaviour.
Replacing that example and reformatting the page.
Drive by fix : There is a huge amount of links in the DISA STIG how to guide for the same website (stigviewer) that often flake and give a false positive in our tests. By only checking 3 of the links (ones starting with V-25*) we should still be altered to broken links but not have the same stability issues
N/A
1.32,1.33
=> docs: Update custom worker join how to guide

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/charm/howto/ceph-csi.md
Document the usage of two additional features of ceph-csi charm
* the auto-creation of namespaces
* the disabling of the Ceph RBD drivers
Integration into the docs how to deploy/reconfigure ceph-csi for the charm proposed features.
* 1.33/stable of ceph-csi will support this feature
* No tests added as it only concerns documentation
=> docs: document Auto Namespace creation and RBD disable

build-scripts/components/kubernetes/patches/v1.34.0/0001-Increase-the-timeout-and-interval-for-populating-cac.patch, build-scripts/components/kubernetes/patches/v1.34.0/0001-allow-all-nodes-to-get-k8sd-config.patch, build-scripts/components/kubernetes/patches/v1.34.0/0001-single-kubernetes-binary.patch, build-scripts/components/kubernetes/patches/v1.34.0/0001-use-resolv.conf-file-with-non-loopback-nameservers.patch, build-scripts/components/kubernetes/patches/v1.34.0/0002-Allow-node-role-labels-on-kubelet-registration.patch
Our kubernetes patch has slightly changed for 1.34 k8s (cmd/kubectl/kubectl.go).
Updated patch.
NA
NA
=> fix: kubernetes 1.34 patches

src/k8s/pkg/k8sd/controllers/feature.go, src/k8s/pkg/utils/time/backoff.go
Helm `apply` of the feature reconciliations might get into a deadlock since feature controllers run independently.  For features that share the same underlying chart the situation is even more dire since there are `num_cp_nodes * num_sibling_features` goroutines that try to apply the same Helm chart. Applying the same Helm chart concurrently or in parallel might fail with `another operation is in progress`.
This PR introduces a jitter to the reconciliation retries in order to reduce the concurrent/parallel Helm operations.
=> fix: Introduce jitter to reconciliation retries

.github/workflows/charm-e2e-tests.yaml
Adding juju-crashdump the the charm-e2e tests
Running `tox -e integration` will create a crashdump of the model under test
Adding `juju-crashdump` for the controller is nice
Finally assemble all the crashdumps into a github artifact of tht ebuild
=> test: charm-e2e tests collect the juju crashdumps

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/snap/reference/ports-and-services.md
The VXLAN port is not in the list of ports and services
Add the VXLAN port in the list
1.32 and 1.33
=> docs: Add vxlan port in the list of ports and services

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/snap/reference/versions/1.32.md
We must keep our release notes up to date
Patch notices foe the snap updated for K8s version 1.32.6
N/A
1.32, 1.33
=> docs: Add patch notices for latest snap 

src/k8s/pkg/k8sd/app/hooks_join.go, src/k8s/pkg/k8sd/app/hooks_post_refresh.go, src/k8s/pkg/k8sd/app/hooks_start.go, src/k8s/pkg/k8sd/controllers/coordinator.go, src/k8s/pkg/k8sd/controllers/node_label.go, src/k8s/pkg/k8sd/controllers/upgrade/controller.go, src/k8s/pkg/k8sd/controllers/upgrade/reconcile.go, src/k8s/pkg/upgrade/upgrade.go, src/k8s/pkg/version/version.go, tests/integration/tests/test_version_upgrades.py
This PR implements a way to wait for the worker nodes in the upgrade process as well, before triggering the feature controllers.
We've introduced a `version.Data` struct that contains all the necessary information about the current version of the installed k8s-snap. The node label controller is responsible for annotating the node with this struct.
The upgrade controller will watch for this annotation and add the node name to the list of `upgradedNodes`.
Once all the nodes (including workers) are available in the `upgradedNodes` list, the upgrade controller will transition the upgrade phase from `NodeUpgrade` to `FeatureUpgrade`, triggering the feature controllers and proceeding with the upgrade.
=> feat(upgrade): Wait for worker nodes to get upgraded as well

snap/snapcraft.yaml
Launchpad builders do not have pip pre-installed, this makes sure python3-pip is installed which is required for etcd elf patching.
Related to #1649
=> fix: adds python3-pip to build-deps

.github/workflows/charm-e2e-tests.yaml
The charm tests introduced an dependency to uv that we need to ensure on the charm e2e test as well. https://github.com/canonical/k8s-snap/actions/runs/16438350077/job/46454442835?pr=1681
.
Only to 1.33 since we don't have that test for 1.32.
=> ci: Add tox-uv to charm test infra

src/k8s/pkg/k8sd/types/cluster_config_kubelet.go, src/k8s/pkg/k8sd/types/cluster_config_kubelet_test.go
This PR adds `control-plane-taints` to the k8sd config map to fix the RSA verification issue
Fixes:
https://github.com/canonical/k8s-operator/issues/601
=> fix: Include control-plane-taints in the k8sd configmap

docs/canonicalk8s/snap/explanation/high-availability.md, docs/canonicalk8s/snap/howto/install/uninstall.md, docs/canonicalk8s/snap/tutorial/add-remove-nodes.md
If you delete the snap before removing the node from the cluster, the node hangs and is unreachable in the cluster. 
There is work planned to fix this, but for now adding a warning to our docs on the importance of removing the node first
Reported on MM
1.32, 1.33
=> docs: Add node removal notice

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/index.md
We recently received some feedback on the layout and wording of our landing page could be misleading
Place the three docs sets (snap,capi,charm) side by side to not insinuate order 
Reword the cards to actually have some relevant info
N/A
1.32, 1.33
=> docs: update homepage docset descriptions

docs/canonicalk8s/snap/reference/inspection-reports.md, k8s/scripts/inspect.sh
Add etcd service to inspection reports
Adds another service to the list to be inspected
* 1.32
* 1.33
No code changes needing unit/integration tests
=> feat: Included managed-etcd service inspection

docs/canonicalk8s/snap/tutorial/getting-started.md, docs/canonicalk8s/snap/tutorial/kubectl.md
Improve the experience of users going through our tutorials.
Having the options after the default bootstrap config option was confusing to users. 
Waiting for the pvc to delete was taking a while and confusing users so added a disclaimer.
Removed numbering from the kubectl tutorial. 
Tried to continue the tutorial by linking to the next adding/removing nodes tutorial.
N/A
1.32, 1.33
=> docs: Based on user feedback, update the tutorials

.github/workflows/charm-e2e-tests.yaml
While reviewing #1726, i spotted an error with the charm-e2e-test
https://github.com/canonical/k8s-snap/actions/runs/16804748815/job/47595805069?pr=1726
Provide unique gh artifact names so any juju-crashdump can be uploaded
I'm not sure @canonical/kubernetes where else should it go?
=> fix: Make charm-e2e-test artifacts uniquely named

.github/workflows/weekly-test.yaml, tests/integration/tests/conftest.py, tests/integration/tests/test_restart.py, tests/integration/tests/test_util/etcd.py, tests/integration/tests/test_util/harness/base.py, tests/integration/tests/test_util/harness/juju.py, tests/integration/tests/test_util/harness/lxd.py, tests/integration/tests/test_util/harness/multipass.py, tests/integration/tests/test_util/registry.py
The multipass tests were failing because rebooting needs to happen via `multipass restart` instead of an `sudo reboot` from within the instance. See https://github.com/canonical/k8s-snap/actions/runs/16878895760/job/47819464883?pr=1702
* Refactored the reboot and delete functions to call the underlying harness function to restart/delete an instance
* Renamed reboot to restart to match lxd/multipass naming conventions
=> test: Make instance restart harness-dependent

k8s/scripts/inspect.sh, tests/integration/tests/test_version_upgrades.py
* Collects upgrade resources in inspection reports.
* Solve the following issue in the upgrade tests by preventing multiple refreshes on the worker nodes:
```
Jul 26 00:19:57 k8s-integration-2-ae8a84 k8s.k8sd[6402]: I0726 00:19:57.167245    6402 upgrade/reconcile.go:83] "Reconciling node version." logger="k8sd.controller-coordinator" node="k8s-integration-5-8ce294" version="x2"
Jul 26 00:19:57 k8s-integration-2-ae8a84 k8s.k8sd[6402]: I0726 00:19:57.167284    6402 upgrade/reconcile.go:89] "No upgrade found for revision, skipping reconciliation." logger="k8sd.controller-coordinator" node="k8s-integration-5-8ce294" revision="x2"
```
=> chore: Collect upgrades in inspection report, Fix feature upgrades test

.github/workflows/charm-e2e-tests.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/weekly-test.yaml, tests/integration/templates/cloud-init/ubuntu-pro-fips-stig-jammy.yaml, tests/integration/templates/cloud-init/ubuntu-pro-fips-stig-noble.yaml, tests/integration/tests/conftest.py, tests/integration/tests/performance/test_perf_clustering.py, tests/integration/tests/test_airgapped.py, tests/integration/tests/test_annotations.py, tests/integration/tests/test_cleanup.py, tests/integration/tests/test_clustering_dqlite.py, tests/integration/tests/test_external_certificates.py, tests/integration/tests/test_loadbalancer.py, tests/integration/tests/test_node_availability_zone.py, tests/integration/tests/test_strict_interfaces.py, tests/integration/tests/test_util/harness/multipass.py, tests/integration/tests/test_util/registry.py, tests/integration/tests/test_util/util.py, tests/integration/tests/test_version_upgrades.py
Extends the weekly FIPS tests to run on DISA STIG compliant multipass machines. 
* Added a cloud-init configuration for jammy and noble to setup and configure FIPS & DISA STIG. Some STIG rules are skipped as they would block communication between host and multipass VM 
* Added a `required_ports` marker to specify ports that need to be open for tests.
=> ci: Add DISA STIG compliant runners

.github/workflows/lint_and_integration.yaml
Adds necessary security scan permissions to lint-and-integration workflow, thanks to @addyess derived from #1749 
`release-1.32`
`release-1.33`
=> chore: add security-events to integration workflow

docs/canonicalk8s/snap/howto/security/cis-assessment.md
This PR updates the CIS hardening guides in documentation to take into effect the steps needed for the new etcd datastore. A similar PR for DISA STIG will be introduced as a follow up. 
`release-1.32`
`release-1.33`
=> docs: CIS etcd updates

docs/canonicalk8s/.sphinx/.wordlist.txt, docs/canonicalk8s/assets/arch.dsl, docs/canonicalk8s/assets/example-bootstrap-config.yaml, docs/canonicalk8s/assets/k8s-container.puml, docs/canonicalk8s/assets/k8sd-component.puml, docs/canonicalk8s/capi/howto/troubleshooting.md, docs/canonicalk8s/capi/reference/configs.md, docs/canonicalk8s/charm/howto/etcd.md, docs/canonicalk8s/charm/howto/install/install-custom.md, docs/canonicalk8s/charm/howto/troubleshooting.md, docs/canonicalk8s/snap/explanation/architecture.md, docs/canonicalk8s/snap/explanation/clustering.md, docs/canonicalk8s/snap/explanation/security/crypto.md, docs/canonicalk8s/snap/howto/external-datastore.md, docs/canonicalk8s/snap/howto/security/refresh-certs.md, docs/canonicalk8s/snap/howto/troubleshooting.md, docs/canonicalk8s/snap/reference/architecture.md, docs/canonicalk8s/snap/reference/certificates.md, docs/canonicalk8s/snap/reference/dqlite.md, docs/canonicalk8s/snap/reference/etcd.md, docs/canonicalk8s/snap/reference/index.md, docs/canonicalk8s/snap/reference/inspection-reports.md, docs/canonicalk8s/snap/reference/ports-and-services.md
Updates the documentation to use etcd instead of dqlite as the default datastore in various places. Note that this PR does not contain the updates of the CIS/STIG compliance. I will address this in a separate PR.
Requires backport since etcd is also backported
=> docs: Replace k8s-dqlite with etcd

src/k8s/pkg/k8sd/app/hooks_start.go
This PR kicks k8sd to reconcile feature on start up to make sure features are reconciled even after an unfortunate k8sd restart.
=> feat: Trigger feature controller on k8sd startup

docs/canonicalk8s/charm/reference/troubleshooting.md
Updates troubleshooting guide for the charms to handle the change preventer on `bootstrap-` charm options.
* Updates the troubleshooting guide with examples of the failure.
* Links to charm-configuration page
Should this PR be backported? If so, to which release? likely 1.33
=> docs: UX adjustments around blocked units on bootstrap change prevention

docs/canonicalk8s/capi/howto/intermediate-ca.md
Renames a secret used in the examples for CAPI and Intermediate CA Secret
Should this PR be backported? If so, to which release? Not sure?
=> docs: fix mistake in example intermediate ca Secret

docs/canonicalk8s/capi/reference/configs.md
This PR fixes a typo in the CAPI docs so that the `files` field will represent an array.
Fixes:
- https://github.com/canonical/k8s-snap/issues/1765
=> docs(CAPI): Fix files field to represent an array

src/k8s/pkg/client/kubernetes/endpoints.go, src/k8s/pkg/client/kubernetes/endpoints_test.go, src/k8s/pkg/proxy/endpoints.go, src/k8s/pkg/utils/endpoints.go, src/k8s/pkg/utils/endpoints_test.go
Switch from deprecated `Endpoints` to `EndpointSlice` for fetching IPs of apiservers
`release-1.33`
`release-1.34`
=> refactor: use EndpointSlice instead of deprecated Endpoints

build-scripts/hack/update-component-versions.py
Prevent the auto-component job from stepping outside of minor versions of helm and k8s
Pins the sources
=> fix: [Release 1.34] Pin to minor versions of k8s and helm

k8s/lib.sh, snap/hooks/configure
We've disabled certain feature gates in 1.34 #1790 via setting `Gate=False` in the apiserver arguments for `k8s-dqlite` backed cluster. On revert/downgrade these flags were not sanitized since they reside in `SNAP_COMMON` which results in the kube-apiserver crashing.
Sanitizes feature gates that do not exist on the current kbuernetes version
=> fix: sanitize not-applicable feature gates in configure hook

.github/workflows/e2e-tests.yaml
Switches the tests that are failing with out of disk error to self-hosted runners. A follow-up work to figure out if we can improve these tests to consume less resources is in order.
=> chore: switch disk related failing tests to self-hosted runners

.github/workflows/nightly-test.yaml, tests/integration/tests/test_clustering.py
This PR introduces more test cases on our nightly CI to test membership operations under more conditions: (parallel joins/removals, mixed join and removal operations) as well as disruptions such as snap restarts.
=> ci: add more clustering test cases

docs/canonicalk8s/.custom_wordlist.txt, docs/canonicalk8s/charm/howto/install/install-terraform.md, docs/canonicalk8s/charm/howto/upgrade-minor.md, docs/canonicalk8s/charm/reference/releases.md, docs/canonicalk8s/charm/reference/versions/1.33.md
This PR adds 1.33 charm release notes and updates instructions to point to this version.
Should be backported to `release-1.33` and `release-1.34`
=> docs: Add 1.33 charm release notes
