README.md

Update the readme to reflect the current status

Minor README updates to make it more accurate

---

src/k8s/cmd/k8sd/k8sd.go
src/k8s/pkg/k8sd/app/app.go
src/k8s/pkg/k8sd/database/kubernetes_auth_tokens_test.go
src/k8s/pkg/k8sd/database/util_test.go

Add machinery so that we can write simple tests against the microcluster database

Add WithDB() test helper for writing database tests

---

src/k8s/pkg/k8sd/api/component.go

This pull request refactors the validation logic for received component statuses and ensures the return of correct responses in such cases.

Refactor Component Status Validation Logic

---

tests/e2e/tests/test_cilium_e2e.py

Use `k8s enable dns` now that it's ready #55

use k8s enable dns for the cilium e2e tests

---

docs/tools/.readthedocs.yaml

Now the docs structure works and the rtd site is setup,  we need to add the config YAML to automatically update the docs site
For the moment, the published docs are marked private until they are more complete

add rtd yaml config for docs

---

docs/src/explanation/about.md
docs/src/tutorial/getting-started.md
docs/tools/.readthedocs.yaml

- uppdate rtd yaml file so build works
- add some dummy files for sections to suppress warnings
NB this is tested and working on RTD

Rtd tweaks

---

.github/workflows/strict.yaml

Set commit identity for CI updating strict branch 

---

build-scripts/components/helm/version.sh

bump helm binary version to 3.14.1

---

src/k8s/cmd/k8s/k8s_enable_gateway.go
src/k8s/cmd/k8s/k8s_helm.go
src/k8s/cmd/k8s/k8s_kubectl.go
src/k8s/pkg/k8s/client/cluster_node.go
src/k8s/pkg/k8sd/api/endpoints.go
src/k8s/pkg/k8sd/api/worker_access_handler.go
src/k8s/pkg/k8sd/app/hooks_bootstrap.go
src/k8s/pkg/k8sd/setup/directories.go
src/k8s/pkg/snap/interface.go
src/k8s/pkg/snap/mock/mock.go
src/k8s/pkg/snap/snap.go
src/k8s/pkg/snap/util/node.go
src/k8s/pkg/utils/file.go
src/k8s/pkg/utils/file_test.go

Added an AccessHandler that restricts certain endpoints to workers.
Also fixed a typo on the Gateway components enable message.

Restrict control plane actions on worker nodes

---

docs/src/explanation/channels.md
docs/src/explanation/index.md
docs/src/howto/index.md
docs/src/howto/install/index.md
docs/src/howto/install/multipass.md
docs/src/howto/install/snap.md
docs/src/index.md
docs/src/reference/releases.md

Pages added:
- installing index (stub)
- Installing from a snap (complete)
- Installing with multipass (stub)
- explanation/channels

Add installing info

---

docs/src/howto/index.md
docs/src/howto/storage.md

Provides a step by step guide on how to enable, configure and disable the storage component.

Add storage how-to documentation

---

docs/src/assets/roadmap.csv
docs/src/reference/index.md
docs/src/reference/roadmap.md

There isn't a lot to say here at the moment.
The table is sourced from a simple CSV file to make it easier to update and/or source from elsewhere

Docs: Add roadmap

---

build-scripts/components/helm/version.sh

Bump helm to v3.14.2, sister PR of #150

bump helm to 3.14.2

---

docs/src/howto/install/multipass.md

Adds the install on Multipass page

Multipass install

---

CODE_OF_CONDUCT.md
src/k8s/pkg/k8sd/api/cluster_tokens.go

Functionality to return the existing join-tocken when the `get-join-token` command is re-run.

Get or create join tocken on get-join-token

---

docs/src/tutorial/add-remove-nodes.md

Add remove-node to the add-remove-nodes tutorial. Make sure the user is warned about nuking things.
Preview:

add remove node section

---

src/k8s/pkg/k8sd/api/cluster_config.go

Added validations for config options for `k8s set` operations

Added validations for config options for `k8s set`

---

docs/src/howto/install/index.md
docs/src/howto/install/lxd.md

Heavily inspired by: https://microk8s.io/docs/install-lxd

Docs: Add installing on LXD section

---

src/k8s/go.mod
src/k8s/go.sum
src/k8s/pkg/k8sd/app/hooks_bootstrap.go
src/k8s/pkg/k8sd/app/hooks_join.go
src/k8s/pkg/k8sd/setup/containerd.go
src/k8s/pkg/k8sd/setup/containerd_test.go
src/k8s/pkg/k8sd/types/cluster_config.go

Add machinery to configure containerd registries and mirrors

Machinery to configure containerd registry auths and mirrors

---

docs/src/howto/index.md
docs/src/index.md
docs/src/reference/index.md

Updating descriptions and links, fixing a few typos

index page updates

---

src/k8s/pkg/k8s/client/client.go
src/k8s/pkg/k8s/client/cluster.go
src/k8s/pkg/k8s/client/cluster_node.go
src/k8s/pkg/k8s/client/interface.go
src/k8s/pkg/k8s/client/mock/mock.go

Minor PR to clean things up about how we use the snap interface from the k8sd client.

tidy usage of snap in k8sd client code

---

docs/src/assets/ck-cluster.puml
docs/src/explanation/clustering.md
docs/src/explanation/index.md

Documentation explanation page for Clustering in `k8s`

[DOCS] Add Clustering Explanation

---

docs/src/_parts/components.md
docs/src/explanation/channels.md
docs/src/howto/contribute.md
docs/src/howto/install/charm.md
docs/src/howto/install/lxd.md
docs/src/howto/install/multipass.md
docs/src/howto/install/snap.md
docs/src/howto/networking/default-dns.md
docs/src/howto/networking/default-ingress.md
docs/src/howto/networking/default-network.md
docs/src/howto/storage.md
docs/src/reference/community.md
docs/src/tutorial/add-remove-nodes.md
docs/src/tutorial/getting-started.md
docs/src/tutorial/kubectl.md
docs/tools/custom_conf.py

Adds the contributing page (code and docs). This can be expanded significantly, probably split into 2 pages eventually, but this is just to get started.
also
- make correct links from other docs
- change sphinx to default to no highlight
- remove wrong styling from various codeblocks

KU-442-contributing

---

docs/src/howto/contribute.md

adds a link and uses the correct lxd container name

small doc fixes for contribs

---

src/k8s/api/v1/kubernetes_auth_tokens.go
src/k8s/api/v1/tokens.go
src/k8s/cmd/k8s/k8s_config.go
src/k8s/cmd/k8s/k8s_generate_auth_token.go
src/k8s/cmd/k8s/k8s_get_join_token.go
src/k8s/cmd/k8s/k8s_join_cluster.go
src/k8s/cmd/k8s/k8s_local_node_status.go
src/k8s/cmd/k8s/k8s_remove_node.go
src/k8s/cmd/k8s/k8s_revoke_auth_token.go
src/k8s/cmd/util/environ.go
src/k8s/pkg/k8s/client/client.go
src/k8s/pkg/k8s/client/cluster.go
src/k8s/pkg/k8s/client/cluster_config.go
src/k8s/pkg/k8s/client/cluster_node.go
src/k8s/pkg/k8s/client/interface.go
src/k8s/pkg/k8s/client/kubernetes_auth_tokens.go
src/k8s/pkg/k8s/client/mock/mock.go
src/k8s/pkg/k8s/client/node.go
src/k8s/pkg/k8s/client/tokens.go
src/k8s/pkg/k8sd/api/cluster_tokens.go
src/k8s/pkg/k8sd/api/kubernetes_auth_tokens.go

Refactor and cleanup some of the pkg/k8s/client
- Update the client interface to use the API request structs where possible
- Rename some structs to match the API requests
- Update error messages to be consistent

refactor and cleanup pkg/k8s/client

---

src/k8s/cmd/k8s/k8s_status.go
src/k8s/pkg/k8s/client/cluster.go
src/k8s/pkg/k8s/client/interface.go
src/k8s/pkg/k8s/client/mock/mock.go
src/k8s/pkg/k8sd/api/impl/k8sd.go
src/k8s/pkg/k8sd/app/hooks_bootstrap.go
src/k8s/pkg/k8sd/app/hooks_join.go
src/k8s/pkg/utils/k8s/status.go
src/k8s/pkg/utils/k8s/status_test.go

Moved status checks to server side, refactored getting nodes and checking cluster status to reduce code duplication

k8s status fixes

---

docs/src/howto/networking/default-loadbalancer.md
docs/src/howto/networking/index.md

I originally wrote a much larger doc but I have stripped all that content out and will save for an explanation page (we should also cover using external load-balancers first before adding that.
So, this is fairly straightforward.

Load-balancer how to

---

README.md

Adds the "Get it from the snap store" banner to the README

Add snap banner

---

src/k8s/go.mod
src/k8s/go.sum
src/k8s/pkg/component/dns.go
src/k8s/pkg/component/gateway.go
src/k8s/pkg/component/ingress.go
src/k8s/pkg/component/loadbalancer.go
src/k8s/pkg/k8sd/api/cluster_bootstrap.go
src/k8s/pkg/k8sd/api/cluster_config.go
src/k8s/pkg/k8sd/api/cluster_join.go
src/k8s/pkg/k8sd/app/hooks_bootstrap.go
src/k8s/pkg/k8sd/app/hooks_start.go
src/k8s/pkg/k8sd/controllers/node_configuration.go
src/k8s/pkg/k8sd/controllers/node_configuration_test.go
src/k8s/pkg/k8sd/types/node_config.go
src/k8s/pkg/utils/control/retry.go
src/k8s/pkg/utils/k8s/client.go
src/k8s/pkg/utils/k8s/configmap_test.go
tests/integration/tests/test_clustering.py
tests/integration/tests/test_config_propagation.py
tests/integration/tests/test_util/util.py

Added unit and integration test for node config propagation, follow up on #258

Added unit and integration test for node config propagation

---

build-scripts/hack/generate-sbom.py

Extend the SBOM archive with links and commit hashes of the rocks we use

Extend sbom archive with rock repos

---

docs/src/assets/charms-architecture.puml
docs/src/reference/architecture.md

* Includes documentation of the overview of the charm architecture
* Includes a diagram of users and interactions within the charm model

Create Charm Architecture Reference

---

docs/src/assets/arch.dsl
docs/src/assets/overview.puml

This pull request improves the language in the Overview diagram.
- Remove redundant description on the roles.
- Added relation between the cluster administrator and the charmed environment.
- Improved the language in the Overview diagram descriptions.
Resolves #266, resolves #268

Improve relationship and language in Overview diagram

---

.github/workflows/scorecard.yaml

This PR adds OSSF Scorecard.
Scorecard at: https://securityscorecards.dev/viewer/?uri=github.com/canonical/k8s-snap

Add OSSF Scorecard

---

src/k8s/pkg/k8sd/pki/load.go

Handle both RSA PRIVATE KEY (PKCS#1) and PRIVATE KEY (PKCS#8) blocks for rsa keys. We still require the presence of an RSA private key.
@mateoflorido

pki: handle both RSA PRIVATE KEY and PRIVATE KEY

---

src/k8s/api/v1/types.go
src/k8s/pkg/component/loadbalancer.go
src/k8s/pkg/k8sd/api/cluster_remove.go

Mini-PR to: supress a tics violation when writing to string buffer, add one error check, lower-cap one error.

Address TICS violations

---

docs/src/tutorial/add-remove-nodes.md

Specify where to run the token command

---

src/k8s/api/v1/bootstrap_config_test.go
src/k8s/api/v1/cluster_config.go
src/k8s/cmd/k8s/k8s_bootstrap_test.go
src/k8s/cmd/k8s/k8s_get.go
src/k8s/cmd/k8s/k8s_set.go
src/k8s/cmd/k8s/testdata/bootstrap-config-full.yaml
src/k8s/pkg/component/storage.go
src/k8s/pkg/k8sd/types/cluster_config_convert.go
src/k8s/pkg/k8sd/types/cluster_config_convert_test.go
src/k8s/pkg/k8sd/types/cluster_config_defaults.go
src/k8s/pkg/k8sd/types/cluster_config_defaults_test.go
src/k8s/pkg/k8sd/types/cluster_config_features.go
src/k8s/pkg/k8sd/types/cluster_config_merge.go
src/k8s/pkg/k8sd/types/cluster_config_merge_test.go

Replace the Local Storage `set-default` config occurrences to `default`.

Change Local Storage `set-default` to `default`

---

docs/src/assets/charm-arch.dsl

Add Charm Architecture DSL to the docs assets

Add Charm Architecture DSL

---

src/k8s/pkg/k8sd/api/cluster.go

Prevent panics in `GET /k8sd/cluster` if node is not yet initialized. This is a regression caused as a side-effect of https://github.com/canonical/k8s-snap/pull/257/files#diff-86fdc39de0c5dec676bb358c40f6de2447b0f4c4570315906d9b1c0e6e2b50eaR11-R19
Also perform some more cleanup in the code (do not retrieve the cluster config twice).

fix GET /k8sd/cluster panic when not initialized

---

src/k8s/pkg/utils/k8s/configmap.go

[WIP] fix busy loop in node config controller

---

src/k8s/api/v1/bootstrap_config.go
src/k8s/api/v1/bootstrap_config_test.go
src/k8s/api/v1/cluster_config.go
src/k8s/cmd/k8s/k8s_bootstrap_test.go
src/k8s/cmd/k8s/k8s_get.go
src/k8s/cmd/k8s/k8s_set.go
src/k8s/cmd/k8s/k8s_status.go
src/k8s/cmd/k8s/testdata/bootstrap-config-full.yaml
src/k8s/pkg/k8sd/types/cluster_config_convert.go
src/k8s/pkg/k8sd/types/cluster_config_convert_test.go

Put cloud-provider in ClusterConfig, so it can get set on k8s bootstrap.

Set Cloud provider on bootstrap

---

src/k8s/api/v1/bootstrap_config.go
src/k8s/api/v1/join_config.go
src/k8s/pkg/k8sd/app/hooks_bootstrap.go
src/k8s/pkg/k8sd/app/hooks_join.go

We are missing fields to provide custom certificates for the Front Proxy Client certs. This pull request introduces the necessary fields in the respective bootstrap and join config structs.

Add FrontProxy Client Custom Certificates

---

docs/src/snap/howto/external-datastore.md
docs/src/snap/howto/index.md

Add How-To for using an external etcd datastore

Add How-To for using an external etcd datastore

---

src/k8s/pkg/k8sd/app/hooks_start.go

do not panic if no public key is set

---

src/k8s/pkg/k8sd/pki/load.go

do not panic if reading invalid RSA public key

---

docs/src/charm/reference/charms.md
docs/src/charm/reference/index.md

Adds links to the charm store pages and source repo for the K8s charms

Add charm reference

---

docs/src/snap/reference/releases.md

Adds some release notes to fill a hole where some release notes should be. We can/will obviously update this when there is a release to note.

Add some preview release notes

---

.github/workflows/update-versions.yaml

Workflow checks upstream repositories for new versions under the same major and creates a PR with the newest version.

Add update part versions workflow

---

docs/src/charm/index.md
docs/src/charm/tutorial/getting-started.md

Some caveats:
- It's difficult to achieve  anything without storage ( I don't want to hack local-storage)
- It currently ends rather abruptly - suggestions welcome on how to finish it off

Add tutorial for charm deployment

---

.github/ISSUE_TEMPLATE/create_release_branch.md

References #383 
- Ensure that the checklist includes making the snaps build automatically on new commits

release-1.xx should be set to build automatically

---

.github/ISSUE_TEMPLATE/create_release_branch.md
.github/workflows/go.yaml
.github/workflows/integration.yaml
.github/workflows/python.yaml
.github/workflows/sbom.yaml
.github/workflows/strict-integration.yaml
.github/workflows/strict.yaml

Backport #411 to the `release-1.30` branch

[Backport 1.30] use `autoupdate/release-1.xx-strict` branches for strict (#411)

---

.github/workflows/update-components.yaml

use PAT so that CI is triggered

---

.github/workflows/go.yaml
.github/workflows/integration.yaml
.github/workflows/python.yaml
.github/workflows/sbom.yaml
.github/workflows/strict-integration.yaml
.github/workflows/update-components.yaml

Make sure to trigger CI when autoupdating release branches

---

.github/workflows/update-components.yaml

Attempt to fix https://github.com/canonical/k8s-snap/actions/runs/9120127554/job/25077097373

attempt to fix components gha

---

.github/workflows/go.yaml
.github/workflows/integration.yaml
.github/workflows/python.yaml
.github/workflows/sbom.yaml
.github/workflows/strict-integration.yaml

Attempt to fix missing CI in PRs like #428

attempt to fix missing CI on release branches component upgrades

---

src/k8s/pkg/k8sd/database/cluster_config.go

Improve relevant context added to the error message

update error message when merging config fails

---

.github/ISSUE_TEMPLATE/feature_request.md

KU-584/feature-req-template

---

.github/workflows/strict-integration.yaml
.github/workflows/strict.yaml
.github/workflows/update-components.yaml

Harden CI follow up

---

src/k8s/pkg/k8sd/types/cluster_config_convert.go
src/k8s/pkg/k8sd/types/cluster_config_convert_test.go
tests/integration/tests/test_control_plane_taints.py
tests/integration/tests/test_util/util.py

Cherry-pick f4fd0e35ac7ee369c9c40213c9cf820b8a2ebe1d into 1.30 release

Copy control-plane taint from bootstrap config (#425)

---

.github/workflows/go.yaml

Backport #435 to release-1.30 branch

[release-1.30] Drop code coverage comment (#435)

---

src/k8s/pkg/k8sd/setup/containerd.go

Use `ghcr.io/canonical/k8s-snap/pause:3.10` as pause image

update pause image to ghcr.io/canonical/k8s-snap/pause:3.10

---

.github/.jira_sync_config.yaml

Add jirasync config

---

docs/src/snap/tutorial/kubectl.md

Fixes linting issues that pop up in contributor PR: https://github.com/canonical/k8s-snap/pull/463/files

Update kubectl documentation links

---

docs/src/snap/tutorial/add-remove-nodes.md

Fixes error in multipass instance removal

docs: Update add-remove-nodes.md

---

src/k8s/cmd/k8s/k8s_kubectl.go
src/k8s/pkg/client/kubernetes/node.go
src/k8s/pkg/k8sd/app/hooks_join.go

Typos and go doc fixes

---

docs/src/charm/reference/architecture.md
docs/src/snap/howto/install/lxd.md

The lxd profile does not use the autostart config anymore.

Remove obsolete docs

---

.github/workflows/fast-forward.yaml

Followup fixes from #531, addressing failures from https://github.com/canonical/k8s-snap/actions/runs/9838898547/job/27159780004

Adjustments for fast-forward PR job

---

docs/proposals/002-refresh-certificates.md

Add proposal for implementing certificate refreshes for control plane and worker nodes for k8s-snap

Proposal 002: Certificate refreshes

---

docs/proposals/000-template.md
docs/proposals/001-k8s-status.md

Add formal feature proposal template, and proposal for improving the output of `k8s status` command.

Proposal 001: Expose feature status in `k8s status` command

---

tests/integration/tests/test_smoke.py

This PR addresses [this discussion](https://github.com/canonical/k8s-snap/pull/563#discussion_r1697088845)

Update k8s status integration test

---

tests/integration/tests/test_smoke.py

Somehow this was dropped between #570 and #571

missing "util" import

---

src/k8s/pkg/k8sd/app/hooks_remove.go

Fix a minor issue in the DeleteNode log

Fix DeleteNode log

---

src/k8s/pkg/k8sd/controllers/feature.go

After trying to apply a feature configuration, make sure to update the feature status on both failure and success.

Update status on failed apply

---

src/k8s/pkg/k8sd/app/hooks_remove.go

On failed `bootstrap` and `join-cluster` commands, the `PreRemove` hook will be called by microcluster. In some scenarios if the Database is not initialized, we get stuck in the `control.WaitUntilReady` loop indefinitely and the command fails with `context deadline exceeded`. We set a fixed number of retries to hopefully prevent this from happening, continue with the cleanup and show the user the actual error.
let's say we have `cp1` which is bootstrapped, we get a token with `get-join-token` but we don't specify any node name. running `k8s join-cluster <token>` on `cp2` should result in an error according to microcluster v2 but right now, the user is hanged for a long time and after that will see this (by default after ~2 mins):
```text
root@cp2:~# k8s join-cluster <token>
Joining the …
```

Prevent hang and show correct error on bootstrap and join-cluster

---

docs/src/snap/howto/index.md
docs/src/snap/howto/refresh-certs.md

This pull request introduces a how-to guide for refreshing certificates in a Canonical Kubernetes cluster.

Add How-to Refresh Certificates

---

docs/src/snap/howto/dualstack.md
docs/src/snap/howto/index.md
docs/src/snap/howto/networking/dualstack.md

This PR adds the dual-stack documentation page.

Add dualstack documentation page

---

docs/src/capi/reference/annotations.md
docs/src/capi/reference/index.md
docs/src/snap/reference/annotations.md
docs/src/snap/reference/index.md

Add a reference page for annotations on CAPI and the `k8s-snap`

Add annotations docs

---

build-scripts/hack/generate-sbom.py
build-scripts/hack/update-component-versions.py

Creation of Release 1.31 branch as a part of https://github.com/canonical/k8s-snap/issues/666

Release 1.31

---

src/k8s/pkg/k8sd/features/localpv/chart.go
src/k8s/pkg/k8sd/features/localpv/localpv.go
src/k8s/pkg/k8sd/features/localpv/localpv_test.go
src/k8s/pkg/k8sd/features/localpv/register.go

This PR adds unit tests for local storage.

Add unit tests for local storage

---

docs/src/snap/explanation/epa.md
docs/src/snap/explanation/index.md

This adds the EPA explanation
I will add links from here when the HowTo parts are complete

Add epa explanation docs

---

src/k8s/pkg/k8sd/features/metrics-server/metrics_server_test.go

Metrics Server feature lacks unit test this PR implements tests for Metrics Server functionality. 
KU-1515

Unit tests for Metrics Server k8sd feature

---

src/k8s/pkg/k8sd/setup/k8s_apiserver_proxy_test.go
src/k8s/pkg/k8sd/setup/kube_apiserver_test.go

I merged #697 after merging #698 without rebasing. This caused a conflict as the function signature changed.

Fix IPv6 unittests

---

README.md

Tackling the hard problems here... :)

Bump Kubernetes version

---

docs/src/snap/howto/cis-hardening.md
docs/src/snap/howto/index.md

Adding how-to guide for CIS hardening and auditing

Ku 1442 cis hardening

---

.golangci.yml
src/k8s/pkg/docgen/godoc.go
src/k8s/pkg/k8sd/features/calico/internal.go
src/k8s/pkg/k8sd/features/contour/ingress.go
src/k8s/pkg/utils/mapstructure.go

There were a bunch of type assertions that were based on trust and prayers.
Let's validate the type before dereferencing some random pointers.

Enable type assertions check

---

docs/src/capi/howto/index.md
docs/src/capi/howto/refresh-certs.md

Add a how-to guide on refreshing certificates with Cluster API.

Add How-To Refresh Certificates (CAPI)

---

build-scripts/hack/generate-sbom.py

Temporary fix for sbom generation for metrics-server

Temporary fix for sbom generation for metrics-server

---

docs/src/_parts/bootstrap_config.md
src/k8s/go.mod
src/k8s/go.sum
src/k8s/pkg/k8sd/controllers/csrsigning/config.go
src/k8s/pkg/k8sd/controllers/csrsigning/reconcile_test.go
src/k8s/pkg/k8sd/features/calico/network_test.go
src/k8s/pkg/k8sd/features/metrics-server/metrics_server_test.go

Depends on https://github.com/canonical/k8s-snap-api/pull/16

Remove hardcoded annotations

---

.github/workflows/integration-informing.yaml

Remove strict testing from PRs until it is re-prioritized and ready.

Remove strict testing from PRs

---

docs/src/assets/how-to-cloud-storage-aws-ccm.yaml
docs/src/snap/howto/storage/cloud.md
docs/src/snap/howto/storage/index.md

This document explains how to use cloud storage with the standalone k8s snap. At the end of the document, the user is able to deploy a pod that uses EBS volumes for storage.

[Docs] How to use cloud storage

---

docs/src/_parts/bootstrap_config.md

Reverts canonical/k8s-snap#807

Revert "Fix formatting and update documentation after merge"

---

docs/src/capi/tutorial/getting-started.md
docs/src/charm/tutorial/getting-started.md
docs/src/snap/tutorial/add-remove-nodes.md
docs/src/snap/tutorial/getting-started.md
docs/src/snap/tutorial/kubectl.md

reviewed tutorials and edited them to make them clearer, fix md linter issues and formatting

[Docs] tutorials review

---

src/k8s/pkg/k8sd/app/hooks_remove.go

Only log worker marker file error if exists

---

docs/canonicalk8s/custom_conf.py
docs/canonicalk8s/index.md
docs/src/capi/index.md
docs/src/charm/index.md
docs/src/snap/explanation/about.md
docs/src/snap/howto/install/offline.md
docs/src/snap/index.md
docs/src/snap/reference/community.md

Updating broken links
Release notes changes in PR #833 links need clean up 
Fixes issue with edit this page on github #537

[Docs] link fixes

---

.github/workflows/auto-merge-successful-prs.yaml
.github/workflows/cla.yaml
.github/workflows/cron-jobs.yaml
.github/workflows/go.yaml
.github/workflows/integration-informing.yaml
.github/workflows/integration.yaml
.github/workflows/python.yaml
.github/workflows/sbom.yaml
.github/workflows/scorecard.yaml
.github/workflows/update-branches.yaml
.github/workflows/update-components.yaml

Removing git harden runner as part of our CI as it is a small startup and not critical.

Remove harden runner from CI

---

src/k8s/pkg/k8sd/features/cilium/ingress.go
src/k8s/pkg/k8sd/features/cilium/ingress_test.go

Backports https://github.com/canonical/k8s-snap/pull/848

[Backport 1.31] Fix cilium ingress, Refactor string literals

---

.github/workflows/automatic-doc-checks.yml

The YAML was malformed.
Also, I added it to the CI pipeline instead of just running it in the manual. workflow_dispatch.

Fix automatic-docs-check CI

---

docs/src/snap/reference/versions/1.31.md

* Add specific release date
* Remove bugs and issues section for initial release

Update 1.31 docs release notes

---

docs/src/capi/howto/custom-ck8s.md
docs/src/capi/tutorial/getting-started.md
docs/src/charm/howto/charm.md
docs/src/charm/tutorial/getting-started.md
docs/src/snap/howto/install/lxd.md
docs/src/snap/howto/install/offline.md
docs/src/snap/howto/install/snap.md
docs/src/snap/tutorial/add-remove-nodes.md
docs/src/snap/tutorial/getting-started.md

Update the install commands to reflect 1.31 candidate release

1.31 candidate install command

---

docs/src/_parts/bootstrap_config.md
docs/src/_parts/control_plane_join_config.md
docs/src/_parts/worker_join_config.md
src/k8s/go.mod
src/k8s/go.sum
src/k8s/pkg/k8sd/api/endpoints.go

Needs https://github.com/canonical/k8s-snap-api/pull/21
This PR replaces the literal string with `ReviewKubernetesAuthTokenRPC` from `k8s-snap-api`.

Add review kubernetes auth token RPC

---

src/k8s/pkg/k8sd/api/endpoints.go
src/k8s/pkg/k8sd/api/node_access_handler_test.go
src/k8s/pkg/snap/mock/provider.go

Add unit tests for the ValidateNodeTokenAccessHandler.
Add mock for Provider interface.

Add unit tests for token validator endpoints

---

docs/src/charm/howto/etcd.md

Highlighted in issue #905 this configuration option was not updated when datastore was changed to bootstrap-datastore

Update etcd guide config option

---

docs/canonicalk8s/custom_conf.py
docs/src/snap/explanation/security.md
docs/src/snap/howto/install/multipass.md
docs/src/snap/howto/security/disa-stig-assessment.md
docs/src/snap/howto/storage/ceph.md
docs/src/snap/howto/two-node-ha.md

Fix broken links and add list of links to ignore to custom_conf due to known sphinx issue with anchors causing false positives.

[Docs] Fix broken links

---

docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
docs/src/snap/howto/image-management.md
docs/src/snap/howto/index.md

Describes how to interact with the `ctr` binary to manually import, list images.

image management howto

---

docs/src/charm/howto/configure-cluster.md
docs/src/charm/howto/index.md

Add a page showing how to apply configuration options to your cluster using Juju.

Add Cluster Configuration using Juju

---

docs/src/capi/explanation/index.md
docs/src/capi/explanation/ingress.md
docs/src/capi/explanation/load-balancer.md
docs/src/charm/explanation/index.md
docs/src/charm/explanation/ingress.md
docs/src/charm/explanation/load-balancer.md
docs/src/snap/explanation/index.md
docs/src/snap/explanation/ingress.md
docs/src/snap/explanation/load-balancer.md
docs/src/snap/howto/networking/default-loadbalancer.md

This PR adds the load-balancer explanation page.

Load-balancer explanation page

---

docs/src/capi/explanation/capi-ck8s.md
docs/src/capi/explanation/in-place-upgrades.md
docs/src/capi/explanation/index.md
docs/src/capi/howto/custom-ck8s.md
docs/src/capi/howto/external-etcd.md
docs/src/capi/howto/migrate-management.md
docs/src/capi/howto/refresh-certs.md
docs/src/capi/howto/rollout-upgrades.md
docs/src/capi/howto/upgrade-providers.md
docs/src/capi/reference/annotations.md
docs/src/capi/reference/configs.md
docs/src/capi/tutorial/getting-started.md

This PR tries to improve the CAPI docs.

docs: CAPI docs review

---

docs/src/_parts/install.md
docs/src/charm/explanation/index.md
docs/src/charm/howto/cos-lite.md
docs/src/charm/howto/custom-registry.md
docs/src/charm/howto/etcd.md
docs/src/charm/howto/index.md
docs/src/charm/howto/install/install-custom.md
docs/src/charm/howto/install/install-lxd.md
docs/src/charm/howto/openstack.md
docs/src/charm/howto/proxy.md
docs/src/charm/howto/upgrade-minor.md
docs/src/charm/howto/upgrade-patch.md
docs/src/charm/index.md
docs/src/charm/reference/index.md

Each page is fixed in a separate commit. Some of the commit messages contain details on the changes.

 charm docs review improvements

---

docs/src/snap/howto/security/disa-stig-assessment.md
docs/src/snap/howto/security/hardening.md

Remove the concept of "Automated" testing from our docs.

DISA Stig hardening docs improvements

---

k8s/scripts/inspect.sh

This change updates inspect.sh to collect kernel logs and allows configuring the maximum number of snap log entries using the --num-snap-log-entries flag.

inspect.sh: dmesg logs + configurable number of snap log entries

---

docs/src/snap/howto/restore-quorum.md
docs/src/snap/howto/security/cis-assessment.md
docs/src/snap/howto/security/disa-stig-assessment.md
docs/src/snap/howto/security/hardening.md
docs/src/snap/howto/security/index.md

This PR contains minor improvements over k8s-snap security docs.

docs: Improve security docs

---

docs/canonicalk8s/styles/config/vocabularies/Canonical/accept.txt
docs/src/snap/howto/index.md
docs/src/snap/howto/observability.md

Adds howto documentation for Prometheus-based observability for Canonical K8s.

docs: Adds Prometheus howto guide

---

k8s/scripts/inspect.sh

Reverts canonical/k8s-snap#991

Revert "misc inspection script cleanup"

---

docs/src/snap/tutorial/add-remove-nodes.md
docs/src/snap/tutorial/getting-started.md
docs/src/snap/tutorial/index.md
docs/src/snap/tutorial/kubectl.md

Polishing and tweaking the tutorial pages. See each commit for details on each page.

Fix snap tutorials section

---

docs/canonicalk8s/index.md
docs/src/snap/explanation/about.md
docs/src/snap/howto/install/lxd.md
docs/src/snap/howto/install/offline.md
docs/src/snap/reference/community.md
docs/src/snap/tutorial/add-remove-nodes.md
docs/src/snap/tutorial/getting-started.md
docs/src/snap/tutorial/kubectl.md

Docs fixes until snap installation.

Review docs pages

---

docs/src/snap/howto/networking/default-ingress.md

Add warning for dual stack ingress

Add warning for dual stack ingress

---

tests/integration/lxd/setup-image.sh

Fix typo that causes the script to fail

Fix typo in setup-image.sh

---

docs/canonicalk8s/snap/howto/storage/ceph.md

* use `sudo k8s kubectl` instead of `kubectl`
* fix yaml manifests
Closes #1054

docs: Fix ceph how-to

---

docs/canonicalk8s/charm/howto/openstack.md

Backports https://github.com/canonical/k8s-snap/pull/1072

[Backport release-1.32] docs: Add fan-config instructions to Openstack how-to guide (#1072)

---

docs/canonicalk8s/snap/howto/install/custom-worker.md
docs/canonicalk8s/snap/howto/install/index.md

A how-to guide detailing joining a worker node to the cluster with a custom configuration

docs: How-to guide adding custom worker

---

docs/canonicalk8s/snap/explanation/cis.md

docs: Fix broken link

---

docs/canonicalk8s/charm/explanation/index.md
docs/canonicalk8s/charm/howto/index.md
docs/canonicalk8s/charm/howto/install/index.md
docs/canonicalk8s/charm/reference/index.md
docs/canonicalk8s/charm/tutorial/index.md

Final landing page rework PR. Same as the previous.

docs: charm landing rework

---

docs/canonicalk8s/charm/howto/openstack.md
docs/canonicalk8s/conf.py

This PR documents how the Openstack `healthmonitor` operates.

chore: Document openstack health monitor behavior

---

docs/canonicalk8s/charm/howto/custom-registry.md

docs: fix custom registry config name

---

docs/canonicalk8s/charm/howto/install/install-terraform.md

feat: Document terraform deployment with k8s-bundles
Dependent:
* https://github.com/canonical/k8s-bundles/pull/22

feat: document terraform deployment with k8s-bundles

---

docs/canonicalk8s/snap/explanation/index.md
docs/canonicalk8s/snap/explanation/roles.md
docs/canonicalk8s/snap/reference/roles.md

KU-2656
Adds documentation on kubernetes node roles.
No,

docs: node roles

---

src/k8s/pkg/k8sd/api/certificates_refresh.go
src/k8s/pkg/k8sd/api/certificates_update.go
src/k8s/pkg/utils/http.go
tests/integration/tests/test_clustering.py

This PR fixes a panic that happens during certs refresh.

fix: Fix certs refresh panic

---

.github/workflows/e2e-tests.yaml
tests/integration/templates/registry/hosts.toml
tests/integration/tests/conftest.py
tests/integration/tests/test_airgapped.py
tests/integration/tests/test_util/harness/lxd.py
tests/integration/tests/test_util/registry.py

Adds integration tests for:
* CK8s setup with internet access through proxy
* CK8s setup with private image registry

test: Add airgap test scenarios

---

.github/workflows/markdown.yaml

https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/

ci: remove compromised dependency

---

docs/canonicalk8s/capi/explanation/security.md
docs/canonicalk8s/charm/explanation/security.md
docs/canonicalk8s/custom_conf.py
docs/canonicalk8s/snap/explanation/security.md

The overview page has not been updated since last year.
Updated the docs with a more accurate view of how the project looks now. There will have to be more updates once more security measures are documented.

docs: Update security overview page

---

.github/workflows/nightly-test.yaml

The boolean logic was wrong. All checks need to pass for the bot to consider a run a success.

fix: require all checks to succeed for the MM bot to succeed

---

.github/workflows/nightly-test.yaml

fix: Remove MM bot dependency for disabled TICS test

---

.github/workflows/e2e-tests.yaml
.github/workflows/nightly-test.yaml
tests/integration/tests/test_cncf_conformace.py
tests/integration/tests/test_util/tags.py
tests/integration/tests/test_util/util.py

Adds the ``test_cncf_conformance`` test. It has the ``conformance_tests`` tag, preventing it from being run, unless specifically included through the tag. This test is only meant to be run on the Nightly job.

test: Adds Sonobuoy CNCF e2e nigthly tests

---

build-scripts/hack/requirements.txt

update-components job needs `packaging` to appropriately check versions
Add to the requirements.txt

fix: included packaging to component updater

---

docs/canonicalk8s/charm/explanation/index.md
docs/canonicalk8s/charm/howto/index.md
docs/canonicalk8s/charm/howto/report-security-issue.md
docs/canonicalk8s/charm/reference/index.md
docs/canonicalk8s/charm/reference/security.md
docs/canonicalk8s/snap/reference/security.md

Adding a reference page for security for the charm
Added security reference page 
Added how to report security issue for the charm
Drive by added crypto to snap security reference page too
N/A

docs: charm security reference page

---

tests/integration/tests/test_version_upgrades.py

Currently, the test_version_upgrades test does not take into account the configured ``TEST_SNAP`` (the built snap for testing the PR) when testing upgrades. This means that if there's a PR that breaks upgrades, we won't notice until the PR merges and gets published to the snap store, which is too late.
This commit addresses this issue by adding the ``TEST_SNAP`` to the upgrade test, helping ensure that the PR doesn't break upgrades.
``release-1.32``

test: Adds test snap to test_version_upgrades

---

docs/canonicalk8s/snap/reference/annotations.md
src/k8s/cmd/k8s/k8s_bootstrap_test.go
src/k8s/go.mod
src/k8s/go.sum
src/k8s/pkg/k8sd/features/cilium/chart.go
src/k8s/pkg/k8sd/features/cilium/internal.go
src/k8s/pkg/k8sd/features/cilium/internal_test.go
src/k8s/pkg/k8sd/features/cilium/network.go
src/k8s/pkg/utils/netlink.go

Backport of #1236 to `release-1.32`

[Backport release-1.32] fix: Cilium possible conflict with fan networking

---

k8s/crds/upgrades.k8sd.io.yaml
src/k8s/pkg/client/kubernetes/node.go
src/k8s/pkg/client/kubernetes/node_test.go
src/k8s/pkg/client/kubernetes/upgrades.go
src/k8s/pkg/client/snapd/snap_info.go
src/k8s/pkg/k8sd/api/cluster_remove.go
src/k8s/pkg/k8sd/app/hooks_join.go
src/k8s/pkg/k8sd/app/hooks_node_ready.go
src/k8s/pkg/k8sd/app/hooks_post_refresh.go
src/k8s/pkg/k8sd/app/hooks_remove.go
src/k8s/pkg/snap/interface.go
src/k8s/pkg/snap/mock/mock.go
src/k8s/pkg/snap/snap.go
src/k8s/pkg/snap/snap_test.go
tests/integration/tests/test_version_upgrades.py

I accidentally merged #1317 into #1316  instead of main.
Recreating the PR and merge again.

feat: Rollout feature upgrades

---

build-scripts/k8s_release.py

fix: Capture output of git branch

---

README.md
docs/canonicalk8s/_parts/install.md
docs/canonicalk8s/reuse/substitutions.yaml

This PR addresses the failed branch management tests.
Certain docs and files are updated with 1.33 to reflect the k8s component version.
N/A
N/A
The PR title is expected to contain one of the following prefixes, following the
[Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/):
* feat: A new feature
* fix: A bug fix
* docs: Documentation only changes
* style: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
* refactor: A code change that neither fixes a bug nor adds a feature
* perf: A code change that improves performance
* test: Adding missing tests or correcting existing tests
* build: Changes that affect the build system …

fix: Update docs to fix branch management tests

---

src/k8s/pkg/client/kubernetes/node.go
src/k8s/pkg/client/kubernetes/node_test.go

We need to make sure that the Kubernetes node is deleted when removing it from the Cluster. If an `500 Internal Error` occurs when doing so (e.g.: when the database is busy), we should retry.
Retry at most 5 times to remove the kubernetes node on a 500 Internal Error.
`release-1.33`, `release-1.32`

fix: Retry Kubernetes node removal on an internal server error

---

build-scripts/generate-bom.py

Currently, `generate-bom.py` only works in a snapcraft context due to how the paths are being constructed for the components git repository paths. Outside of that, the script does not render any of the components.
The script now handles regular contexts as well.
`release-1.32`

fix: BOM generation outside of snapcraft

---

tests/integration/tests/conftest.py
tests/integration/tests/test_util/config.py
tests/integration/tests/test_util/harness/lxd.py
tests/integration/tests/test_util/registry.py
tests/integration/tests/test_util/util.py

Backport of #1460 
Also required to backport (some) stuff from #1284

test: Retry snap install of pre-loaded snaps [Backport 1.32]

---

docs/canonicalk8s/snap/howto/install/dev-env.md

Adds more explanation to the developer installation guide.

docs: Updates developer installation guide

---

docs/canonicalk8s/snap/explanation/about.md
docs/canonicalk8s/snap/tutorial/getting-started.md

Clarifying items in the tutorial a new user found unclear
Add check system requirements to warning box 
Remove excessive next steps at the end of the tutorial 
Remove numbering 
Provide brief introduction into what Canonical K8s is so the user has some context
Explicitly state the bootstrap will print a success message
N/A
No

docs: Apply user feedback

---

docs/canonicalk8s/snap/reference/troubleshooting.md

Adding the workaround for the bridge interface to the snap troubleshooting page 
Raised on MM 
No

docs: Add bridge interface workaround to troubleshooting

---

.github/workflows/lint_and_integration.yaml
tests/integration/tests/test_annotations.py

test: Fix annotation test (#1529)

---

src/k8s/cmd/k8sd/k8sd.go
src/k8s/pkg/client/helm/client.go
tests/integration/tests/test_user_config.py

Backport of https://github.com/canonical/k8s-snap/pull/1564

fix: [Backport 1.32] Decide same helm values after merge

---

docs/canonicalk8s/snap/howto/networking/default-loadbalancer.md

docs: fix typo in loadbalancer link

---

docs/canonicalk8s/snap/howto/troubleshooting.md
k8s/scripts/inspect.sh

Backport of #1710 to `release-1.33`.

feat: Included managed-etcd service inspection [Backport release-1.32]

---

docs/README.md

During releases, sometimes the docs are not updated correctly.
Adding a list of steps that must be followed to ensure our docs stay up to date with each release
N/A
no

docs: Add docs release instructions to docs readme

---

README.md
docs/canonicalk8s/_parts/install.md
docs/canonicalk8s/reuse/substitutions.yaml

This PR updates some documentation changes needed for the 1.34 release

chore: 1.34 immediate documentation updates

---

.github/workflows/cut-release-branch.yaml
build-scripts/k8s_release.py

Cuts a new release branch when the PR containing Kubernetes minor version change gets merged.

feat: cut a release branch on minor version change

---

src/k8s/pkg/utils/endpoints.go

Follow up on https://github.com/canonical/k8s-snap/pull/1829

fix: endpoints port name nil check

---

.github/workflows/e2e-tests.yaml
tests/integration/tests/test_version_upgrades.py

Backports #1185 #1292 #1314 #1831

chore: backport missed commits for test_version_upgrades [Backport 1.32]
